CREATE TABLE [dbo].[AUC_CF_AUSCA_NO_AUSCO_CERT] (
    [CODFISC-W3]           VARCHAR (16) NULL,
    [FUNRETCO-W3]          VARCHAR (6)  NULL,
    [FUNERDES-W3]          VARCHAR (70) NULL,
    [CODFIS-01W]           VARCHAR (16) NULL,
    [CFVALID-01W]          VARCHAR (1)  NULL,
    [COGNOME-01W]          VARCHAR (36) NULL,
    [NOME-01W]             VARCHAR (36) NULL,
    [COGNACQU-01W]         VARCHAR (36) NULL,
    [DATNASCI-01W]         VARCHAR (8)  NULL,
    [SESSO-01W]            VARCHAR (1)  NULL,
    [CODCOMUN-01W]         VARCHAR (5)  NULL,
    [PROVNASC-01W]         VARCHAR (3)  NULL,
    [DECOCOMU-01W]         VARCHAR (37) NULL,
    [STATUS2-01W]          VARCHAR (1)  NULL,
    [DATMORTE-01W]         VARCHAR (8)  NULL,
    [EDIPARTA-01W]         VARCHAR (35) NULL,
    [EDIPARTB-01W]         VARCHAR (35) NULL,
    [EDIPARTC-01W]         VARCHAR (35) NULL,
    [EDICITTA-01W]         VARCHAR (35) NULL,
    [EDIPAESE-01W]         VARCHAR (3)  NULL,
    [CODARCA-W]            VARCHAR (11) NULL,
    [RESIDOM-03W]          VARCHAR (1)  NULL,
    [DATVARIA-03W]         VARCHAR (8)  NULL,
    [INDIRIZZ-03W]         VARCHAR (52) NULL,
    [CIVICO-03W]           VARCHAR (18) NULL,
    [INDIRIZB-03W]         VARCHAR (52) NULL,
    [INDIRIZC-03W]         VARCHAR (52) NULL,
    [INDIRIZD-03W]         VARCHAR (52) NULL,
    [CAP-03W]              VARCHAR (9)  NULL,
    [CODCOMUN-03W]         VARCHAR (5)  NULL,
    [PROVIND-03W]          VARCHAR (3)  NULL,
    [DECOCOMU-03W]         VARCHAR (37) NULL,
    [FRAZIONE-03W]         VARCHAR (35) NULL,
    [EDIPAESE-03W]         VARCHAR (3)  NULL,
    [filler]               VARCHAR (4)  NULL,
    [ausca_codice_pk]      INT          NULL,
    [ausco_codice_pk]      INT          NULL,
    [stato_record]         INT          NULL,
    [data_inizio_attivita] DATETIME     NULL,
    [ausca_ausco]          INT          NULL
);

