CREATE TABLE [dbo].[BDIN_INDIRIZ_SIN] (
    [BDIN_ID_VA]            BIGINT       NOT NULL,
    [BDIN_BDLC_APP_VR]      BIGINT       NULL,
    [BDIN_BDCP_ERI_VR]      BIGINT       NULL,
    [BDIN_DESCRIZ_VB]       VARCHAR (60) NULL,
    [BDIN_TOPONOMA_VB]      VARCHAR (60) NULL,
    [BDIN_MODREC_VB]        DATE         NULL,
    [BDIN_DATAINI_VB]       DATE         NOT NULL,
    [BDIN_DATAFINE_VB]      DATE         NULL,
    [BDIN_BDIN_ERI_VR]      BIGINT       NULL,
    [BDIN_RANGECIVICO_VB]   VARCHAR (50) NULL,
    [BDIN_BDST_ERI_VR]      BIGINT       NULL,
    [BDIN_UTENTE_VB]        VARCHAR (40) NOT NULL,
    [BDIN_COMPLEM_VB]       VARCHAR (25) NULL,
    [BDIN_RICERCA_VB]       VARCHAR (85) NULL,
    [BDIN_FRAZIONE_VB]      VARCHAR (50) NULL,
    [BDIN_ANCCO_SEQ_CAPCOM] BIGINT       NOT NULL,
    [BDIN_TOPONABB_VB]      VARCHAR (50) NULL,
    [BDIN_DESCRABB_VB]      VARCHAR (50) NULL,
    [BDIN_ADDRESS_VB]       BIGINT       NULL,
    [BDIN_FLAG_NORMALIZ]    VARCHAR (1)  NOT NULL,
    CONSTRAINT [PK_BDIN_INDIRIZ_SIN] PRIMARY KEY CLUSTERED ([BDIN_ID_VA] ASC)
);

