CREATE TABLE [dbo].[BDMS_COMPSOCI_CL] (
    [BDMS_BDSD_SRI_VR] BIGINT       NOT NULL,
    [BDMS_BDSU_SRI_VR] BIGINT       NOT NULL,
    [BDMS_DTINI_VB]    DATE         NOT NULL,
    [BDMS_DTFINE_VB]   DATE         NULL,
    [BDMS_ID_VA]       BIGINT       IDENTITY (300000, 1) NOT NULL,
    [BDMS_MODREC_VB]   DATETIME     NULL,
    [BDMS_MOTCHG_VB]   VARCHAR (1)  NULL,
    [BDMS_UTENTE_VB]   VARCHAR (40) NOT NULL,
    [BDMS_BDST_ERI_VR] BIGINT       NULL,
    CONSTRAINT [PK_BDMS_COMPSOCI_CL] PRIMARY KEY CLUSTERED ([BDMS_BDSD_SRI_VR] ASC, [BDMS_BDSU_SRI_VR] ASC, [BDMS_DTINI_VB] ASC),
    CONSTRAINT [BDMS_MOTCHG_CK] CHECK ([BDMS_MOTCHG_VB]='NULL' OR [BDMS_MOTCHG_VB]='E'),
    CONSTRAINT [FK_BDMS_BDSD_SRI_VR] FOREIGN KEY ([BDMS_BDSD_SRI_VR]) REFERENCES [dbo].[BDSD_SEDESOC_CL] ([BDSD_ID_VA]),
    CONSTRAINT [FK_BDMS_BDSU_SRI_VR] FOREIGN KEY ([BDMS_BDSU_SRI_VR]) REFERENCES [dbo].[BDSU_SEDEUFFI_CT] ([BDSU_ID_VA])
);

