CREATE TABLE [dbo].[BDRG_RGNATGIU_CT] (
    [BDRG_ID_VA]                 BIGINT        IDENTITY (1000, 1) NOT NULL,
    [BDRG_CODICE_VB]             VARCHAR (6)   NULL,
    [BDRG_DESCRIZ_VB]            VARCHAR (100) NULL,
    [BDRG_MODREC_VB]             DATETIME      NULL,
    [BDRG_NSI_VB]                VARCHAR (1)   CONSTRAINT [DF_BDRG_RGNATGIU_CT_BDRG_NSI_VB] DEFAULT ('S') NOT NULL,
    [BDRG_DATAINI_VB]            DATE          CONSTRAINT [DF_BDRG_RGNATGIU_CT_BDRG_DATAINI_VB] DEFAULT (CONVERT([date],'1948-01-01')) NOT NULL,
    [BDRG_DATAFIN_VB]            DATE          NULL,
    [BDRG_BDTS_ERI_VR]           BIGINT        NULL,
    [BDRG_AUC_CODICE_PK]         BIGINT        NULL,
    [BDRG_AUC_DATA_INSERIMENTO]  DATETIME      CONSTRAINT [DF_BDRG_RGNATGIU_CT_BDRG_AUC_DATA_INSERIMENTO] DEFAULT (getdate()) NULL,
    [BDRG_AUC_STATO_LAVORAZIONE] INT           CONSTRAINT [DF_BDRG_RGNATGIU_CT_BDRG_AUC_STATO_LAVORAZIONE] DEFAULT ((0)) NULL,
    [BDRG_AUC_PRESENTE]          INT           CONSTRAINT [DF_BDRG_RGNATGIU_CT_BDRG_AUC_PRESENTE] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_BDRG_RGNATGIU_CT] PRIMARY KEY CLUSTERED ([BDRG_ID_VA] ASC),
    CONSTRAINT [CK_BDRG_NSI_VB] CHECK ([BDRG_NSI_VB]='N' OR [BDRG_NSI_VB]='S'),
    CONSTRAINT [FK_BDRG_BDTS_ERI_VR] FOREIGN KEY ([BDRG_BDTS_ERI_VR]) REFERENCES [dbo].[BDTS_TIPOSOC_CT] ([BDTS_ID_VA])
);

