CREATE TABLE [dbo].[BDRL_RAPLEG_CL] (
    [BDRL_CODFISC_PG]  VARCHAR (11)  NOT NULL,
    [BDRL_CODFISC_PF]  VARCHAR (16)  NOT NULL,
    [BDRL_DATA_INIZIO] DATE          NOT NULL,
    [BDRL_BDRA_ID_VA]  BIGINT        NULL,
    [BDRL_DATA_FINE]   DATE          NULL,
    [BDRL_TIPOLOGIA]   VARCHAR (100) NULL,
    [BDRL_MODREC]      DATETIME      NULL,
    [BDRL_ESITO_SOGEI] VARCHAR (100) NULL,
    CONSTRAINT [PK_BDRL_RAPLEG_CL] PRIMARY KEY CLUSTERED ([BDRL_CODFISC_PG] ASC, [BDRL_CODFISC_PF] ASC, [BDRL_DATA_INIZIO] ASC),
    CONSTRAINT [FK_BDRL_BDRA_ID_VA] FOREIGN KEY ([BDRL_BDRA_ID_VA]) REFERENCES [dbo].[BDRA_RAPANAG_CL] ([BDRA_ID_VA])
);

