CREATE TABLE [dbo].[BDSD_SEDESOC_CL] (
    [BDSD_ID_VA]                 BIGINT       IDENTITY (300000, 1) NOT NULL,
    [BDSD_BDSE_APP_VR]           BIGINT       NOT NULL,
    [BDSD_BDSO_EDI_VR]           BIGINT       NOT NULL,
    [BDSD_CODINPS_VB]            VARCHAR (15) NULL,
    [BDSD_DATAFINE_VB]           DATE         NULL,
    [BDSD_DATAINI_VB]            DATE         NOT NULL,
    [BDSD_DESCRIZ_VB]            VARCHAR (60) NOT NULL,
    [BDSD_MODREC_VB]             DATETIME     NULL,
    [BDSD_UTENTE_VB]             VARCHAR (40) NOT NULL,
    [BDSD_BDST_ERI_VR]           BIGINT       NOT NULL,
    [BDSD_DTVAR_VB]              DATE         NULL,
    [BDSD_AUC_CODICE_PK]         BIGINT       NULL,
    [BDSD_AUC_DATA_INSERIMENTO]  DATETIME     CONSTRAINT [DF_BDSD_SEDESOC_CL_BDSD_AUC_DATA_INSERIMENTO] DEFAULT (getdate()) NULL,
    [BDSD_AUC_STATO_LAVORAZIONE] INT          CONSTRAINT [DF_BDSD_SEDESOC_CL_BDSD_AUC_STATO_LAVORAZIONE] DEFAULT ((0)) NULL,
    [BDSD_AUC_CF_PK]             VARCHAR (16) NULL,
    [BDSD_AUC_AUSCA_PK]          INT          CONSTRAINT [DF_BDSD_SEDESOC_CL_BDSD_AUC_AUSCA_PK] DEFAULT ((0)) NULL,
    [BDSD_AUC_PRESENTE]          INT          CONSTRAINT [DF_BDSD_SEDESOC_CL_BDSD_AUC_PRESENTE] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_BDSD_SEDESOC_CL] PRIMARY KEY CLUSTERED ([BDSD_ID_VA] ASC),
    CONSTRAINT [FK_BDSD_BDSE_APP_VR] FOREIGN KEY ([BDSD_BDSE_APP_VR]) REFERENCES [dbo].[BDSE_TIPOSEDE_CT] ([BDSE_ID_VA]),
    CONSTRAINT [FK_BDSD_BDSO_EDI_VR] FOREIGN KEY ([BDSD_BDSO_EDI_VR]) REFERENCES [dbo].[BDSO_SOCIETA_CL] ([BDSO_ID_VA])
);

