CREATE TABLE [dbo].[BDSE_TIPOSEDE_CT] (
    [BDSE_ID_VA]      BIGINT       NOT NULL,
    [BDSE_CODICE_VB]  VARCHAR (3)  NOT NULL,
    [BDSE_DESCRIZ_VB] VARCHAR (15) NOT NULL,
    [BDSE_MODREC_VB]  DATE         NULL,
    [BDSE_DATAINI_VB] DATE         NOT NULL,
    [BDSE_DATAFIN_VB] DATE         NULL,
    [BDSE_NSI_VB]     VARCHAR (1)  NOT NULL,
    CONSTRAINT [PK_BDSE_TIPOSEDE_CT] PRIMARY KEY CLUSTERED ([BDSE_ID_VA] ASC),
    CONSTRAINT [BDSE_NSI_CK] CHECK ([BDSE_NSI_VB]='N' OR [BDSE_NSI_VB]='S')
);

