CREATE TABLE [dbo].[BDST_SISTEMA_CT] (
    [BDST_ID_VA]        BIGINT        NOT NULL,
    [BDST_DESCRIZ_VB]   VARCHAR (100) NOT NULL,
    [BDST_LIVELLO_VB]   INT           NULL,
    [BDST_SCAPP_ERI_VR] VARCHAR (2)   NULL,
    CONSTRAINT [PK_BDST_SISTEMA_CT] PRIMARY KEY CLUSTERED ([BDST_ID_VA] ASC)
);

