CREATE TABLE [dbo].[BDSV_SOCVER_CL] (
    [BDSV_ID_VA]                 BIGINT       IDENTITY (4500000, 1) NOT NULL,
    [BDSV_BDSO_APP_VR]           BIGINT       NOT NULL,
    [BDSV_BDSO_VER_VR]           BIGINT       NOT NULL,
    [BDSV_DATAFIN_VB]            DATE         NULL,
    [BDSV_DATAINI_VB]            DATE         NOT NULL,
    [BDSV_ECTO_PER_VR]           BIGINT       NOT NULL,
    [BDSV_MODREC_VB]             DATETIME     NULL,
    [BDSV_UTENTE_VB]             VARCHAR (40) CONSTRAINT [DF_BDRS_BDSV_SOCVER_CL_BDSV_UTENTE_VB] DEFAULT ('Default NSI') NULL,
    [BDSV_BDST_ERI_VR]           BIGINT       NULL,
    [BDSV_AUC_CODICE_PK]         BIGINT       NULL,
    [BDSV_AUC_DATA_INSERIMENTO]  DATETIME     CONSTRAINT [DF_BDSV_SOCVER_CL_BDSV_DATA_INSERIMENTO] DEFAULT (getdate()) NULL,
    [BDSV_AUC_STATO_LAVORAZIONE] INT          CONSTRAINT [DF_BDSV_SOCVER_CL_DBSV_AUC_STATO_LAVORAZIONE] DEFAULT ((0)) NULL,
    [BDSV_AUC_CF_APP_PK]         VARCHAR (16) NULL,
    [BDSV_AUC_CF_VER_PK]         VARCHAR (16) NULL,
    [BDSV_AUC_AUSCA_APP_PK]      INT          NULL,
    [BDSV_AUC_AUSCA_VER_PK]      INT          NULL,
    [BDSV_AUC_PRESENTE]          INT          CONSTRAINT [DF_BDSV_SOCVER_CL_BDSV_AUC_PRESENTE] DEFAULT ((0)) NULL,
    [BDSV_ECTO_DESCRIZIONE]      VARCHAR (60) NULL,
    CONSTRAINT [PK_BDSV_SOCVER_CL] PRIMARY KEY CLUSTERED ([BDSV_ID_VA] ASC),
    CONSTRAINT [FK_BDSV_BDSO_APP_VR] FOREIGN KEY ([BDSV_BDSO_APP_VR]) REFERENCES [dbo].[BDSO_SOCIETA_CL] ([BDSO_ID_VA]),
    CONSTRAINT [FK_BDSV_BDSO_VER_VR] FOREIGN KEY ([BDSV_BDSO_VER_VR]) REFERENCES [dbo].[BDSO_SOCIETA_CL] ([BDSO_ID_VA])
);

