CREATE TABLE [dbo].[BDTS_TIPOSOC_CT] (
    [BDTS_ID_VA]                 BIGINT       IDENTITY (50, 1) NOT NULL,
    [BDTS_CODICE_VB]             VARCHAR (3)  NULL,
    [BDTS_DESCRIZ_VB]            VARCHAR (60) NULL,
    [BDTS_MODREC_VB]             DATETIME     NULL,
    [BDTS_DATAINI_VB]            DATE         CONSTRAINT [DF_BDTS_TIPOSOC_CT_BDTS_DATAINI_VB] DEFAULT (CONVERT([date],'1948-01-01')) NOT NULL,
    [BDTS_DATAFIN_VB]            DATE         NULL,
    [BDTS_NSI_VB]                VARCHAR (1)  CONSTRAINT [DF_BDTS_TIPOSOC_CT_BDTS_NSI_VB] DEFAULT ('S') NOT NULL,
    [BDTS_FLGDCE_VB]             VARCHAR (1)  CONSTRAINT [DF_BDTS_TIPOSOC_CT_BDTS_FLGDCE_VB] DEFAULT ('N') NOT NULL,
    [BDTS_AUC_CODICE_PK]         BIGINT       NULL,
    [BDTS_AUC_DATA_INSERIMENTO]  DATETIME     CONSTRAINT [DF_BDTS_TIPOSOC_CT_BDTS_AUC_DATA_INSERIMENTO] DEFAULT (getdate()) NULL,
    [BDTS_AUC_STATO_LAVORAZIONE] INT          CONSTRAINT [DF_BDTS_TIPOSOC_CT_BDTS_AUC_STATO_LAVORAZIONE] DEFAULT ((0)) NULL,
    [BDTS_AUC_PRESENTE]          INT          CONSTRAINT [DF_BDTS_TIPOSOC_CT_BDTS_AUC_PRESENTE] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_BDTS_TIPOSOC_CT] PRIMARY KEY CLUSTERED ([BDTS_ID_VA] ASC),
    CONSTRAINT [BDTS_NSI_CK] CHECK ([BDTS_NSI_VB]='N' OR [BDTS_NSI_VB]='S'),
    CONSTRAINT [CK1_BDTS_FLGDCE_VB] CHECK ([BDTS_FLGDCE_VB]='N' OR [BDTS_FLGDCE_VB]='S')
);

