CREATE TABLE [dbo].[elenco_posizioni] (
    [codice_fiscale]           VARCHAR (16)  NULL,
    [codice_gruppo]            VARCHAR (20)  NULL,
    [denominazione]            VARCHAR (405) NULL,
    [nome]                     VARCHAR (200) NULL,
    [cognome]                  VARCHAR (200) NULL,
    [codice_ateco_2007]        VARCHAR (20)  NULL,
    [codice_ateco_1991]        VARCHAR (20)  NULL,
    [CSC]                      VARCHAR (10)  NULL,
    [CA]                       VARCHAR (30)  NULL,
    [numero_dipendenti]        INT           NULL,
    [data_inizio_attivita]     DATETIME      NULL,
    [data_cessazione]          DATETIME      NULL,
    [data_domanda]             DATETIME      NULL,
    [toponimo_SL]              VARCHAR (50)  NULL,
    [codice_toponimo_SL]       VARCHAR (3)   NULL,
    [indirizzo_SL]             VARCHAR (100) NULL,
    [civico_SL]                VARCHAR (50)  NULL,
    [CAP_SL]                   VARCHAR (5)   NULL,
    [comune_SL]                VARCHAR (100) NULL,
    [provincia_SL]             VARCHAR (2)   NULL,
    [telefono1]                VARCHAR (20)  NULL,
    [telefono2]                VARCHAR (20)  NULL,
    [fax]                      VARCHAR (20)  NULL,
    [email]                    VARCHAR (160) NULL,
    [PEC]                      VARCHAR (160) NULL,
    [posizione_AUC]            VARCHAR (20)  NULL,
    [toponimo_SO]              VARCHAR (50)  NULL,
    [codice_toponimo_SO]       VARCHAR (3)   NULL,
    [indirizzo_SO]             VARCHAR (100) NULL,
    [civico_SO]                VARCHAR (50)  NULL,
    [CAP_SO]                   VARCHAR (5)   NULL,
    [comune_SO]                VARCHAR (100) NULL,
    [provincia_SO]             VARCHAR (2)   NULL,
    [codice_categoria]         VARCHAR (3)   NULL,
    [codice_compartimento]     VARCHAR (1)   NULL,
    [codice_fiscale_SOG]       VARCHAR (16)  NULL,
    [nome_SOG]                 VARCHAR (200) NULL,
    [cognome_SOG]              VARCHAR (200) NULL,
    [toponimo_SOG]             VARCHAR (50)  NULL,
    [codice_toponimo_SOG]      VARCHAR (3)   NULL,
    [indirizzo_SOG]            VARCHAR (100) NULL,
    [civico_SOG]               VARCHAR (20)  NULL,
    [CAP_SOG]                  VARCHAR (5)   NULL,
    [comune_SOG]               VARCHAR (100) NULL,
    [provincia_SOG]            VARCHAR (2)   NULL,
    [tipo_SOG]                 VARCHAR (3)   NULL,
    [data_inizio_SOG]          DATETIME      NULL,
    [data_fine_SOG]            DATETIME      NULL,
    [data_elaborazione]        DATETIME      NULL,
    [esito_elaborazione]       INT           NULL,
    [matricola_assegnata]      VARCHAR (10)  NULL,
    [denominazione_posizione]  VARCHAR (405) NULL,
    [flag_lavorabile]          VARCHAR (1)   CONSTRAINT [DF_elenco_posizioni_flag_lavorabile] DEFAULT ('N') NULL,
    [tipo_lavorazione]         INT           CONSTRAINT [DF_elenco_posizioni_tipo_lavorazione] DEFAULT ((0)) NULL,
    [comune_nascita_SOG]       VARCHAR (50)  NULL,
    [data_nascita_SOG]         DATETIME      NULL,
    [indirizzo_SL_F]           VARCHAR (100) NULL,
    [indirizzo_SO_F]           VARCHAR (100) NULL,
    [provincia_nascita_SOG]    VARCHAR (2)   NULL,
    [toponimo_attivita]        VARCHAR (50)  NULL,
    [codice_toponimo_attivita] VARCHAR (3)   NULL,
    [indirizzo_attivita]       VARCHAR (100) NULL,
    [civico_attivita]          VARCHAR (20)  NULL,
    [CAP_attivita]             VARCHAR (5)   NULL,
    [comune_attivita]          VARCHAR (100) NULL,
    [provincia_attivita]       VARCHAR (2)   NULL,
    [dt_in_att]                VARCHAR (20)  NULL,
    [dt_ces_att]               VARCHAR (20)  NULL,
    [indirizzo_att_F]          VARCHAR (100) NULL
);

