CREATE TABLE [dbo].[ERROR_LOG] (
    [TABLE_NAME] VARCHAR (100)  NOT NULL,
    [TABLE_KEY]  VARCHAR (1000) NOT NULL,
    [ERR_DATE]   DATE           NOT NULL,
    [ERR_DESC]   VARCHAR (200)  NULL
);

