CREATE TABLE [dbo].[Import_ausca_sog_contr_azienda] (
    [St_ausca_codice_pk]                    INT            NULL,
    [St_ausca_denominazione]                VARCHAR (405)  NULL,
    [St_ausca_codice_fiscale]               VARCHAR (16)   NULL,
    [St_ausca_cciaa]                        VARCHAR (2)    NULL,
    [St_ausca_aungi_codice_pk]              INT            NULL,
    [St_ausca_indirizzo]                    VARCHAR (255)  NULL,
    [St_ausca_codice_toponimo]              VARCHAR (3)    NULL,
    [St_ausca_Nome_Via]                     VARCHAR (255)  NULL,
    [St_ausca_Toponimo]                     VARCHAR (50)   NULL,
    [St_ausca_civico]                       VARCHAR (50)   NULL,
    [St_ausca_localita]                     VARCHAR (50)   NULL,
    [St_ausca_sede_legale_italia]           VARCHAR (1)    NULL,
    [St_ausca_codice_comune]                VARCHAR (4)    NULL,
    [St_ausca_descr_comune]                 VARCHAR (30)   NULL,
    [St_ausca_sigla_provincia]              VARCHAR (2)    NULL,
    [St_ausca_regione]                      VARCHAR (25)   NULL,
    [St_ausca_codice_stato_estero]          VARCHAR (4)    NULL,
    [St_ausca_cap]                          VARCHAR (10)   NULL,
    [St_ausca_CodiceFormaGiuridica]         VARCHAR (50)   NULL,
    [St_ausca_FormaGiuridica]               VARCHAR (100)  NULL,
    [St_ausca_Stato]                        VARCHAR (50)   NULL,
    [St_ausca_telefono1]                    VARCHAR (20)   NULL,
    [St_ausca_telefono2]                    VARCHAR (20)   NULL,
    [St_ausca_telefono3]                    VARCHAR (20)   NULL,
    [St_ausca_fax]                          VARCHAR (20)   NULL,
    [St_ausca_email]                        VARCHAR (162)  NULL,
    [St_ausca_PEC]                          VARCHAR (162)  NULL,
    [St_ausca_auate_codice_pk]              INT            NULL,
    [St_ausca_auate1991_codice_pk]          INT            NULL,
    [St_ausca_auate2002_codice_pk]          INT            NULL,
    [St_ausca_auate2007_codice_pk]          INT            NULL,
    [St_ausca_soggetto_certificato]         CHAR (1)       NULL,
    [St_ausca_data_variazione_stato]        DATE           NULL,
    [St_ausca_auten_codice_pk]              INT            NULL,
    [St_ausca_codice_entita_riferimento]    INT            NULL,
    [St_ausca_note]                         VARCHAR (50)   NULL,
    [St_ausca_ATECO_2002]                   VARCHAR (20)   NULL,
    [St_ausca_ATECO_2007]                   VARCHAR (20)   NULL,
    [St_ausca_DesATECO_2002]                VARCHAR (200)  NULL,
    [St_ausca_DesATECO_2007]                VARCHAR (200)  NULL,
    [St_ausca_Data_Inizio_Attivita]         DATE           NULL,
    [St_ausca_Data_Fine_Attivita]           DATE           NULL,
    [St_ausca_Filename]                     VARCHAR (1000) NULL,
    [St_ausca_data_domandafile]             VARCHAR (200)  NULL,
    [St_ausca_TipologiaFile]                VARCHAR (100)  NULL,
    [St_ausca_MatricolaGestioneAziende]     VARCHAR (10)   NULL,
    [St_ausca_NomeFileVisuraOriginale]      VARCHAR (1000) NULL,
    [St_ausca_NomeOriginale_Prov1]          VARCHAR (50)   NULL,
    [St_ausca_NomeOriginale_Anno]           VARCHAR (10)   NULL,
    [St_ausca_NomeOriginale_Progressivo1]   VARCHAR (100)  NULL,
    [St_ausca_NomeOriginale_Visura]         VARCHAR (1000) NULL,
    [St_ausca_NomeOriginale_Prov2]          VARCHAR (50)   NULL,
    [St_ausca_NomeOriginale_NumREA]         VARCHAR (50)   NULL,
    [St_ausca_NumeroREA_Visura]             VARCHAR (20)   NULL,
    [St_ausca_FLAG]                         TINYINT        NULL,
    [St_ausca_PRESENTE]                     CHAR (1)       CONSTRAINT [St_ausca_PRESENTE_def] DEFAULT ('X') NULL,
    [St_ausca_data_modifica]                DATETIME       NULL,
    [St_ausca_descr_utente]                 VARCHAR (50)   NULL,
    [St_ausca_piva]                         VARCHAR (11)   NULL,
    [St_ausca_data_iscrizione]              VARCHAR (10)   NULL,
    [St_codice_stato_infocamere]            VARCHAR (5)    NULL,
    [St_descr_stato_infocamere]             VARCHAR (100)  NULL,
    [Presenti_POC_DM]                       VARCHAR (1)    NULL,
    [St_ausca_PRESENTE_Aggiornata]          VARCHAR (1)    NULL,
    [st_ausca_descrizione_01]               VARCHAR (100)  NULL,
    [st_ausca_descrizione_02]               VARCHAR (100)  NULL,
    [st_ausca_descrizione_03]               VARCHAR (100)  NULL,
    [St_ausca_stato_impresa]                VARCHAR (50)   NULL,
    [st_ausca_n_iscrizione_ri]              VARCHAR (21)   NULL,
    [st_ausca_c_n_iscrizione_ri_old]        VARCHAR (21)   NULL,
    [st_ausca_c_fonte]                      VARCHAR (2)    NULL,
    [st_ausca_f_aggiornamento]              VARCHAR (1)    NULL,
    [st_ausca_dt_annotazione]               DATE           NULL,
    [st_ausca_dt_iscrizione_rea]            DATE           NULL,
    [st_ausca_dt_iscrizione_ri]             DATE           NULL,
    [st_ausca_codice_iscrizione_01]         VARCHAR (3)    NULL,
    [st_ausca_dt_iscrizione_sezione_01]     DATE           NULL,
    [st_ausca_f_colt_diretto_01]            VARCHAR (1)    NULL,
    [st_ausca_codice_iscrizione_02]         VARCHAR (3)    NULL,
    [st_ausca_dt_iscrizione_sezione_02]     DATE           NULL,
    [st_ausca_f_colt_diretto_02]            VARCHAR (1)    NULL,
    [st_ausca_codice_iscrizione_03]         VARCHAR (3)    NULL,
    [st_ausca_dt_iscrizione_sezione_03]     DATE           NULL,
    [st_ausca_f_colt_diretto_03]            VARCHAR (1)    NULL,
    [st_ausca_c_stato]                      VARCHAR (1)    NULL,
    [st_ausca_dt_inizio_attivita_impresa]   DATE           NULL,
    [st_ausca_c_causale_canc]               VARCHAR (2)    NULL,
    [st_ausca_dt_cessazione_canc]           DATE           NULL,
    [st_ausca_dt_domanda_canc]              DATE           NULL,
    [st_ausca_dt_canc_canc]                 DATE           NULL,
    [st_ausca_codice_tipo_trasferimento]    VARCHAR (1)    NULL,
    [st_ausca_dt_cessazione_trasferimento]  DATE           NULL,
    [st_ausca_codice_causale_trasferimento] VARCHAR (2)    NULL,
    [st_ausca_dt_cessazione_att_canc]       DATE           NULL,
    [st_ausca_causale_cancellazione]        VARCHAR (100)  NULL,
    [St_Attivita_esercitata]                VARCHAR (500)  NULL,
    [St_Attivita_secondaria_esercitata]     VARCHAR (500)  NULL
);

