CREATE TABLE [dbo].[Import_aucon_concorsuale] (
    [aucon_codice_pk]                     BIGINT        NULL,
    [aucon_ausca_codice_pk]               BIGINT        NULL,
    [aucon_f_presenza_info]               VARCHAR (1)   NULL,
    [aucon_codice_fiscale]                VARCHAR (16)  NULL,
    [aucon_data_iscrizione]               DATE          NULL,
    [aucon_tribunale]                     VARCHAR (100) NULL,
    [aucon_num_registrazione]             VARCHAR (20)  NULL,
    [aucon_data_registrazione]            DATE          NULL,
    [aucon_localita_uff_registro]         VARCHAR (50)  NULL,
    [aucon_prov_uff_registro]             VARCHAR (2)   NULL,
    [aucon_cciaa_fuori_provincia]         VARCHAR (2)   NULL,
    [aucon_codice_liquidazione]           VARCHAR (5)   NULL,
    [aucon_descr_liquidazione]            VARCHAR (50)  NULL,
    [aucon_data_iscrizione_procedura]     DATE          NULL,
    [aucon_codice_atto]                   VARCHAR (5)   NULL,
    [aucon_descrizione_atto]              VARCHAR (100) NULL,
    [aucon_FLAG]                          TINYINT       NULL,
    [aucon_PRESENTE]                      CHAR (1)      NULL,
    [aucon_data_modifica]                 DATETIME      NULL,
    [aucon_descr_utente]                  VARCHAR (50)  NULL,
    [aucon_data_atto]                     DATE          NULL,
    [aucon_notaio]                        VARCHAR (80)  NULL,
    [aucon_Accordi_Debiti]                VARCHAR (MAX) NULL,
    [aucon_Annotazioni_Procedure]         VARCHAR (MAX) NULL,
    [aucon_Appelli_Reclami]               VARCHAR (MAX) NULL,
    [aucon_Cessazione_Esercizio_Provv]    VARCHAR (MAX) NULL,
    [aucon_Continuazione_Esercizio_Provv] VARCHAR (MAX) NULL,
    [aucon_data_chiusura]                 DATE          NULL,
    [aucon_data_esecuzione]               DATE          NULL,
    [aucon_data_omologazione]             DATE          NULL,
    [aucon_data_provvedimento]            DATE          NULL,
    [aucon_data_revoca]                   DATE          NULL,
    [aucon_data_termine]                  DATE          NULL,
    [aucon_Esecuzione_Concordato]         VARCHAR (MAX) NULL,
    [aucon_Esercizio_Provvisorio]         VARCHAR (MAX) NULL,
    [aucon_Proposta_Concordato]           VARCHAR (MAX) NULL,
    [aucon_Rapporto_Curatore]             VARCHAR (MAX) NULL,
    [data_chiusura]                       DATE          NULL,
    [data_esecuzione]                     DATE          NULL,
    [data_omologazione]                   DATE          NULL,
    [data_provvedimento]                  DATE          NULL,
    [data_revoca]                         DATE          NULL,
    [data_termine]                        DATE          NULL,
    [st_aucon_altre_indicazioni]          VARCHAR (40)  NULL
);

