CREATE TABLE [dbo].[IndirizziDelegheANALISI] (
    [CFImpresa]            VARCHAR (50)   NULL,
    [Matricola]            VARCHAR (50)   NULL,
    [RagioneSociale]       VARCHAR (200)  NULL,
    [CodiceFiscale]        VARCHAR (50)   NULL,
    [Cognome]              VARCHAR (200)  NULL,
    [Nome]                 VARCHAR (200)  NULL,
    [Nazione]              VARCHAR (50)   NULL,
    [Provincia]            VARCHAR (50)   NULL,
    [Comune]               VARCHAR (100)  NULL,
    [Cap]                  VARCHAR (50)   NULL,
    [PrefissoStradale]     VARCHAR (50)   NULL,
    [Indirizzo]            VARCHAR (1000) NULL,
    [NumeroCivico]         VARCHAR (50)   NULL,
    [ausca_provincia]      VARCHAR (2)    NULL,
    [ausca_comune]         VARCHAR (50)   NULL,
    [ausca_cap]            VARCHAR (5)    NULL,
    [ausca_toponimo]       VARCHAR (50)   NULL,
    [ausca_indirizzo]      VARCHAR (200)  NULL,
    [ausca_civico]         VARCHAR (50)   NULL,
    [aupoc_provincia]      VARCHAR (2)    NULL,
    [aupoc_comune]         VARCHAR (50)   NULL,
    [aupoc_cap]            VARCHAR (5)    NULL,
    [aupoc_toponimo]       VARCHAR (50)   NULL,
    [aupoc_indirizzo]      VARCHAR (200)  NULL,
    [aupoc_civico]         VARCHAR (50)   NULL,
    [ausca_codice_pk]      INT            NULL,
    [aupoc_codice_pk]      INT            NULL,
    [ausca_codice_fiscale] VARCHAR (16)   NULL,
    [ausca_piva]           VARCHAR (11)   NULL,
    [ausca_flag_01]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_ausca_flag_01] DEFAULT ((0)) NULL,
    [ausca_flag_02]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_ausca_flag_02] DEFAULT ((0)) NULL,
    [ausca_flag_03]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_ausca_flag_03] DEFAULT ((0)) NULL,
    [ausca_flag_04]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_ausca_flag_04] DEFAULT ((0)) NULL,
    [ausca_flag_05]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_ausca_flag_05] DEFAULT ((0)) NULL,
    [ausca_flag_06]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_ausca_flag_06] DEFAULT ((0)) NULL,
    [ausca_flag_07]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_ausca_flag_07] DEFAULT ((0)) NULL,
    [ausca_flag_08]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_ausca_flag_08] DEFAULT ((0)) NULL,
    [ausca_flag_09]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_ausca_flag_09] DEFAULT ((0)) NULL,
    [ausca_flag_10]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_ausca_flag_10] DEFAULT ((0)) NULL,
    [ausca_flag_11]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_ausca_flag_11] DEFAULT ((0)) NULL,
    [ausca_flag_12]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_ausca_flag_12] DEFAULT ((0)) NULL,
    [ausca_flag_13]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_ausca_flag_13] DEFAULT ((0)) NULL,
    [ausca_flag_14]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_ausca_flag_14] DEFAULT ((0)) NULL,
    [ausca_flag_15]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_ausca_flag_15] DEFAULT ((0)) NULL,
    [ausca_flag_16]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_ausca_flag_16] DEFAULT ((0)) NULL,
    [ausca_flag_17]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_ausca_flag_17] DEFAULT ((0)) NULL,
    [ausca_flag_18]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_ausca_flag_18] DEFAULT ((0)) NULL,
    [ausca_flag_19]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_ausca_flag_19] DEFAULT ((0)) NULL,
    [ausca_flag_20]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_ausca_flag_20] DEFAULT ((0)) NULL,
    [aupoc_flag_01]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_aupoc_flag_01] DEFAULT ((0)) NULL,
    [aupoc_flag_02]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_aupoc_flag_02] DEFAULT ((0)) NULL,
    [aupoc_flag_03]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_aupoc_flag_03] DEFAULT ((0)) NULL,
    [aupoc_flag_04]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_aupoc_flag_04] DEFAULT ((0)) NULL,
    [aupoc_flag_05]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_aupoc_flag_05] DEFAULT ((0)) NULL,
    [aupoc_flag_06]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_aupoc_flag_06] DEFAULT ((0)) NULL,
    [aupoc_flag_07]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_aupoc_flag_07] DEFAULT ((0)) NULL,
    [aupoc_flag_08]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_aupoc_flag_08] DEFAULT ((0)) NULL,
    [aupoc_flag_09]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_aupoc_flag_09] DEFAULT ((0)) NULL,
    [aupoc_flag_10]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_aupoc_flag_10] DEFAULT ((0)) NULL,
    [aupoc_flag_11]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_aupoc_flag_11] DEFAULT ((0)) NULL,
    [aupoc_flag_12]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_aupoc_flag_12] DEFAULT ((0)) NULL,
    [aupoc_flag_13]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_aupoc_flag_13] DEFAULT ((0)) NULL,
    [aupoc_flag_14]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_aupoc_flag_14] DEFAULT ((0)) NULL,
    [aupoc_flag_15]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_aupoc_flag_15] DEFAULT ((0)) NULL,
    [aupoc_flag_16]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_aupoc_flag_16] DEFAULT ((0)) NULL,
    [aupoc_flag_17]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_aupoc_flag_17] DEFAULT ((0)) NULL,
    [aupoc_flag_18]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_aupoc_flag_18] DEFAULT ((0)) NULL,
    [aupoc_flag_19]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_aupoc_flag_19] DEFAULT ((0)) NULL,
    [aupoc_flag_20]        INT            CONSTRAINT [DF_IndirizziDelegheANALISI_aupoc_flag_20] DEFAULT ((0)) NULL
);

