CREATE TABLE [dbo].[RappLegaliStorico] (
    [ID_Gestionale]     INT           NOT NULL,
    [CodiceFiscale]     VARCHAR (16)  NOT NULL,
    [Cognome]           VARCHAR (255) NULL,
    [Nome]              VARCHAR (150) NULL,
    [Toponimo]          VARCHAR (50)  NULL,
    [Numerocivico]      VARCHAR (50)  NULL,
    [Comune]            VARCHAR (45)  NULL,
    [Provincia]         VARCHAR (2)   NULL,
    [Cap]               VARCHAR (5)   NULL,
    [PEC]               VARCHAR (160) NULL,
    [Email]             VARCHAR (160) NULL,
    [DataInizio]        DATETIME      NULL,
    [DataFine]          DATETIME      NULL,
    [FonteAcq]          INT           NOT NULL,
    [CodiceTipologia]   INT           NOT NULL,
    [CodiceFiscaleSost] VARCHAR (16)  NULL,
    [CodiceFiscaleSoc]  VARCHAR (16)  NULL,
    [Protocollo]        VARCHAR (25)  NULL,
    [Note]              VARCHAR (255) NULL,
    [DataPresDomanda]   DATETIME      NULL,
    [DataInserimento]   DATETIME      NULL,
    [FlagInsert]        INT           NULL,
    [DataVariazione]    DATETIME      NULL,
    [FlagVariato]       CHAR (1)      NULL,
    [Provenienza]       VARCHAR (10)  NULL,
    [DescrTipologia]    VARCHAR (255) NULL,
    [DescrFonte]        VARCHAR (255) NULL
);

