CREATE TABLE [dbo].[st_aupgi_pg_iscritte_inpdap] (
    [aupgi_id_sin]                   VARCHAR (10)  NULL,
    [aupgi_cf]                       VARCHAR (16)  NULL,
    [aupgi_progressivo]              VARCHAR (5)   NULL,
    [aupgi_denominazione]            VARCHAR (400) NULL,
    [aupgi_data_validita]            DATETIME      NULL,
    [aupgi_data_istituzione]         DATETIME      NULL,
    [aupgi_data_cessazione]          DATETIME      NULL,
    [aupgi_descrizione]              VARCHAR (100) NULL,
    [aupgi_particella]               VARCHAR (30)  NULL,
    [aupgi_complemento]              VARCHAR (15)  NULL,
    [aupgi_strada]                   VARCHAR (100) NULL,
    [aupgi_civico]                   VARCHAR (20)  NULL,
    [aupgi_localita]                 VARCHAR (200) NULL,
    [aupgi_frazione]                 VARCHAR (200) NULL,
    [aupgi_cap]                      VARCHAR (5)   NULL,
    [aupgi_id_conflluito]            VARCHAR (10)  NULL,
    [aupgi_cf_confluito]             VARCHAR (16)  NULL,
    [aupgi_progessivo_confluito]     VARCHAR (5)   NULL,
    [aupgi_sigla_provincia]          VARCHAR (2)   NULL,
    [AUPGI_AUSCA_CODICE_PK]          INT           CONSTRAINT [DF2_st_aupgi_pg_iscritte_inpdap_AUPGI_AUSCA_CODICE_PK] DEFAULT ((0)) NULL,
    [aupgi_posizione]                VARCHAR (50)  NULL,
    [aupgi_auspc_stato_posizione]    INT           CONSTRAINT [DF2_st_aupgi_pg_iscritte_inpdap_aupgi_auspc_stato_posizione] DEFAULT ((0)) NULL,
    [AUPGI_AUPOC_CODICE_PK]          INT           CONSTRAINT [DF2_st_aupgi_pg_iscritte_inpdap_AUPGI_AUPOC_CODICE_PK] DEFAULT ((0)) NULL,
    [aupgi_auapp_codice_pk]          INT           CONSTRAINT [DF2_st_aupgi_pg_iscritte_inpdap_aupgi_auapp_codice_pk] DEFAULT ((0)) NULL,
    [aupgi_aurea_codice_pk]          INT           CONSTRAINT [DF2_st_aupgi_pg_iscritte_inpdap_aupgi_aurea_codice_pk] DEFAULT ((0)) NULL,
    [aupgi_stato_record]             INT           CONSTRAINT [DF2_st_aupgi_pg_iscritte_inpdap_aupgi_stato_record] DEFAULT ((0)) NULL,
    [AUPGI_FLAG_AUSCA]               VARCHAR (1)   CONSTRAINT [DF2_st_aupgi_pg_iscritte_inpdap_AUPGI_FLAG_AUSCA] DEFAULT ('N') NULL,
    [AUPGI_FLAG_AUPOC]               VARCHAR (1)   CONSTRAINT [DF2_st_aupgi_pg_iscritte_inpdap_AUPGI_FLAG_AUPOC] DEFAULT ('N') NULL,
    [AUPGI_AUTEN_CODICE_PK]          INT           CONSTRAINT [DF2_st_aupgi_pg_iscritte_inpdap_AUPGI_AUTEN_CODICE_PK] DEFAULT ((0)) NULL,
    [AUPGI_AUNGI_CODICE_PK]          INT           CONSTRAINT [DF2_st_aupgi_pg_iscritte_inpdap_AUPGI_AUNGI_CODICE_PK] DEFAULT ((0)) NULL,
    [aupgi_presenti_posizioni_DM]    VARCHAR (1)   NULL,
    [AUPGI_FLAG_AURSS_RL]            VARCHAR (1)   NULL,
    [AUPGI_CODICE_AUSCO]             INT           NULL,
    [aupgi_telefono]                 VARCHAR (20)  NULL,
    [aupgi_fax]                      VARCHAR (20)  NULL,
    [aupgi_mail_pec]                 VARCHAR (162) NULL,
    [aupgi_mail_no_pec]              VARCHAR (162) NULL,
    [aupgi_codice_ateco]             VARCHAR (20)  NULL,
    [aupgi_cf_rapr_legale]           VARCHAR (16)  NULL,
    [aupgi_cognome_rapr_legale]      VARCHAR (255) NULL,
    [aupgi_nome_rapr_legale]         VARCHAR (150) NULL,
    [aupgi_data_nasc_rapr_legale]    VARCHAR (20)  NULL,
    [aupgi_ente_dichiarante_INPDAP]  VARCHAR (1)   NULL,
    [aupgi_ente_appartenenza_INPDAP] VARCHAR (1)   NULL,
    [aupgi_sede_servizio_INPDAP]     VARCHAR (1)   NULL,
    [aupgi_ente_versante_INPDAP]     VARCHAR (1)   NULL,
    [aupgi_sede_competenza_INPDAP]   VARCHAR (4)   NULL,
    [AUPGI_AUSCA_CODICE_AUATE_2002]  INT           NULL,
    [AUPGI_AUSCA_CODICE_AUATE_2007]  INT           NULL,
    [AUPGI_AUPOC_AUSIN_CODICE_PK]    INT           NULL,
    [AUPGI_CODICE_TOPONIMO]          VARCHAR (3)   NULL
);

