CREATE TABLE [dbo].[Sync_DM_tanagaz] (
    [St_ausca_denominazione]              VARCHAR (MAX) NULL,
    [St_ausca_codice_fiscale]             VARCHAR (MAX) NULL,
    [St_ausca_aungi_codice_pk]            VARCHAR (MAX) NULL,
    [St_ausca_indirizzo]                  VARCHAR (MAX) NULL,
    [St_ausca_Codice_Toponimo]            VARCHAR (MAX) NULL,
    [St_ausca_Nome_Via]                   VARCHAR (MAX) NULL,
    [St_ausca_Toponimo]                   VARCHAR (MAX) NULL,
    [St_ausca_civico]                     VARCHAR (MAX) NULL,
    [St_ausca_localita]                   VARCHAR (MAX) NULL,
    [St_ausca_sede_legale_italia]         VARCHAR (MAX) NULL,
    [St_ausca_codice_comune]              VARCHAR (MAX) NULL,
    [St_ausca_descr_comune]               VARCHAR (MAX) NULL,
    [St_ausca_sigla_provincia]            VARCHAR (MAX) NULL,
    [St_ausca_regione]                    VARCHAR (MAX) NULL,
    [St_ausca_codice_stato_estero]        VARCHAR (MAX) NULL,
    [St_ausca_cap]                        VARCHAR (MAX) NULL,
    [St_ausca_CodiceFormaGiuridica]       VARCHAR (MAX) NULL,
    [St_ausca_FormaGiuridica]             VARCHAR (MAX) NULL,
    [St_ausca_Stato]                      VARCHAR (MAX) NULL,
    [St_ausca_telefono1]                  VARCHAR (MAX) NULL,
    [St_ausca_telefono2]                  VARCHAR (MAX) NULL,
    [St_ausca_telefono3]                  VARCHAR (MAX) NULL,
    [St_ausca_fax]                        VARCHAR (MAX) NULL,
    [St_ausca_email]                      VARCHAR (MAX) NULL,
    [St_ausca_PEC]                        VARCHAR (MAX) NULL,
    [St_ausca_auate_codice_pk]            VARCHAR (MAX) NULL,
    [St_ausca_soggetto_certificato]       VARCHAR (MAX) NULL,
    [St_ausca_data_variazione_stato]      VARCHAR (MAX) NULL,
    [St_ausca_auten_codice_pk]            VARCHAR (MAX) NULL,
    [St_ausca_codice_entita_riferimento]  VARCHAR (MAX) NULL,
    [St_ausca_note]                       VARCHAR (MAX) NULL,
    [St_ausca_ATECO_2002]                 VARCHAR (MAX) NULL,
    [St_ausca_ATECO_2007]                 VARCHAR (MAX) NULL,
    [St_ausca_DesATECO_2002]              VARCHAR (MAX) NULL,
    [St_ausca_DesATECO_2007]              VARCHAR (MAX) NULL,
    [St_ausca_Data_Inizio_Attivita]       VARCHAR (MAX) NULL,
    [St_ausca_Data_Fine_Attivita]         VARCHAR (MAX) NULL,
    [St_ausca_Filename]                   VARCHAR (MAX) NULL,
    [St_ausca_data_domandafile]           VARCHAR (MAX) NULL,
    [St_ausca_TipologiaFile]              VARCHAR (MAX) NULL,
    [St_ausca_NomeFileVisuraOriginale]    VARCHAR (MAX) NULL,
    [St_ausca_NomeOriginale_Prov1]        VARCHAR (MAX) NULL,
    [St_ausca_NomeOriginale_Anno]         VARCHAR (MAX) NULL,
    [St_ausca_NomeOriginale_Progressivo1] VARCHAR (MAX) NULL,
    [St_ausca_NomeOriginale_Visura]       VARCHAR (MAX) NULL,
    [St_ausca_NomeOriginale_Prov2]        VARCHAR (MAX) NULL,
    [St_ausca_NomeOriginale_NumREA]       VARCHAR (MAX) NULL,
    [St_ausca_NumeroREA_Visura]           VARCHAR (MAX) NULL,
    [St_ausca_FLAG]                       TINYINT       NULL,
    [St_ausca_Aungi_pk]                   INT           NULL,
    [St_ausca_Auate_pk]                   INT           NULL,
    [St_ausca_Auten_pk]                   INT           NULL,
    [St_ausca_CodEntita_pk]               INT           NULL,
    [St_ausca_codice_Ateco91]             VARCHAR (MAX) NULL,
    [St_ausca_codice_forma_giuridica]     VARCHAR (MAX) NULL,
    [St_ausca_MatricolaGestioneAziende]   VARCHAR (MAX) NULL,
    [St_ausca_sede_provinciale]           VARCHAR (MAX) NULL,
    [St_ausca_matricola_azienda]          VARCHAR (MAX) NULL,
    [St_ausca_controcod_matr_az]          VARCHAR (MAX) NULL,
    [St_ausca_stato_posizione]            VARCHAR (MAX) NULL,
    [St_ausca_data_modifica]              VARCHAR (MAX) NULL,
    [St_ausca_descr_utente]               VARCHAR (MAX) NULL,
    [St_ausca_Az_Posta]                   VARCHAR (1)   NULL,
    [St_ausca_PEC_IVA]                    VARCHAR (MAX) NULL
);

