CREATE TABLE [dbo].[TAZSO00_STAGING] (
    [SOCODPRO] DECIMAL (2) NULL,
    [SOMATAZI] DECIMAL (6) NULL,
    [SOCTRCOD] DECIMAL (2) NULL,
    [SOTIPCEO] CHAR (1)    NULL,
    [SODATCEO] DECIMAL (8) NULL,
    [SOTIPCEN] CHAR (1)    NULL,
    [SODATCEN] DECIMAL (8) NULL,
    [SOTIPINT] CHAR (1)    NULL,
    [SODATDAL] DECIMAL (8) NULL,
    [SODATAL]  DECIMAL (8) NULL,
    [SOUSERID] CHAR (8)    NULL,
    [SOTDISP]  CHAR (6)    NULL,
    [SODATVAR] DECIMAL (8) NULL,
    [SOORAVAR] DECIMAL (6) NULL
);

