CREATE TABLE [dbo].[TB_ANAUC_ELABAUC_CL] (
    [ANAUC_DATA_ELAB_PK]          DATETIME      NOT NULL,
    [ANAUC_TIPO_ELAB_PK]          VARCHAR (1)   NOT NULL,
    [ANAUC_TABELLA_ELAB_PK]       VARCHAR (50)  NOT NULL,
    [ANAUC_NUM_RECORD_LETTI]      BIGINT        CONSTRAINT [DF__TB_ANAUC___ANAUC__44B85633] DEFAULT ((0)) NOT NULL,
    [ANAUC_NUM_RECORD_INSERITI]   BIGINT        CONSTRAINT [DF__TB_ANAUC___ANAUC__45AC7A6C] DEFAULT ((0)) NOT NULL,
    [ANAUC_NUM_RECORD_AGGIORNATI] BIGINT        CONSTRAINT [DF__TB_ANAUC___ANAUC__46A09EA5] DEFAULT ((0)) NOT NULL,
    [ANAUC_NUM_RECORD_ELIMINATI]  BIGINT        CONSTRAINT [DF__TB_ANAUC___ANAUC__4794C2DE] DEFAULT ((0)) NOT NULL,
    [ANAUC_FLAG_ESITO]            VARCHAR (1)   NOT NULL,
    [ANAUC_DESC_ESITO]            VARCHAR (100) NULL,
    [ANAUC_DATA_SISTEMA]          DATE          CONSTRAINT [DF_TB_ANAUC_ELABAUC_CL_ANAUC_DATA_SISTEMA] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_ANAUC_ELABAUC] PRIMARY KEY CLUSTERED ([ANAUC_DATA_ELAB_PK] ASC, [ANAUC_TIPO_ELAB_PK] ASC, [ANAUC_TABELLA_ELAB_PK] ASC)
);

