CREATE TABLE [dbo].[TB_ANTOG_TOPERPG_CT] (
    [ANTOG_COD_TOPERPG_PK]        VARCHAR (3)  NOT NULL,
    [ANTOG_DESCR_TOPERPG]         VARCHAR (50) NOT NULL,
    [ANTOG_DATA_INIZ]             DATE         NOT NULL,
    [ANTOG_DATA_FINE]             DATE         NOT NULL,
    [ANTOG_FLAG_ESPOSIZ]          VARCHAR (1)  NOT NULL,
    [ANTOG_NUM_ORDINAM]           INT          NOT NULL,
    [ANTOG_COD_UTENTE]            VARCHAR (16) NOT NULL,
    [ANTOG_DATA_AGGIORN]          DATE         NOT NULL,
    [ANTOG_COD_APPL]              VARCHAR (2)  NOT NULL,
    [ANTOG_AUC_CODICE_PK]         BIGINT       IDENTITY (1, 1) NOT NULL,
    [ANTOG_AUC_DATA_INSERIMENTO]  DATETIME     CONSTRAINT [DF_TB_ANTOG_TOPERPG_CT_ANTOG_AUC_DATA_INSERIMENTO] DEFAULT (getdate()) NULL,
    [ANTOG_AUC_STATO_LAVORAZIONE] INT          CONSTRAINT [DF_TB_ANTOG_TOPERPG_CT_ANTOG_AUC_STATO_LAVORAZIONE] DEFAULT ((0)) NULL,
    [ANTOG_AUC_PRESENTE]          INT          CONSTRAINT [DF_TB_ANTOG_TOPERPG_CT_ANTOG_AUC_PRESENTE] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_ANTOG_TOPERPG] PRIMARY KEY CLUSTERED ([ANTOG_COD_TOPERPG_PK] ASC),
    CONSTRAINT [CK1_ANTOG_FLAG_ESPOSIZ] CHECK ([ANTOG_FLAG_ESPOSIZ]='N' OR [ANTOG_FLAG_ESPOSIZ]='S'),
    CONSTRAINT [CK2_ANTOG_DATE_INIZ_FINE] CHECK ([ANTOG_DATA_FINE]>=[ANTOG_DATA_INIZ])
);

