CREATE TABLE [dbo].[TB_ANTLP_TIPLEGAMEPG_CT] (
    [ANTLP_COD_TIPLEGAMEPG_PK]    VARCHAR (2)   NOT NULL,
    [ANTLP_DESCR_TIPLEGAMEPG]     VARCHAR (60)  NOT NULL,
    [ANTLP_DATA_INIZ]             DATE          NOT NULL,
    [ANTLP_DATA_FINE]             DATE          CONSTRAINT [DF_TB_ANTLP_TIPLEGAMEPG_CT_ANTLP_DATA_FINE] DEFAULT (CONVERT([date],'9999-12-31')) NOT NULL,
    [ANTLP_FLAG_ESPOSIZ]          VARCHAR (1)   CONSTRAINT [DF_TB_ANTLP_TIPLEGAMEPG_CT_ANTLP_FLAG_ESPOSIZ] DEFAULT ('S') NOT NULL,
    [ANTLP_NOTE_TIPLEGAMEPG]      VARCHAR (255) NULL,
    [ANTLP_COD_UTENTE]            VARCHAR (16)  NOT NULL,
    [ANTLP_DATA_AGGIORN]          DATE          NOT NULL,
    [ANTLP_COD_APPL]              VARCHAR (2)   NOT NULL,
    [ANTLP_AUC_CODICE_PK]         BIGINT        IDENTITY (1, 1) NOT NULL,
    [ANTLP_AUC_DATA_INSERIMENTO]  DATETIME      CONSTRAINT [DF_TB_ANTLP_TIPLEGAMEPG_CT_ANTLP_AUC_DATA_INSERIMENTO] DEFAULT (getdate()) NULL,
    [ANTLP_AUC_STATO_LAVORAZIONE] INT           CONSTRAINT [DF_TB_ANTLP_TIPLEGAMEPG_CT_ANTLP_AUC_STATO_LAVORAZIONE] DEFAULT ((0)) NULL,
    [ANTLP_AUC_PRESENTE]          INT           CONSTRAINT [DF_TB_ANTLP_TIPLEGAMEPG_CT_ANTLP_AUC_PRESENTE] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_ANTLP_TIPLEGAMEPG] PRIMARY KEY CLUSTERED ([ANTLP_COD_TIPLEGAMEPG_PK] ASC)
);

