CREATE TABLE [dbo].[TB_ANFGG_FORMAGIURPG_CL] (
    [ANFGG_BDSO_ID_VA_PK]         BIGINT       NOT NULL,
    [ANFGG_DATA_INIZ_PK]          DATE         NOT NULL,
    [ANFGG_DATA_FINE]             DATE         CONSTRAINT [DF_TB_ANFGG_FORMAGIURPG_CL_ANFGG_DATA_FINE] DEFAULT (CONVERT([date],'9999-12-31')) NOT NULL,
    [ANFGG_ANFGI_COD_FORMAGIUR]   VARCHAR (3)  NOT NULL,
    [ANFGG_COD_UTENTE]            VARCHAR (16) NOT NULL,
    [ANFGG_DATA_AGGIORN]          DATE         CONSTRAINT [DF_TB_ANFGG_FORMAGIURPG_CL_ANFGG_DATA_AGGIORN] DEFAULT (getdate()) NOT NULL,
    [ANFGG_COD_APPL]              VARCHAR (2)  NOT NULL,
    [ANFGG_DATA_SISTEMA]          DATETIME     NULL,
    [ANFGG_AUC_CODICE_PK]         BIGINT       IDENTITY (1, 1) NOT NULL,
    [ANFGG_AUC_DATA_INSERIMENTO]  DATETIME     CONSTRAINT [DF_TB_ANFGG_FORMAGIURPG_CL_ANFGG_DATA_INSERIMENTO] DEFAULT (getdate()) NULL,
    [ANFGG_AUC_STATO_LAVORAZIONE] INT          CONSTRAINT [DF_TB_ANFGG_FORMAGIURPG_CL_ANFGG_AUC_STATO_LAVORAZIONE] DEFAULT ((0)) NULL,
    [ANFGG_AUC_CF_PK]             VARCHAR (16) NULL,
    [ANFGG_AUC_AUSCA_PK]          INT          CONSTRAINT [DF_TB_ANFGG_FORMAGIURPG_CL_ANFGG_AUC_AUSCA_PK] DEFAULT ((0)) NULL,
    [ANFGG_AUC_PRESENTE]          INT          CONSTRAINT [DF_TB_ANFGG_FORMAGIURPG_CL_ANFGG_AUC_PRESENTE] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_ANFGG_FORMAGIURPG] PRIMARY KEY CLUSTERED ([ANFGG_BDSO_ID_VA_PK] ASC, [ANFGG_DATA_INIZ_PK] ASC),
    CONSTRAINT [CK1_ANFGG_DATE_INIZ_FINE] CHECK ([ANFGG_DATA_FINE]>=[ANFGG_DATA_INIZ_PK]),
    CONSTRAINT [FK1_ANFGG_BDSO] FOREIGN KEY ([ANFGG_BDSO_ID_VA_PK]) REFERENCES [dbo].[BDSO_SOCIETA_CL] ([BDSO_ID_VA])
);

