CREATE TABLE [dbo].[tb_aupoe_PosizioniErrate_Auuop] (
    [auuop_aupoc_codice_pk]        INT           NULL,
    [aupoc_posizione]              VARCHAR (50)  NULL,
    [auuop_aupoc_accentrante]      VARCHAR (10)  NULL,
    [auuop_aupoc_codice_pk_ante]   INT           NULL,
    [auuop_data_richiesta]         DATETIME2 (3) NULL,
    [auuop_identificativo]         VARCHAR (10)  NULL,
    [auuop_num_provvedimento]      INT           NULL,
    [auuop_data_provvedimento]     DATETIME2 (3) NULL,
    [auuop_tipo_richiesta]         INT           NULL,
    [auuop_segnatatura_protocollo] VARCHAR (40)  NULL,
    [auuop_cod_fiscale_ric]        VARCHAR (16)  NULL,
    [auuop_stato_richiesta]        VARCHAR (1)   NULL,
    [auuop_classe_utente_ric]      VARCHAR (5)   NULL,
    [auuop_validatore_INPS]        VARCHAR (10)  NULL,
    [auuop_aupoc_accentrata]       VARCHAR (10)  NULL,
    [auuop_aupoc_codice_pk_ata]    INT           NULL,
    [auuop_data_inizio_accentr]    DATETIME2 (3) NULL,
    [auuop_data_fine_accentr]      DATETIME2 (3) NULL,
    [auuop_denominazione]          VARCHAR (405) NULL,
    [auuop_numero_dipendenti]      INT           NULL,
    [auuop_flag_operativo]         INT           NULL,
    [auuop_id_taccontr]            INT           NULL,
    [auuop_data_modifica]          DATETIME2 (3) NULL,
    [auuop_descr_utente]           VARCHAR (50)  NULL,
    [auuop_unita_operativa]        CHAR (1)      NULL,
    [auuop_unita_produttiva]       CHAR (1)      NULL
);

