CREATE TABLE [dbo].[tb_aucon_concorsuale] (
    [aucon_codice_pk]                     BIGINT        IDENTITY (1, 1) NOT NULL,
    [aucon_ausca_codice_pk]               INT           NULL,
    [aucon_info]                          VARCHAR (1)   NULL,
    [aucon_data_iscrizione]               DATETIME      NULL,
    [aucon_tribunale]                     VARCHAR (100) NULL,
    [aucon_num_registrazione]             VARCHAR (20)  NULL,
    [aucon_data_registrazione]            DATETIME      NULL,
    [aucon_localita_uff_registro]         VARCHAR (50)  NULL,
    [aucon_prov_uff_registro]             VARCHAR (2)   NULL,
    [aucon_data_modifica]                 DATETIME      NULL,
    [aucon_descr_utente]                  VARCHAR (50)  NULL,
    [aucon_codice_pk_db2]                 BIGINT        NULL,
    [aucon_rec_del]                       VARCHAR (1)   NULL,
    [aucon_data_del]                      DATETIME      NULL,
    [aucon_cod_tipo]                      VARCHAR (2)   NULL,
    [aucon_data_atto]                     DATETIME      NULL,
    [aucon_notaio]                        VARCHAR (80)  NULL,
    [aucon_tipo]                          VARCHAR (50)  NULL,
    [aucon_cciaa_fuori_provincia]         VARCHAR (2)   NULL,
    [aucon_codice_atto]                   VARCHAR (5)   NULL,
    [aucon_codice_liquidazione]           VARCHAR (5)   NULL,
    [aucon_data_iscrizione_procedura]     DATE          NULL,
    [aucon_descr_liquidazione]            VARCHAR (50)  NULL,
    [aucon_descrizione_atto]              VARCHAR (50)  NULL,
    [aucon_Accordi_Debiti]                VARCHAR (MAX) NULL,
    [aucon_Annotazioni_Procedure]         VARCHAR (MAX) NULL,
    [aucon_Appelli_Reclami]               VARCHAR (MAX) NULL,
    [aucon_Cessazione_Esercizio_Provv]    VARCHAR (MAX) NULL,
    [aucon_Continuazione_Esercizio_Provv] VARCHAR (MAX) NULL,
    [aucon_data_chiusura]                 DATE          NULL,
    [aucon_data_esecuzione]               DATE          NULL,
    [aucon_data_omologazione]             DATE          NULL,
    [aucon_data_provvedimento]            DATE          NULL,
    [aucon_data_revoca]                   DATE          NULL,
    [aucon_data_termine]                  DATE          NULL,
    [aucon_Esecuzione_Concordato]         VARCHAR (MAX) NULL,
    [aucon_Esercizio_Provvisorio]         VARCHAR (MAX) NULL,
    [aucon_Proposta_Concordato]           VARCHAR (MAX) NULL,
    [aucon_Rapporto_Curatore]             VARCHAR (MAX) NULL,
    [aucon_altre_indicazioni]             VARCHAR (40)  NULL,
    CONSTRAINT [PK_tb_aucon] PRIMARY KEY CLUSTERED ([aucon_codice_pk] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_aucon_ausca] FOREIGN KEY ([aucon_ausca_codice_pk]) REFERENCES [dbo].[tb_ausca_sog_contr_az] ([ausca_codice_pk]),
    CONSTRAINT [UQ_aucon_aucon] UNIQUE NONCLUSTERED ([aucon_codice_pk] ASC) WITH (FILLFACTOR = 90)
);

