CREATE TABLE [dbo].[tb_auuop_unita_operativa] (
    [auuop_codice_pk]              BIGINT        IDENTITY (1, 1) NOT NULL,
    [auuop_aupoc_codice_pk]        INT           NULL,
    [auuop_aupoc_accentrante]      VARCHAR (10)  NULL,
    [auuop_aupoc_codice_pk_ante]   INT           NULL,
    [auuop_data_richiesta]         DATETIME      NULL,
    [auuop_identificativo]         VARCHAR (10)  NULL,
    [auuop_num_provvedimento]      INT           NULL,
    [auuop_data_provvedimento]     DATETIME      NULL,
    [auuop_tipo_richiesta]         INT           NULL,
    [auuop_segnatatura_protocollo] VARCHAR (40)  NULL,
    [auuop_cod_fiscale_ric]        VARCHAR (16)  NULL,
    [auuop_stato_richiesta]        VARCHAR (1)   NULL,
    [auuop_classe_utente_ric]      VARCHAR (5)   NULL,
    [auuop_validatore_INPS]        VARCHAR (10)  NULL,
    [auuop_aupoc_accentrata]       VARCHAR (10)  NULL,
    [auuop_aupoc_codice_pk_ata]    INT           NULL,
    [auuop_data_inizio_accentr]    DATETIME      NULL,
    [auuop_data_fine_accentr]      DATETIME      NULL,
    [auuop_denominazione]          VARCHAR (405) NULL,
    [auuop_numero_dipendenti]      INT           NULL,
    [auuop_flag_operativo]         INT           NULL,
    [auuop_id_taccontr]            INT           NULL,
    [auuop_data_modifica]          DATETIME      NULL,
    [auuop_descr_utente]           VARCHAR (50)  NULL,
    [auuop_codice_pk_db2]          BIGINT        NULL,
    [auuop_rec_del]                VARCHAR (1)   NULL,
    [auuop_data_del]               DATETIME      NULL,
    [auuop_unita_operativa]        CHAR (1)      CONSTRAINT [DF_tb_auuop_unita_operativa_auuop_unita_operativa] DEFAULT ('N') NULL,
    [auuop_unita_produttiva]       CHAR (1)      CONSTRAINT [DF_tb_auuop_unita_operativa_auuop_unita_produttiva] DEFAULT ('N') NULL,
    CONSTRAINT [PK_tb_auuop] PRIMARY KEY CLUSTERED ([auuop_codice_pk] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_auuop_aupoc] FOREIGN KEY ([auuop_aupoc_codice_pk]) REFERENCES [dbo].[tb_aupoc_pos_contr] ([aupoc_codice_pk]),
    CONSTRAINT [UQ_auuop_auuop] UNIQUE NONCLUSTERED ([auuop_codice_pk] ASC) WITH (FILLFACTOR = 90)
);

