CREATE TABLE [dbo].[TB_ANLPG_LEGAMIPG_CL] (
    [ANLPG_BDSO_ID_VA_RLD_PK]        BIGINT       NOT NULL,
    [ANLPG_BDSO_ID_VA_RLA_PK]        BIGINT       NOT NULL,
    [ANLPG_ANTLP_COD_TIPLEGAMEPG_PK] VARCHAR (2)  NOT NULL,
    [ANLPG_DATA_INIZ_PK]             DATE         NOT NULL,
    [ANLPG_DATA_FINE]                DATE         CONSTRAINT [DF_TB_ANLPG_LEGAMIPG_CL_ANLPG_DATA_FINE] DEFAULT (CONVERT([date],'9999-12-31')) NOT NULL,
    [ANLPG_COD_UTENTE]               VARCHAR (16) NOT NULL,
    [ANLPG_DATA_AGGIORN]             DATE         NOT NULL,
    [ANLPG_COD_APPL]                 VARCHAR (2)  NOT NULL,
    [ANLPG_DATA_SISTEMA]             DATETIME     NOT NULL,
    [ANLPG_AUC_CODICE_PK]            BIGINT       IDENTITY (1, 1) NOT NULL,
    [ANLPG_AUC_DATA_INSERIMENTO]     DATETIME     CONSTRAINT [DF_TB_ANLPG_LEGAMIPG_CL_ANLPG_AUC_DATA_INSERIMENTO] DEFAULT (getdate()) NULL,
    [ANLPG_AUC_STATO_LAVORAZIONE]    INT          CONSTRAINT [DF_TB_ANLPG_LEGAMIPG_CL_ANLPG_AUC_STATO_LAVORAZIONE] DEFAULT ((0)) NULL,
    [ANLPG_AUC_CF_RLD_PK]            VARCHAR (16) NULL,
    [ANLPG_AUC_CF_RLA_PK]            VARCHAR (16) NULL,
    [ANLPG_AUC_AUSCA_RLD_PK]         INT          NULL,
    [ANLPG_AUC_AUSCA_RLA_PK]         INT          NULL,
    [ANLPG_AUC_PRESENTE]             INT          CONSTRAINT [DF_TB_ANLPG_LEGAMIPG_CL_ANLPG_AUC_PRESENTE] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_ANLPG_LEGAMIPG] PRIMARY KEY CLUSTERED ([ANLPG_BDSO_ID_VA_RLD_PK] ASC, [ANLPG_BDSO_ID_VA_RLA_PK] ASC, [ANLPG_ANTLP_COD_TIPLEGAMEPG_PK] ASC, [ANLPG_DATA_INIZ_PK] ASC),
    CONSTRAINT [FK1_ANLPG_BDSO] FOREIGN KEY ([ANLPG_BDSO_ID_VA_RLD_PK]) REFERENCES [dbo].[BDSO_SOCIETA_CL] ([BDSO_ID_VA]),
    CONSTRAINT [FK2_ANLPG_BDSO] FOREIGN KEY ([ANLPG_BDSO_ID_VA_RLA_PK]) REFERENCES [dbo].[BDSO_SOCIETA_CL] ([BDSO_ID_VA]),
    CONSTRAINT [FK3_ANLPG_ANTLP] FOREIGN KEY ([ANLPG_ANTLP_COD_TIPLEGAMEPG_PK]) REFERENCES [dbo].[TB_ANTLP_TIPLEGAMEPG_CT] ([ANTLP_COD_TIPLEGAMEPG_PK])
);

