CREATE TABLE [dbo].[TB_AUAIN_AZIENDE_GESTIONE_SEPARATA] (
    [AUAIN_CODICE_PK]                              INT           IDENTITY (1, 1) NOT NULL,
    [auain_codice_gestione]                        VARCHAR (50)  NULL,
    [auain_denominazione]                          VARCHAR (405) NULL,
    [auain_flag_dt_individuale]                    VARCHAR (1)   NULL,
    [auain_codice_fiscale]                         VARCHAR (16)  NULL,
    [auain_partita_iva]                            VARCHAR (11)  NULL,
    [Auian_ateco]                                  VARCHAR (7)   NULL,
    [Auain_tipo_soggetto_committente]              VARCHAR (1)   CONSTRAINT [DF_tb_auain_aziende_Gestione_Separata_Auain_tipo_soggetto_committente] DEFAULT ('N') NULL,
    [Auain_data_inizio_committente]                DATETIME      NULL,
    [Auain_data_fine_committente]                  DATETIME      NULL,
    [Auain_stato_committente]                      VARCHAR (20)  NULL,
    [Auian_ateco_committente]                      VARCHAR (7)   NULL,
    [Auain_descr_ateco_comm]                       VARCHAR (50)  NULL,
    [Auain_tipo_soggetto_professionista]           VARCHAR (1)   CONSTRAINT [DF_tb_auain_aziende_Gestione_Separata_Auain_tipo_soggetto_professionista] DEFAULT ('N') NULL,
    [Auain_data_inizio_professionista]             DATETIME      NULL,
    [Auain_data_fine_professionista]               DATETIME      NULL,
    [Auain_stato_professionista]                   VARCHAR (20)  NULL,
    [Auian_ateco_professionista]                   VARCHAR (7)   NULL,
    [Auain_descr_ateco_prof]                       VARCHAR (50)  NULL,
    [auain_nome_tit]                               VARCHAR (150) NULL,
    [auain_cognome_tit]                            VARCHAR (255) NULL,
    [auain_sesso_tit]                              VARCHAR (1)   NULL,
    [auain_data_nascita_tit]                       DATETIME      NULL,
    [auain_comune_nascita_tit]                     VARCHAR (45)  NULL,
    [auain_prov_nascita_tit]                       VARCHAR (2)   NULL,
    [auain_nazione_nascita_tit]                    VARCHAR (100) NULL,
    [auain_toponimo_tit]                           VARCHAR (50)  NULL,
    [auain_indirizzo_tit]                          VARCHAR (255) NULL,
    [auain_civico_tit]                             VARCHAR (50)  NULL,
    [auain_cap_tit]                                VARCHAR (5)   NULL,
    [auain_comune_tit]                             VARCHAR (45)  NULL,
    [auain_sigla_provincia_tit]                    VARCHAR (2)   NULL,
    [auain_frazione_tit]                           VARCHAR (100) NULL,
    [auain_localita_tit]                           VARCHAR (50)  NULL,
    [auain_telefono_tit]                           VARCHAR (20)  NULL,
    [auain_fax_tit]                                VARCHAR (20)  NULL,
    [auain_email_tit]                              VARCHAR (160) NULL,
    [auain_pec_tit]                                VARCHAR (160) NULL,
    [auain_toponimo]                               VARCHAR (50)  NULL,
    [auain_indirizzo]                              VARCHAR (255) NULL,
    [auain_civico]                                 VARCHAR (50)  NULL,
    [auain_cap]                                    VARCHAR (5)   NULL,
    [auain_comune]                                 VARCHAR (45)  NULL,
    [auain_sigla_provincia]                        VARCHAR (2)   NULL,
    [auain_frazione]                               VARCHAR (100) NULL,
    [auain_localita]                               VARCHAR (50)  NULL,
    [auain_telefono]                               VARCHAR (20)  NULL,
    [auain_fax]                                    VARCHAR (20)  NULL,
    [auain_email]                                  VARCHAR (160) NULL,
    [auain_pec]                                    VARCHAR (160) NULL,
    [auain_nat_giur]                               VARCHAR (10)  NULL,
    [auain_descr_nat_giur]                         VARCHAR (100) NULL,
    [auain_sede_inps]                              VARCHAR (10)  NULL,
    [auain_cf_RL]                                  VARCHAR (16)  NULL,
    [auain_nome_RL]                                VARCHAR (150) NULL,
    [auain_cognome_RL]                             VARCHAR (255) NULL,
    [auain_data_inizio_RL]                         DATETIME      NULL,
    [auain_sesso_RL]                               VARCHAR (1)   NULL,
    [auain_data_nasc_RL]                           DATETIME      NULL,
    [auain_com_nasc_RL]                            VARCHAR (45)  NULL,
    [auain_prov_nasc_RL]                           VARCHAR (2)   NULL,
    [auain_toponimo_RL]                            VARCHAR (50)  NULL,
    [auain_indirizzo_RL]                           VARCHAR (255) NULL,
    [auain_civico_RL]                              VARCHAR (50)  NULL,
    [auain_cap_RL]                                 VARCHAR (5)   NULL,
    [auain_comune_RL]                              VARCHAR (45)  NULL,
    [auain_sigla_prov_RL]                          VARCHAR (2)   NULL,
    [auain_frazione_RL]                            VARCHAR (100) NULL,
    [auain_localita_RL]                            VARCHAR (50)  NULL,
    [auain_telefono_RL]                            VARCHAR (20)  NULL,
    [auain_fax_RL]                                 VARCHAR (20)  NULL,
    [auain_email_RL]                               VARCHAR (160) NULL,
    [auain_pec_RL]                                 VARCHAR (160) NULL,
    [Auain_data_certificazione]                    DATETIME      NULL,
    [Auain_validato]                               INT           NULL,
    [Auain_flag_validato]                          CHAR (1)      NULL,
    [AUAIN_DATA_MODIFICA]                          DATETIME      CONSTRAINT [DF_tb_auain_aziende_Gestione_Separata_AUAIN_DATA_MODIFICA] DEFAULT (getdate()) NULL,
    [AUAIN_STATO_LAVORAZIONE]                      INT           CONSTRAINT [DF_tb_auain_aziende_Gestione_Separata_AUAIN_STATO_LAVORAZIONE] DEFAULT ((0)) NULL,
    [AUAIN_CODICE_LOTTO]                           INT           CONSTRAINT [DF_tb_auain_aziende_Gestione_Separata_AUAIN_CODICE_LOTTO] DEFAULT ((0)) NULL,
    [AUAIN_FLAG_AUSCA]                             VARCHAR (1)   CONSTRAINT [DF_tb_auain_aziende_Gestione_Separata_AUAIN_FLAG_AUSCA] DEFAULT ('N') NULL,
    [AUAIN_FLAG_AUSCO]                             VARCHAR (1)   CONSTRAINT [DF_tb_auain_aziende_Gestione_Separata_AUAIN_FLAG_AUSCO] DEFAULT ('N') NULL,
    [AUAIN_FLAG_AUSCO_RL]                          VARCHAR (1)   CONSTRAINT [DF_tb_auain_aziende_Gestione_Separata_AUAIN_FLAG_AUSCO_RL] DEFAULT ('N') NULL,
    [AUAIN_FLAG_AURSS]                             VARCHAR (1)   CONSTRAINT [DF_tb_auain_aziende_Gestione_Separata_AUAIN_FLAG_AURSS] DEFAULT ('N') NULL,
    [AUAIN_FLAG_AURSS_RL]                          VARCHAR (1)   CONSTRAINT [DF_tb_auain_aziende_Gestione_Separata_AUAIN_FLAG_AURSS_RL] DEFAULT ('N') NULL,
    [AUAIN_FLAG_AUPOC_COMM]                        VARCHAR (1)   CONSTRAINT [DF_tb_auain_aziende_Gestione_Separata_AUAIN_FLAG_AUPOC_COMM] DEFAULT ('N') NULL,
    [AUAIN_FLAG_AUPOC_PROF]                        VARCHAR (1)   CONSTRAINT [DF_tb_auain_aziende_Gestione_Separata_AUAIN_FLAG_AUPOC_PROF] DEFAULT ('N') NULL,
    [AUAIN_CODICE_AUSCA]                           INT           CONSTRAINT [DF_tb_auain_aziende_Gestione_Separata_AUAIN_CODICE_AUSCA] DEFAULT ((0)) NULL,
    [AUAIN_CODICE_AUSCO]                           INT           CONSTRAINT [DF_tb_auain_aziende_Gestione_Separata_AUAIN_CODICE_AUSCO] DEFAULT ((0)) NULL,
    [AUAIN_CODICE_AUSCO_RL]                        INT           CONSTRAINT [DF_tb_auain_aziende_Gestione_Separata_AUAIN_CODICE_AUSCO_RL] DEFAULT ((0)) NULL,
    [AUAIN_AUPOC_COMM]                             INT           CONSTRAINT [DF_tb_auain_aziende_Gestione_Separata_AUAIN_AUPOC_COMM] DEFAULT ((0)) NULL,
    [AUAIN_AUPOC_PROF]                             INT           CONSTRAINT [DF_tb_auain_aziende_Gestione_Separata_AUAIN_AUPOC_PROF] DEFAULT ((0)) NULL,
    [AUAIN_PRESENTI_POSIZIONI_DM]                  VARCHAR (1)   CONSTRAINT [DF_tb_auain_aziende_Gestione_Separata_AUAIN_PRESENTI_POSIZIONI_DM] DEFAULT ('N') NULL,
    [AUAIN_SOGGETTO_AGGIORNABILE]                  VARCHAR (1)   CONSTRAINT [DF_tb_auain_aziende_Gestione_Separata_AUAIN_SOGGETTO_AGGIORNABILE] DEFAULT ('N') NULL,
    [AUAIN_DATA_INIZIO_ATTIVITA]                   DATETIME      NULL,
    [AUAIN_DATA_FINE_ATTIVITA]                     DATETIME      NULL,
    [auain_data_fine_rl]                           DATETIME      NULL,
    [auain_fonte_acq_rl]                           INT           NULL,
    [AUAIN_CODICE_AUSSC]                           BIGINT        NULL,
    [AUAIN_CODICE_AREA_INSERITO]                   INT           NULL,
    [AUAIN_CODICE_AREA_CERTIFICATORE]              INT           NULL,
    [AUAIN_STATO_CERTIFICAZIONE]                   VARCHAR (1)   NULL,
    [AUAIN_AURIN_CodPK_TIT]                        INT           NULL,
    [AUAIN_AURIN_CodPK_RL]                         INT           NULL,
    [AUAIN_IND_QUALITA_INDIR]                      INT           NULL,
    [AUAIN_IND_QUALITA_INDIR_RL]                   INT           NULL,
    [AUAIN_POSIZIONE_COMMITTENTE]                  VARCHAR (50)  NULL,
    [AUAIN_POSIZIONE_PROFESSIONISTA]               VARCHAR (50)  NULL,
    [AUAIN_AUSIN_CODICE_PK]                        INT           NULL,
    [AUAIN_IND_QUALITA_INDIR_TIT]                  INT           NULL,
    [Auain_tipo_soggetto_professionista_Originale] VARCHAR (1)   NULL,
    [Auain_tipo_soggetto_committente_Originale]    VARCHAR (1)   NULL,
    [auain_sede_inps_Originale]                    VARCHAR (10)  NULL,
    [auain_aungi_codice_pk]                        INT           NULL
);

