CREATE TABLE [dbo].[TB_ANCCO_CAPCOM_CL] (
    [ANCCO_BDCP_ID_VA_PK] BIGINT       NOT NULL,
    [ANCCO_BDLC_ID_VA_PK] BIGINT       NOT NULL,
    [ANCCO_DATA_INIZ]     DATE         NOT NULL,
    [ANCCO_DATA_FINE]     DATE         NOT NULL,
    [ANCCO_COD_UTENTE]    VARCHAR (16) NOT NULL,
    [ANCCO_DATA_AGGIORN]  DATE         DEFAULT (getdate()) NOT NULL,
    [ANCCO_COD_APPL]      VARCHAR (2)  NOT NULL,
    [ANCCO_SEQ_CAPCOM_PK] BIGINT       NOT NULL,
    [ANCCO_DATA_SISTEMA]  DATE         NULL,
    CONSTRAINT [PK_TB_ANCCO_CAPCOM_CL] PRIMARY KEY CLUSTERED ([ANCCO_SEQ_CAPCOM_PK] ASC),
    CONSTRAINT [CK1_ANCCO_DATE_INIZ_FINE] CHECK ([ANCCO_DATA_FINE]>=[ANCCO_DATA_INIZ]),
    CONSTRAINT [FK1_ANCCO_BDCP] FOREIGN KEY ([ANCCO_BDCP_ID_VA_PK]) REFERENCES [dbo].[BDCP_CAP_CL] ([BDCP_ID_VA]),
    CONSTRAINT [FK2_ANCCO_BDLC] FOREIGN KEY ([ANCCO_BDLC_ID_VA_PK]) REFERENCES [dbo].[BDLC_LOCALITA_CL] ([BDLC_ID_VA])
);

