CREATE TABLE [dbo].[TB_AUAAC_ANAGRAFICA_AC] (
    [AUAAC_CODICE_PK]               INT           IDENTITY (1, 1) NOT NULL,
    [auaac_cod_azienda]             VARCHAR (20)  NULL,
    [auaac_tipo_sog]                VARCHAR (2)   NULL,
    [auaac_cf_sog]                  VARCHAR (16)  NULL,
    [auaac_cognome_sog]             VARCHAR (200) NULL,
    [auaac_nome_sog]                VARCHAR (200) NULL,
    [auaac_sesso_sog]               VARCHAR (1)   NULL,
    [auaac_dt_nascita]              DATETIME      NULL,
    [auaac_comune_nascita_sog]      VARCHAR (100) NULL,
    [auaac_cod_com_nascita_sog]     VARCHAR (4)   NULL,
    [auaac_prov_nascita_sog]        VARCHAR (2)   NULL,
    [auaac_indirizzo_sog]           VARCHAR (200) NULL,
    [auaac_cap_sog]                 VARCHAR (5)   NULL,
    [auaac_comune_sog]              VARCHAR (100) NULL,
    [auaac_cod_com_sog]             VARCHAR (4)   NULL,
    [auaac_prov_sog]                VARCHAR (2)   NULL,
    [auaac_stato_sog]               VARCHAR (1)   NULL,
    [auaac_sede_inps]               VARCHAR (10)  NULL,
    [auaac_cf_az]                   VARCHAR (16)  NULL,
    [auaac_indirizzo_az]            VARCHAR (200) NULL,
    [auaac_cap_az]                  VARCHAR (5)   NULL,
    [auaac_comune_az]               VARCHAR (100) NULL,
    [auaac_cod_com_az]              VARCHAR (4)   NULL,
    [auaac_prov_az]                 VARCHAR (2)   NULL,
    [auaac_cod_assoc]               VARCHAR (10)  NULL,
    [auaac_nome_assoc]              VARCHAR (200) NULL,
    [auaac_cod_cancellazione]       VARCHAR (10)  NULL,
    [auaac_data_inizio]             VARCHAR (20)  NULL,
    [auaac_data_fine]               VARCHAR (20)  NULL,
    [auaac_data_domanda]            VARCHAR (20)  NULL,
    [auaac_tipo_domanda]            VARCHAR (5)   NULL,
    [auaac_cod_ateco02]             VARCHAR (10)  NULL,
    [auaac_data_in]                 DATETIME      NULL,
    [auaac_data_mod]                DATETIME      NULL,
    [AUAAC_STATO_LAVORAZIONE]       INT           CONSTRAINT [DF_TB_AUAAC_ANAGRAFICA_AC_AUAAC_STATO_LAVORAZIONE] DEFAULT ((0)) NULL,
    [AUAAC_TOPO_IND_SOG]            VARCHAR (50)  NULL,
    [AUAAC_COD_TOPO_IND_SOG]        VARCHAR (10)  NULL,
    [AUAAC_IND_SOG]                 VARCHAR (100) NULL,
    [AUAAC_CIVICO_SOG]              VARCHAR (50)  NULL,
    [AUAAC_IND_QLA_IND_SOG]         INT           CONSTRAINT [DF_TB_AUAAC_ANAGRAFICA_AC_AUAAC_IND_QLA_IND_SOG] DEFAULT ((0)) NULL,
    [AUAAC_TOPO_IND_AZ]             VARCHAR (50)  NULL,
    [AUAAC_COD_TOPO_IND_AZ]         VARCHAR (10)  NULL,
    [AUAAC_IND_AZ]                  VARCHAR (100) NULL,
    [AUAAC_CIVICO_AZ]               VARCHAR (50)  NULL,
    [AUAAC_IND_QLA_IND_AZ]          INT           NULL,
    [AUAAC_CODICE_AUSCA]            INT           CONSTRAINT [DF_TB_AUAAC_ANAGRAFICA_AC_AUAAC_CODICE_AUSCA] DEFAULT ((0)) NULL,
    [AUAAC_CODICE_AUSCO]            INT           CONSTRAINT [DF_TB_AUAAC_ANAGRAFICA_AC_AUAAC_CODICE_AUSCO] DEFAULT ((0)) NULL,
    [AUAAC_CODICE_AURSS]            INT           CONSTRAINT [DF_TB_AUAAC_ANAGRAFICA_AC_AUAAC_CODICE_AURSS] DEFAULT ((0)) NULL,
    [AUAAC_CODICE_AUPOC]            INT           CONSTRAINT [DF_TB_AUAAC_ANAGRAFICA_AC_AUAAC_CODICE_AUPOC] DEFAULT ((0)) NULL,
    [AUAAC_DENOMINAZIONE]           VARCHAR (200) NULL,
    [AUAAC_VALIDATO_AUSCA]          INT           CONSTRAINT [DF_TB_AUAAC_ANAGRAFICA_AC_AUAAC_VALIDATO_AUSCA] DEFAULT ((0)) NULL,
    [AUAAC_VALIDATO_AUSCO]          INT           CONSTRAINT [DF_TB_AUAAC_ANAGRAFICA_AC_AUAAC_VALIDATO_AUSCO] DEFAULT ((0)) NULL,
    [AUAAC_VALIDATO_AURSS]          INT           CONSTRAINT [DF_TB_AUAAC_ANAGRAFICA_AC_AUAAC_VALIDATO_AURSS] DEFAULT ((0)) NULL,
    [AUAAC_VALIDATO_AUPOC]          INT           CONSTRAINT [DF_TB_AUAAC_ANAGRAFICA_AC_AUAAC_VALIDATO_AUPOC] DEFAULT ((0)) NULL,
    [AUAAC_FLAG_AUSCA]              VARCHAR (1)   CONSTRAINT [DF_TB_AUAAC_ANAGRAFICA_AC_AUAAC_FLAG_AUSCA] DEFAULT ('N') NULL,
    [AUAAC_FLAG_AUSCO]              VARCHAR (1)   CONSTRAINT [DF_TB_AUAAC_ANAGRAFICA_AC_AUAAC_FLAG_AUSCO] DEFAULT ('N') NULL,
    [AUAAC_FLAG_AURSS]              VARCHAR (1)   CONSTRAINT [DF_TB_AUAAC_ANAGRAFICA_AC_AUAAC_FLAG_AURSS] DEFAULT ('N') NULL,
    [AUAAC_FLAG_AUPOC]              VARCHAR (1)   CONSTRAINT [DF_TB_AUAAC_ANAGRAFICA_AC_AUAAC_FLAG_AUPOC] DEFAULT ('N') NULL,
    [AUAAC_STATO_POSIZIONE]         INT           CONSTRAINT [DF_TB_AUAAC_ANAGRAFICA_AC_AUAAC_STATO_POSIZIONE] DEFAULT ((0)) NULL,
    [AUAAC_AUSIN]                   INT           CONSTRAINT [DF_TB_AUAAC_ANAGRAFICA_AC_AUAAC_AUSIN] DEFAULT ((0)) NULL,
    [AUAAC_DATA_INSERIMENTO]        VARCHAR (50)  CONSTRAINT [DF_TB_AUAAC_ANAGRAFICA_AC_AUAAC_DATA_INSERIMENTO] DEFAULT (getdate()) NULL,
    [AUAAC_DATA_MODIFICA]           VARCHAR (50)  CONSTRAINT [DF_TB_AUAAC_ANAGRAFICA_AC_AUAAC_DATA_MODIFICA] DEFAULT (getdate()) NULL,
    [AUAAC_AUATE]                   INT           CONSTRAINT [DF_TB_AUAAC_ANAGRAFICA_AC_AUAAC_AUATE] DEFAULT ((0)) NULL,
    [AUAAC_AUSCA_COD_QLA_IND]       INT           CONSTRAINT [DF_TB_AUAAC_ANAGRAFICA_AC_AUAAC_AUSCA_COD_QLA_IND] DEFAULT ((0)) NULL,
    [AUAAC_AUSCO_COD_QLA_IND]       INT           CONSTRAINT [DF_TB_AUAAC_ANAGRAFICA_AC_AUAAC_AUSCO_COD_QLA_IND] DEFAULT ((0)) NULL,
    [AUAAC_STATO_LAVORAZIONE_AUSCO] INT           CONSTRAINT [DF_TB_AUAAC_ANAGRAFICA_AC_AUAAC_STATO_LAVORAZIONE_AUSCO] DEFAULT ((0)) NULL
) ON [SECONDARIO];

