CREATE TABLE [dbo].[tb_audel_del] (
    [audel_codice_pk]      INT           IDENTITY (1, 1) NOT NULL,
    [audel_codice_fiscale] VARCHAR (16)  NOT NULL,
    [audel_denominazione]  VARCHAR (405) NULL,
    [audel_cognome]        VARCHAR (255) NULL,
    [audel_nome]           VARCHAR (150) NULL,
    [audel_note]           VARCHAR (200) NULL,
    [audel_tipo_persona]   VARCHAR (1)   NULL,
    [audel_toponimo]       VARCHAR (100) NULL,
    [audel_indirizzo]      VARCHAR (100) NULL,
    [audel_civico]         VARCHAR (50)  NULL,
    [audel_cap]            VARCHAR (5)   NULL,
    [audel_descr_comune]   VARCHAR (30)  NULL,
    [audel_provincia]      VARCHAR (2)   NULL,
    [audel_sesso]          VARCHAR (1)   NULL,
    [audel_data_nascita]   DATETIME      NULL,
    [audel_comune_nascita] VARCHAR (30)  NULL,
    [audel_prov_nascita]   VARCHAR (2)   NULL,
    [audel_telefono1]      VARCHAR (20)  NULL,
    [audel_telefono2]      VARCHAR (20)  NULL,
    [audel_fax]            VARCHAR (20)  NULL,
    [audel_data_modifica]  DATETIME      NULL,
    [audel_descr_utente]   VARCHAR (50)  NULL,
    [audel_codice_pk_db2]  INT           NULL,
    [audel_email]          VARCHAR (162) NULL,
    [audel_pec]            VARCHAR (162) NULL,
    [audel_legalmail]      VARCHAR (162) NULL,
    CONSTRAINT [PK_tb_audel] PRIMARY KEY CLUSTERED ([audel_codice_pk] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [UQ_audel_audel] UNIQUE NONCLUSTERED ([audel_codice_pk] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [UQ_audel_CF] UNIQUE NONCLUSTERED ([audel_codice_fiscale] ASC) WITH (FILLFACTOR = 90)
);

