CREATE TABLE [dbo].[TB_ANTCT_TIPCOMTER_CT] (
    [ANTCT_COD_TIPCOMTER_PK] VARCHAR (3)  NOT NULL,
    [ANTCT_DESCR_TIPCOMTER]  VARCHAR (50) NOT NULL,
    [ANTCT_BDLL_ID_VA]       BIGINT       NULL,
    [ANTCT_FLAG_ESPOSIZ]     VARCHAR (1)  CONSTRAINT [DF_TB_ANTCT_TIPCOMTER_CT_ANTCT_FLAG_ESPOSIZ] DEFAULT ('S') NOT NULL,
    [ANTCT_DATA_INIZ]        DATE         NOT NULL,
    [ANTCT_DATA_FINE]        DATE         CONSTRAINT [DF_TB_ANTCT_TIPCOMTER_CT_ANTCT_DATA_FINE] DEFAULT (CONVERT([date],'1999-12-31')) NOT NULL,
    [ANTCT_COD_UTENTE]       VARCHAR (16) NOT NULL,
    [ANTCT_DATA_AGGIORN]     DATETIME     CONSTRAINT [DF_TB_ANTCT_TIPCOMTER_CT_ANTCT_DATA_AGGIORN] DEFAULT (getdate()) NOT NULL,
    [ANTCT_COD_APPL]         VARCHAR (2)  NOT NULL,
    CONSTRAINT [PK_ANTCT_TIPCOMTER] PRIMARY KEY CLUSTERED ([ANTCT_COD_TIPCOMTER_PK] ASC),
    CONSTRAINT [CK1_ANTCT_FLAG_ESPOSIZ] CHECK ([ANTCT_FLAG_ESPOSIZ]='S' OR [ANTCT_FLAG_ESPOSIZ]='N')
);

