CREATE TABLE [dbo].[tb_auain_aziende_enpals] (
    [AUAIN_CODICE_PK]             INT           IDENTITY (1, 1) NOT NULL,
    [auain_tipo_soggetto]         VARCHAR (1)   NULL,
    [auain_denominazione]         VARCHAR (405) NULL,
    [auain_codice_fiscale]        VARCHAR (16)  NULL,
    [auain_partita_iva]           VARCHAR (11)  NULL,
    [auain_nome]                  VARCHAR (255) NULL,
    [auain_cognome]               VARCHAR (255) NULL,
    [auain_data_nascita]          DATETIME      NULL,
    [auain_com_nasc]              VARCHAR (30)  NULL,
    [auain_belf_com_nasc]         VARCHAR (5)   NULL,
    [auain_prov_nascita]          VARCHAR (2)   NULL,
    [auain_toponimo]              VARCHAR (50)  NULL,
    [auain_indirizzo]             VARCHAR (255) NULL,
    [auain_civico]                VARCHAR (50)  NULL,
    [auain_cap]                   VARCHAR (5)   NULL,
    [auain_comune]                VARCHAR (30)  NULL,
    [auain_belf_com]              VARCHAR (5)   NULL,
    [auain_sigla_prov]            VARCHAR (2)   NULL,
    [auain_frazione]              VARCHAR (100) NULL,
    [auain_localita]              VARCHAR (50)  NULL,
    [auain_telefono]              VARCHAR (20)  NULL,
    [auain_fax]                   VARCHAR (20)  NULL,
    [auain_email]                 VARCHAR (160) NULL,
    [auain_pec]                   VARCHAR (160) NULL,
    [auain_cf_rappr_legale]       VARCHAR (16)  NULL,
    [auain_data_inizio_val]       DATETIME      NULL,
    [auain_nome_RL]               VARCHAR (255) NULL,
    [auain_cognome_RL]            VARCHAR (255) NULL,
    [auain_data_nasc_RL]          DATETIME      NULL,
    [auain_com_nasc_RL]           VARCHAR (30)  NULL,
    [auain_belf_com_nasc_RL]      VARCHAR (5)   NULL,
    [auain_prov_nasc_RL]          VARCHAR (2)   NULL,
    [auain_toponimo_RL]           VARCHAR (50)  NULL,
    [auain_indirizzo_RL]          VARCHAR (255) NULL,
    [auain_civico_RL]             VARCHAR (50)  NULL,
    [auain_cap_RL]                VARCHAR (5)   NULL,
    [auain_comune_RL]             VARCHAR (30)  NULL,
    [auain_belf_com_RL]           VARCHAR (5)   NULL,
    [auain_sigla_prov_RL]         VARCHAR (2)   NULL,
    [auain_frazione_RL]           VARCHAR (100) NULL,
    [auain_localita_RL]           VARCHAR (50)  NULL,
    [auain_telefono_RL]           VARCHAR (20)  NULL,
    [auain_fax_RL]                VARCHAR (20)  NULL,
    [auain_email_RL]              VARCHAR (160) NULL,
    [auain_pec_RL]                VARCHAR (160) NULL,
    [auain_nat_giur]              VARCHAR (100) NULL,
    [auain_raggr_nat_giur]        VARCHAR (100) NULL,
    [auain_tipo_societa]          VARCHAR (100) NULL,
    [auain_data_inizio_attiv]     DATETIME      NULL,
    [auain_stato]                 VARCHAR (20)  NULL,
    [auain_data_var_stato]        DATETIME      NULL,
    [auain_ateco]                 VARCHAR (7)   NULL,
    [auain_codice_gruppo]         VARCHAR (6)   NULL,
    [AUAIN_DATA_MODIFICA]         DATETIME      CONSTRAINT [DF_tb_auain_aziende_enpals_AUAIN_DATA_MODIFICA] DEFAULT (getdate()) NULL,
    [AUAIN_STATO_LAVORAZIONE]     INT           CONSTRAINT [DF_tb_auain_aziende_enpals_AUAIN_STATO_LAVORAZIONE] DEFAULT ((0)) NULL,
    [AUAIN_CODICE_LOTTO]          INT           CONSTRAINT [DF_tb_auain_aziende_enpals_AUAIN_CODICE_LOTTO] DEFAULT ((0)) NULL,
    [AUAIN_FLAG_AUSCA]            VARCHAR (1)   CONSTRAINT [DF_tb_auain_aziende_enpals_AUAIN_FLAG_AUSCA] DEFAULT ('N') NULL,
    [AUAIN_FLAG_AUSCO]            VARCHAR (1)   CONSTRAINT [DF_tb_auain_aziende_enpals_AUAIN_FLAG_AUSCO] DEFAULT ('N') NULL,
    [AUAIN_CODICE_AUSCA]          INT           CONSTRAINT [DF_tb_auain_aziende_enpals_AUAIN_CODICE_AUSCA] DEFAULT ((0)) NULL,
    [AUAIN_CODICE_AUSCO]          INT           CONSTRAINT [DF_tb_auain_aziende_enpals_AUAIN_CODICE_AUSCO] DEFAULT ((0)) NULL,
    [AUAIN_FLAG_AUSCO_RL]         VARCHAR (1)   CONSTRAINT [DF_tb_auain_aziende_enpals_AUAIN_FLAG_AUSCO_RL] DEFAULT ('N') NULL,
    [AUAIN_CODICE_AUSCO_RL]       INT           CONSTRAINT [DF_tb_auain_aziende_enpals_AUAIN_CODICE_AUSCO_RL] DEFAULT ((0)) NULL,
    [AUAIN_FLAG_AURSS]            VARCHAR (1)   CONSTRAINT [DF_tb_auain_aziende_enpals_AUAIN_FLAG_AURSS] DEFAULT ('N') NULL,
    [AUAIN_FLAG_AURSS_RL]         VARCHAR (1)   CONSTRAINT [DF_tb_auain_aziende_enpals_AUAIN_FLAG_AURSS_RL] DEFAULT ('N') NULL,
    [AUAIN_TS]                    VARCHAR (1)   CONSTRAINT [DF_tb_auain_aziende_enpals_auain_ts] DEFAULT ((0)) NULL,
    [Auain_presenti_posizioni_DM] VARCHAR (1)   NULL,
    [AUAIN_IND_QUALITA_INDIR]     INT           CONSTRAINT [DF_tb_auain_posizioni_enpals_AUAIN_IND_QUALITA_INDIR] DEFAULT ((0)) NULL,
    [AUAIN_IND_QUALITA_INDIR_RL]  INT           CONSTRAINT [DF_tb_auain_posizioni_enpals_AUAIN_IND_QUALITA_INDIR_RL] DEFAULT ((0)) NULL
);

