CREATE TABLE [dbo].[TB_ANCOT_COMPTERR_CL] (
    [ANCOT_BDSO_ID_VA_PK]          BIGINT       NOT NULL,
    [ANCOT_ANTCT_COD_TIPCOMTER_PK] VARCHAR (3)  NOT NULL,
    [ANCOT_BDLC_ID_VA_PK]          BIGINT       NOT NULL,
    [ANCOT_DATA_INIZ_PK]           DATE         NOT NULL,
    [ANCOT_DATA_FINE]              DATE         CONSTRAINT [DF_TB_ANCOT_COMPTERR_CL_ANCOT_DATA_FINE] DEFAULT (CONVERT([date],'1999-12-31')) NOT NULL,
    [ANCOT_COD_UTENTE]             VARCHAR (16) NOT NULL,
    [ANCOT_DATA_AGGIORN]           DATE         CONSTRAINT [DF_TB_ANCOT_COMPTERR_CL_ANCOT_DATA_AGGIORN] DEFAULT (getdate()) NOT NULL,
    [ANCOT_COD_APPL]               VARCHAR (2)  NOT NULL,
    [ANCOT_DATA_SISTEMA]           DATETIME     NULL,
    [ANCOT_AUC_CODICE_PK]          BIGINT       IDENTITY (1, 1) NOT NULL,
    [ANCOT_AUC_DATA_INSERIMENTO]   DATETIME     CONSTRAINT [DF_TB_ANCOT_COMPTERR_CL_ANCOT_AUC_DATA_INSERIMENTO] DEFAULT (getdate()) NULL,
    [ANCOT_AUC_STATO_LAVORAZIONE]  INT          CONSTRAINT [DF_TB_ANCOT_COMPTERR_CL_ANCOT_AUC_STATO_LAVORAZIONE] DEFAULT ((0)) NULL,
    [ANCOT_AUC_CF_PK]              VARCHAR (16) NULL,
    [ANCOT_AUC_AUSCA_PK]           INT          NULL,
    [ANCOT_AUC_PRESENTE]           INT          CONSTRAINT [DF_TB_ANCOT_COMPTERR_CL_ANCOT_AUC_PRESENTE] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_ANCOT_COMPTERR] PRIMARY KEY CLUSTERED ([ANCOT_BDSO_ID_VA_PK] ASC, [ANCOT_ANTCT_COD_TIPCOMTER_PK] ASC, [ANCOT_BDLC_ID_VA_PK] ASC, [ANCOT_DATA_INIZ_PK] ASC),
    CONSTRAINT [FK1_ANCOT_BDSO] FOREIGN KEY ([ANCOT_BDSO_ID_VA_PK]) REFERENCES [dbo].[BDSO_SOCIETA_CL] ([BDSO_ID_VA]),
    CONSTRAINT [FK2_ANCOT_ANTCT] FOREIGN KEY ([ANCOT_ANTCT_COD_TIPCOMTER_PK]) REFERENCES [dbo].[TB_ANTCT_TIPCOMTER_CT] ([ANTCT_COD_TIPCOMTER_PK]),
    CONSTRAINT [FK3_ANCOT_BDLC] FOREIGN KEY ([ANCOT_BDLC_ID_VA_PK]) REFERENCES [dbo].[BDLC_LOCALITA_CL] ([BDLC_ID_VA])
);

