CREATE TABLE [dbo].[tb_aurss_rel_sog_sog] (
    [aurss_codice_pk]                BIGINT        IDENTITY (1, 1) NOT NULL,
    [aurss_ausca_codice_pk]          INT           NULL,
    [aurss_ausco_codice_pk]          INT           NULL,
    [aurss_aussu_codice_pk]          INT           NULL,
    [aurss_autis_codice_pk]          INT           NULL,
    [aurss_data_inizio_validita]     DATETIME      NULL,
    [aurss_data_di_fine_validita]    DATETIME      NULL,
    [aurss_data_iscr_libro_soci]     DATETIME      NULL,
    [aurss_data_atto_di_nomina]      DATETIME      NULL,
    [aurss_data_nomina]              DATETIME      NULL,
    [aurss_data_fine_carica]         DATETIME      NULL,
    [aurss_note]                     VARCHAR (200) NULL,
    [aurss_rappresentante_legale]    VARCHAR (1)   NULL,
    [aurss_data_modifica]            DATETIME      NULL,
    [aurss_descr_utente]             VARCHAR (50)  NULL,
    [aurss_codice_pk_db2]            BIGINT        NULL,
    [aurss_relazione_certificata]    CHAR (1)      CONSTRAINT [DF__tb_aurss___aurss__5FA15699] DEFAULT ('N') NULL,
    [aurss_rec_del]                  VARCHAR (1)   NULL,
    [aurss_data_del]                 DATETIME      NULL,
    [aurss_cert_auten_cod_pk]        INT           NULL,
    [aurss_cert_cod_entita_rif]      INT           NULL,
    [aurss_cert_data_modifica]       DATETIME      NULL,
    [aurss_auten_codice_pk]          INT           NULL,
    [aurss_codice_entita_rif]        INT           NULL,
    [aurss_indice_qualita_relazione] INT           NULL,
    [aurss_codice_carica]            VARCHAR (4)   NULL,
    [aurss_provenienza]              VARCHAR (30)  NULL,
    [aurss_data_iscrizione]          DATETIME      NULL,
    [aurss_flag_chiusura]            SMALLINT      CONSTRAINT [DF_tb_aurss_rel_sog_sog_aurss_flag_chiusura] DEFAULT ((0)) NULL,
    [aurss_cap_agire]                VARCHAR (2)   NULL,
    [aurss_flag_se_elettore]         VARCHAR (1)   NULL,
    [aurss_potere_firma]             VARCHAR (1)   NULL,
    [aurss_quote_partec]             VARCHAR (15)  NULL,
    [aurss_perce_partec]             VARCHAR (4)   NULL,
    [aurss_quote_partec_e]           VARCHAR (17)  NULL,
    [aurss_quota_c_valuta]           VARCHAR (3)   NULL,
    [aurss_cod_durata_carica]        VARCHAR (2)   NULL,
    [aurss_anni_ese_carica]          VARCHAR (2)   NULL,
    [aurss_data_pres_carica]         VARCHAR (8)   NULL,
    [aurss_prog_pers]                VARCHAR (4)   NULL,
    [aurss_progressivo_carica]       VARCHAR (4)   NULL,
    [aurss_posizione]                VARCHAR (50)  NULL,
    CONSTRAINT [PK_tb_aurss] PRIMARY KEY CLUSTERED ([aurss_codice_pk] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_aurss_ausca] FOREIGN KEY ([aurss_ausca_codice_pk]) REFERENCES [dbo].[tb_ausca_sog_contr_az] ([ausca_codice_pk]),
    CONSTRAINT [FK_aurss_ausco] FOREIGN KEY ([aurss_ausco_codice_pk]) REFERENCES [dbo].[tb_ausco_sog_contr_col] ([ausco_codice_pk]),
    CONSTRAINT [FK_aurss_aussu] FOREIGN KEY ([aurss_aussu_codice_pk]) REFERENCES [dbo].[tb_aussu_stato_sog_utente_ct] ([aussu_codice_pk]),
    CONSTRAINT [FK_aurss_autis] FOREIGN KEY ([aurss_autis_codice_pk]) REFERENCES [dbo].[tb_autis_tipo_sog_col_ct] ([autis_codice_pk]),
    CONSTRAINT [UQ_aurss_aurss] UNIQUE NONCLUSTERED ([aurss_codice_pk] ASC) WITH (FILLFACTOR = 90)
);

