CREATE TABLE [dbo].[TB_AUSSA_STORICO_SOGGETTO_ARCA] (
    [AUSSA_CODICE_PK]                BIGINT        IDENTITY (1, 1) NOT NULL,
    [AUSSA_CHIAVE_AUC]               INT           NULL,
    [AUSSA_PROVENIENZA]              VARCHAR (5)   NULL,
    [AUSSA_CODICE_FISCALE]           VARCHAR (16)  NULL,
    [AUSSA_CHIAVE_ARCA]              BIGINT        NULL,
    [AUSSA_DENOMINAZIONE]            VARCHAR (405) NULL,
    [AUSSA_COGNOME]                  VARCHAR (255) NULL,
    [AUSSA_NOME]                     VARCHAR (150) NULL,
    [AUSSA_SESSO]                    VARCHAR (1)   NULL,
    [AUSSA_FRAZIONE]                 VARCHAR (100) NULL,
    [AUSSA_TOPONIMO]                 VARCHAR (100) NULL,
    [AUSSA_INDIRIZZO]                VARCHAR (100) NULL,
    [AUSSA_CIVICO]                   VARCHAR (50)  NULL,
    [AUSSA_CAP]                      VARCHAR (5)   NULL,
    [AUSSA_COMUNE]                   VARCHAR (50)  NULL,
    [AUSSA_PROVINCIA]                VARCHAR (2)   NULL,
    [AUSSA_COD_COMUNE_BELF]          VARCHAR (4)   NULL,
    [AUSSA_DATA_NASCITA]             DATE          NULL,
    [AUSSA_DATA_MORTE]               DATE          NULL,
    [AUSSA_COMUNE_NASCITA]           VARCHAR (50)  NULL,
    [AUSSA_PROVINCIA_NASCITA]        VARCHAR (2)   NULL,
    [AUSSA_COD_COMUNE_BELF_NASCITA]  VARCHAR (4)   NULL,
    [AUSSA_COD_NAZIONE_BELF_NASCITA] VARCHAR (4)   NULL,
    [AUSSA_SIGLA_NAZIONE_NASCITA]    VARCHAR (3)   NULL,
    [AUSSA_DESCR_NAZIONE_NASCITA]    VARCHAR (100) NULL,
    [AUSSA_NAZIONALITA]              VARCHAR (4)   NULL,
    [AUSSA_TELEFONO]                 VARCHAR (20)  NULL,
    [AUSSA_EMAIL]                    VARCHAR (162) NULL,
    [AUSSA_PEC]                      VARCHAR (162) NULL,
    [AUSSA_DESCR_UTENTE]             VARCHAR (50)  NULL,
    [AUSSA_DATA_MODIFICA]            DATETIME      NULL,
    [AUSSA_FONTE_VALIDAZIONE]        VARCHAR (2)   NULL,
    [AUSSA_MOTIVO_SCARTO]            VARCHAR (2)   NULL,
    [AUSSA_DATA_INSERIMENTO]         DATETIME      NULL,
    [AUSSA_DATA_LAVORAZIONE]         DATETIME      NULL,
    [AUSSA_LOTTO]                    INT           NULL,
    [AUSSA_DATA_LAVORAZIONE_AUC]     DATETIME      NULL,
    [AUSSA_RICHIEDENTE]              VARCHAR (50)  NULL,
    [AUSSA_LAVORAZIONE_AUC]          CHAR (1)      NULL,
    [AUSSA_AUIAS_CODICE_PK]          BIGINT        NULL,
    [AUSSA_CfCcc1_Ev0_ARCA]          VARCHAR (3)   NULL,
    [AUSSA_Progr_Ev0_ARCA]           INT           NULL,
    CONSTRAINT [PK_tb_aussaA] PRIMARY KEY CLUSTERED ([AUSSA_CODICE_PK] ASC),
    CONSTRAINT [UQ_aussa_aussa] UNIQUE NONCLUSTERED ([AUSSA_CODICE_PK] ASC)
);

