CREATE TABLE [dbo].[TB_AULDG_PERSONA_GIURIDICA_LD] (
    [AULDG_CODICE_PK]                INT           IDENTITY (1, 1) NOT NULL,
    [auldg_denominazione]            VARCHAR (405) NULL,
    [auldg_codice_fiscale]           VARCHAR (16)  NULL,
    [auldg_cap]                      NCHAR (5)     NULL,
    [auldg_comune]                   VARCHAR (100) NULL,
    [auldg_sigla_provincia]          VARCHAR (50)  NULL,
    [auldg_indirizzo_sede_input]     VARCHAR (255) NULL,
    [auldg_codice_fiscale_rl]        NCHAR (16)    NULL,
    [auldg_nome_rl]                  VARCHAR (150) NULL,
    [auldg_cognome_rl]               VARCHAR (255) NULL,
    [auldg_sesso_rl]                 VARCHAR (2)   NULL,
    [auldg_comune_nascita_rl]        NCHAR (60)    NULL,
    [auldg_data_nascita_rl]          DATETIME      NULL,
    [auldg_prov_nascita_rl]          NCHAR (2)     NULL,
    [auldg_pec]                      NCHAR (160)   NULL,
    [auldg_email]                    NCHAR (160)   NULL,
    [auldg_telefono]                 NCHAR (20)    NULL,
    [auldg_toponimo]                 NCHAR (50)    NULL,
    [auldg_codice_toponimo]          VARCHAR (3)   NULL,
    [auldg_indirizzo]                VARCHAR (255) NULL,
    [auldg_civico]                   VARCHAR (50)  NULL,
    [auldg_indice_qualita_indirizzo] INT           NULL,
    [auldg_data_inserimento]         DATETIME      NULL,
    [auldg_sequenza_inserimento]     INT           NULL,
    [AULDG_VALIDATO_AUSCA]           INT           CONSTRAINT [DF_TB_AULDG_PERSONA_GIURIDICA_LD_AULDG_VALIDATO_AUSCA] DEFAULT ((0)) NULL,
    [AULDG_VALIDATO_AUSCO]           INT           CONSTRAINT [DF_TB_AULDG_PERSONA_GIURIDICA_LD_AULDG_VALIDATO_AUSCO] DEFAULT ((0)) NULL,
    [AULDG_VALIDATO_AURSS]           INT           CONSTRAINT [DF_TB_AULDG_PERSONA_GIURIDICA_LD_AULDG_VALIDATO_AURSS] DEFAULT ((0)) NULL,
    [AULDG_FLAG_AUSCA]               VARCHAR (1)   CONSTRAINT [DF_TB_AULDG_PERSONA_GIURIDICA_LD_AULDG_FLAG_AUSCA] DEFAULT ('N') NULL,
    [AULDG_FLAG_AUSCO]               VARCHAR (1)   CONSTRAINT [DF_TB_AULDG_PERSONA_GIURIDICA_LD_AULDG_FLAG_AUSCO] DEFAULT ('N') NULL,
    [AULDG_FLAG_AURSS]               VARCHAR (1)   CONSTRAINT [DF_TB_AULDG_PERSONA_GIURIDICA_LD_AULDG_FLAG_AURSS] DEFAULT ('N') NULL,
    [AULDG_DATA_MODIFICA]            DATETIME      CONSTRAINT [DF_TB_AULDG_PERSONA_GIURIDICA_LD_AULDG_DATA_MODIFICA] DEFAULT (getdate()) NULL,
    [AULDG_STATO_LAVORAZIONE]        INT           CONSTRAINT [DF_TB_AULDG_PERSONA_GIURIDICA_LD_AULDG_STATO_LAVORAZIONE] DEFAULT ((0)) NULL,
    [AULDG_CODICE_LOTTO]             INT           CONSTRAINT [DF_TB_AULDG_PERSONA_GIURIDICA_LD_AULDG_CODICE_LOTTO] DEFAULT ((0)) NULL,
    [AULDG_CODICE_AUSCA]             INT           CONSTRAINT [DF_TB_AULDG_PERSONA_GIURIDICA_LD_AULDG_CODICE_AUSCA] DEFAULT ((0)) NULL,
    [AULDG_CODICE_AUSCO]             INT           CONSTRAINT [DF_TB_AULDG_PERSONA_GIURIDICA_LD_AULDG_CODICE_AUSCO] DEFAULT ((0)) NULL,
    [AULDG_CODICE_AURSS]             INT           CONSTRAINT [DF_TB_AULDG_PERSONA_GIURIDICA_LD_AULDG_CODICE_AURSS] DEFAULT ((0)) NULL
);

