CREATE TABLE [dbo].[TB_ANNGG_NATGIURPG_CL] (
    [ANNGG_BDSO_ID_VA_PK]         BIGINT       NOT NULL,
    [ANNGG_DATA_INIZ_PK]          DATE         NOT NULL,
    [ANNGG_DATA_FINE]             DATE         CONSTRAINT [DF_TB_ANNGG_NATGIURPG_CL_ANNGG_DATA_FINE] DEFAULT (CONVERT([date],'9999-12-31')) NOT NULL,
    [ANNGG_BDNG_ID_VA]            BIGINT       NOT NULL,
    [ANNGG_COD_UTENTE]            VARCHAR (16) NOT NULL,
    [ANNGG_DATA_AGGIORN]          DATE         CONSTRAINT [DF_TB_ANNGG_NATGIURPG_CL_ANNGG_DATA_AGGIORN] DEFAULT (getdate()) NOT NULL,
    [ANNGG_COD_APPL]              VARCHAR (2)  NOT NULL,
    [ANNGG_DATA_SISTEMA]          DATETIME     NULL,
    [ANNGG_AUC_CODICE_PK]         BIGINT       IDENTITY (1, 1) NOT NULL,
    [ANNGG_AUC_DATA_INSERIMENTO]  DATETIME     CONSTRAINT [DF_TB_ANNGG_NATGIURPG_CL_ANNGG_AUC_DATA_INSERIMENTO] DEFAULT (getdate()) NULL,
    [ANNGG_AUC_STATO_LAVORAZIONE] INT          CONSTRAINT [DF_TB_ANNGG_NATGIURPG_CL_ANNG_AUC_STATO_LAVORAZIONE] DEFAULT ((0)) NULL,
    [ANNGG_AUC_CF_PK]             VARCHAR (16) NULL,
    [ANNGG_AUC_AUSCA_PK]          INT          CONSTRAINT [DF_TB_ANNGG_NATGIURPG_CL_ANNGG_AUC_AUSCA_PK] DEFAULT ((0)) NULL,
    [ANNGG_AUC_PRESENTE]          INT          CONSTRAINT [DF_TB_ANNGG_NATGIURPG_CL_ANNGG_AUC_PRESENTE] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_ANNGG_NATGIURPG] PRIMARY KEY CLUSTERED ([ANNGG_BDSO_ID_VA_PK] ASC, [ANNGG_DATA_INIZ_PK] ASC),
    CONSTRAINT [CK1_ANNGG_DATE_INIZ_FINE] CHECK ([ANNGG_DATA_FINE]>=[ANNGG_DATA_INIZ_PK]),
    CONSTRAINT [FK1_ANNGG_BDSO] FOREIGN KEY ([ANNGG_BDSO_ID_VA_PK]) REFERENCES [dbo].[BDSO_SOCIETA_CL] ([BDSO_ID_VA])
);

