CREATE TABLE [dbo].[TB_ANCNG_CLASSNG_CT] (
    [ANCNG_COD_CLASS_PK]  VARCHAR (1)  NOT NULL,
    [ANCNG_DESCR_CLASSPG] VARCHAR (50) NOT NULL,
    [ANCNG_DATA_INIZ]     DATETIME     NOT NULL,
    [ANCNG_DATA_FINE]     DATETIME     NOT NULL,
    [ANCNG_FLAG_ESPOSIZ]  VARCHAR (1)  NOT NULL,
    [ANCNG_COD_UTENTE]    VARCHAR (16) NOT NULL,
    [ANCNG_DATA_AGGIORN]  DATETIME     NOT NULL,
    [ANCNG_COD_APPL]      VARCHAR (2)  NOT NULL,
    CONSTRAINT [PK_TB_ANCNG_CLASSNG_CT] PRIMARY KEY CLUSTERED ([ANCNG_COD_CLASS_PK] ASC),
    CONSTRAINT [CK1_ANCNG_FLAG_ESPOSIZ] CHECK ([ANCNG_FLAG_ESPOSIZ]='N' OR [ANCNG_FLAG_ESPOSIZ]='S'),
    CONSTRAINT [CK2_ANCNG_DATE_INIZ_FINE] CHECK ([ANCNG_DATA_FINE]>=[ANCNG_DATA_INIZ])
);

