CREATE TABLE [dbo].[TB_AUOPE_OPERAZIONI] (
    [AUOPE_CODICE_PK]    BIGINT        IDENTITY (1, 1) NOT NULL,
    [AUOPE_DESCRIZIONE]  VARCHAR (405) NULL,
    [AUOPE_NUM_RECORD]   INT           NULL,
    [AUOPE_DATA_UPLOAD]  DATETIME      NULL,
    [AUOPE_UTENTE]       VARCHAR (50)  NULL,
    [AUOPE_AUREP_CODICE] INT           NULL
);

