CREATE TABLE [dbo].[tb_aulin_allineamento] (
    [aulin_colonna_01]  VARCHAR (255) NULL,
    [aulin_colonna_02]  VARCHAR (255) NULL,
    [aulin_colonna_03]  VARCHAR (255) NULL,
    [aulin_colonna_04]  VARCHAR (255) NULL,
    [aulin_colonna_05]  VARCHAR (255) NULL,
    [aulin_colonna_06]  VARCHAR (255) NULL,
    [aulin_colonna_07]  VARCHAR (255) NULL,
    [aulin_colonna_08]  VARCHAR (255) NULL,
    [aulin_colonna_09]  VARCHAR (255) NULL,
    [aulin_colonna_10]  VARCHAR (255) NULL,
    [aulin_colonna_11]  VARCHAR (255) NULL,
    [aulin_colonna_12]  VARCHAR (255) NULL,
    [aulin_colonna_13]  VARCHAR (255) NULL,
    [aulin_colonna_14]  VARCHAR (255) NULL,
    [aulin_colonna_15]  VARCHAR (255) NULL,
    [aulin_colonna_16]  VARCHAR (255) NULL,
    [aulin_colonna_17]  VARCHAR (255) NULL,
    [aulin_colonna_18]  VARCHAR (255) NULL,
    [aulin_colonna_19]  VARCHAR (255) NULL,
    [aulin_colonna_20]  VARCHAR (255) NULL,
    [aulin_colonna_21]  VARCHAR (255) NULL,
    [aulin_colonna_22]  VARCHAR (255) NULL,
    [aulin_colonna_23]  VARCHAR (255) NULL,
    [aulin_colonna_24]  VARCHAR (255) NULL,
    [aulin_colonna_25]  VARCHAR (255) NULL,
    [aulin_colonna_26]  VARCHAR (255) NULL,
    [aulin_colonna_27]  VARCHAR (255) NULL,
    [aulin_colonna_28]  VARCHAR (255) NULL,
    [aulin_colonna_29]  VARCHAR (255) NULL,
    [aulin_colonna_30]  VARCHAR (255) NULL,
    [aulin_colonna_31]  VARCHAR (255) NULL,
    [aulin_colonna_32]  VARCHAR (255) NULL,
    [aulin_colonna_33]  VARCHAR (255) NULL,
    [aulin_colonna_34]  VARCHAR (255) NULL,
    [aulin_colonna_35]  VARCHAR (255) NULL,
    [aulin_colonna_36]  VARCHAR (255) NULL,
    [aulin_colonna_37]  VARCHAR (255) NULL,
    [aulin_colonna_38]  VARCHAR (255) NULL,
    [aulin_colonna_39]  VARCHAR (255) NULL,
    [aulin_colonna_40]  VARCHAR (255) NULL,
    [aulin_int_01]      INT           NULL,
    [aulin_int_02]      INT           NULL,
    [aulin_int_03]      INT           NULL,
    [aulin_int_04]      INT           NULL,
    [aulin_int_05]      INT           NULL,
    [aulin_int_06]      INT           NULL,
    [aulin_int_07]      INT           NULL,
    [aulin_int_08]      INT           NULL,
    [aulin_int_09]      INT           NULL,
    [aulin_int_10]      INT           NULL,
    [aulin_colonna_xml] XML           NULL,
    [aulin_cf]          VARCHAR (16)  NULL,
    [aulin_label]       VARCHAR (40)  NULL
);

