CREATE TABLE [dbo].[TB_ANPID_PERINVIODMA_CL] (
    [ANPID_BDSO_ID_VA]         BIGINT       NOT NULL,
    [ANPID_DATA_INIZ]          DATE         NOT NULL,
    [ANPID_DATA_FINE]          DATE         NULL,
    [ANPID_FLAG_VALIDO]        VARCHAR (1)  CONSTRAINT [DF_TB_ANPID_PERINVIODMA_CL_ANPID_FLAG_VALIDO] DEFAULT ('S') NOT NULL,
    [ANPID_COD_UTENTE]         VARCHAR (16) NOT NULL,
    [ANPID_DATA_AGGIORN]       DATE         CONSTRAINT [DF_TB_ANPID_PERINVIODMA_CL_ANPID_DATA_AGGIORN] DEFAULT (getdate()) NOT NULL,
    [ANPID_COD_APPL]           VARCHAR (2)  NOT NULL,
    [ANPID_SEQ_PERINVIODMA_PK] BIGINT       IDENTITY (60000, 1) NOT NULL,
    [ANPID_DATA_SISTEMA]       DATETIME     NULL,
    CONSTRAINT [PK_ANPID_PERINVIODMA] PRIMARY KEY CLUSTERED ([ANPID_SEQ_PERINVIODMA_PK] ASC),
    CONSTRAINT [CK1_ANPID_DATE_INIZ_FINE] CHECK ([ANPID_DATA_FINE]>=[ANPID_DATA_INIZ]),
    CONSTRAINT [CK1_ANPID_FLAG_VALIDO_DOM] CHECK ([ANPID_FLAG_VALIDO]='N' OR [ANPID_FLAG_VALIDO]='S'),
    CONSTRAINT [FK1_ANPID_BDSO] FOREIGN KEY ([ANPID_BDSO_ID_VA]) REFERENCES [dbo].[BDSO_SOCIETA_CL] ([BDSO_ID_VA])
);

