CREATE TABLE [dbo].[tb_aupoc_pos_contr] (
    [aupoc_codice_pk]                    INT            IDENTITY (1, 1) NOT NULL,
    [aupoc_contro_codice]                VARCHAR (2)    NULL,
    [aupoc_ausca_codice_pk]              INT            NULL,
    [aupoc_auapp_codice_pk]              INT            NULL,
    [aupoc_auspc_codice_pk]              INT            NULL,
    [aupoc_autia_codice_pk]              INT            NULL,
    [aupoc_autdt_codice_pk]              INT            NULL,
    [aupoc_autd2_codice_pk]              INT            NULL,
    [aupoc_posizione]                    VARCHAR (50)   NULL,
    [aupoc_sede_provinciale]             INT            NULL,
    [aupoc_matricola_azienda]            INT            NULL,
    [aupoc_controcod_matr_az]            INT            NULL,
    [aupoc_sede_zonale]                  VARCHAR (2)    NULL,
    [aupoc_data_inizio_attivita]         DATETIME       NULL,
    [aupoc_denom_posiz_contr]            VARCHAR (405)  NULL,
    [aupoc_cod_prov_istat]               VARCHAR (3)    NULL,
    [aupoc_cod_comune_istat]             VARCHAR (3)    NULL,
    [aupoc_prog_azienda_agr]             INT            NULL,
    [aupoc_cida]                         VARCHAR (10)   NULL,
    [aupoc_note]                         VARCHAR (2000) NULL,
    [aupoc_annullata]                    VARCHAR (1)    NULL,
    [aupoc_data_domanda_iscr]            DATETIME       NULL,
    [aupoc_provenienza_iscr]             VARCHAR (1)    NULL,
    [aupoc_cod_sede_INPS]                VARCHAR (6)    NULL,
    [aupoc_cod_agenzia]                  VARCHAR (6)    NULL,
    [aupoc_utente_acquisizione]          VARCHAR (8)    NULL,
    [aupoc_utente_validazione]           VARCHAR (8)    NULL,
    [aupoc_attivita_dichiarata]          VARCHAR (80)   NULL,
    [aupoc_flag_operativo]               INT            NULL,
    [aupoc_data_modifica]                DATETIME       NULL,
    [aupoc_descr_utente]                 VARCHAR (50)   NULL,
    [aupoc_ateco]                        VARCHAR (20)   NULL,
    [aupoc_auate_1991_codice_pk]         INT            NULL,
    [aupoc_auate_2002_codice_pk]         INT            NULL,
    [aupoc_auate_2007_codice_pk]         INT            NULL,
    [aupoc_desATECO]                     VARCHAR (200)  NULL,
    [aupoc_codice_pk_db2]                INT            NULL,
    [aupoc_ausin_codice_pk]              INT            NULL,
    [aupoc_aurea_codice_pk]              INT            NULL,
    [aupoc_aucom_codice]                 VARCHAR (1)    NULL,
    [aupoc_cf_confluito]                 VARCHAR (16)   NULL,
    [aupoc_codice_categoria]             VARCHAR (3)    NULL,
    [aupoc_codice_gruppo]                VARCHAR (6)    NULL,
    [aupoc_data_del]                     DATETIME       NULL,
    [aupoc_id_confluito]                 VARCHAR (10)   NULL,
    [aupoc_id_sin]                       VARCHAR (10)   NULL,
    [aupoc_progressivo_confluito]        VARCHAR (5)    NULL,
    [aupoc_rec_del]                      VARCHAR (1)    NULL,
    [aupoc_tipo_posizione]               INT            CONSTRAINT [DF_tb_aupoc_pos_contr_aupoc_tipo_posizione] DEFAULT ((0)) NULL,
    [aupoc_data_ultimo_stato]            DATETIME       NULL,
    [aupoc_ente_dichiarante_INPDAP]      VARCHAR (1)    NULL,
    [aupoc_ente_appartenenza_INPDAP]     VARCHAR (1)    NULL,
    [aupoc_sede_servizio_INPDAP]         VARCHAR (1)    NULL,
    [aupoc_ente_versante_INPDAP]         VARCHAR (1)    NULL,
    [aupoc_chiave_LD]                    VARCHAR (50)   NULL,
    [aupoc_cfLavoratore_LD]              VARCHAR (16)   NULL,
    [aupoc_codice_stato_LD]              VARCHAR (2)    NULL,
    [aupoc_descr_stato_LD]               VARCHAR (20)   NULL,
    [aupoc_cod_cancellazione_AC]         VARCHAR (5)    NULL,
    [aupoc_matricola_riferimento_dm]     VARCHAR (50)   NULL,
    [aupoc_descr_stato_GS]               VARCHAR (50)   NULL,
    [AUPOC_PROVENIENZA_ISCRIZIONE]       VARCHAR (20)   NULL,
    [AUPOC_OPER_ACQUISIZIONE]            VARCHAR (20)   NULL,
    [AUPOC_PROV_ACQUISIZIONE]            VARCHAR (20)   NULL,
    [AUPOC_OPER_VALIDAZIONE]             VARCHAR (20)   NULL,
    [AUPOC_PROV_VALIDAZIONE]             VARCHAR (20)   NULL,
    [AUPOC_INQ_ESITO_CONTROL]            INT            CONSTRAINT [DF_tb_aupoc_pos_contr_AUPOC_INQ_ESITO_CONTROL] DEFAULT ((0)) NULL,
    [AUPOC_INQ_COD_ERRORE_CONTROL]       INT            CONSTRAINT [DF_tb_aupoc_pos_contr_AUPOC_INQ_COD_ERRORE_CONTROL] DEFAULT ((0)) NULL,
    [AUPOC_INQ_DESCR_ERRORE]             VARCHAR (100)  NULL,
    [AUPOC_INQ_DATA_PRIMO_CONTROL]       DATETIME       NULL,
    [AUPOC_INQ_DATA_ULTIMO_CONTROL]      DATETIME       NULL,
    [AUPOC_INQ_ESITO_VERIFICA_OPER]      INT            CONSTRAINT [DF_tb_aupoc_pos_contr_AUPOC_INQ_ESITO_VERIFICA_OPER] DEFAULT ((0)) NULL,
    [AUPOC_INQ_DATA_ESITO_VERIFICA_OPER] DATETIME       NULL,
    [AUPOC_INQ_COD_OPER]                 VARCHAR (20)   NULL,
    [AUPOC_INQ_NOTE]                     VARCHAR (200)  NULL,
    [aupoc_data_cessazione_LD]           DATE           NULL,
    [aupoc_navale]                       CHAR (1)       CONSTRAINT [DF_tb_aupoc_pos_contr_aupoc_navale] DEFAULT ('N') NULL,
    [aupoc_data_validazione]             DATETIME       NULL,
    [aupoc_data_iscrizione_provvisoria]  DATETIME       NULL,
    CONSTRAINT [PK_tb_aupoc] PRIMARY KEY CLUSTERED ([aupoc_codice_pk] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [UQ_aupoc_aupoc] UNIQUE NONCLUSTERED ([aupoc_codice_pk] ASC) WITH (FILLFACTOR = 90)
);

