CREATE TABLE [dbo].[TB_ANTRL_TIPRUOLOPG_CT] (
    [ANTRL_COD_TIPRUOLOPG_PK]     VARCHAR (3)  NOT NULL,
    [ANTRL_DESCR_TIPRUOLOPG]      VARCHAR (60) NOT NULL,
    [ANTRL_DATA_INIZ]             DATE         NOT NULL,
    [ANTRL_DATA_FINE]             DATE         CONSTRAINT [DF_TB_ANTRL_TIPRUOLOPG_CT_ANTRL_DATA_FINE] DEFAULT (CONVERT([date],'9999-12-31')) NOT NULL,
    [ANTRL_FLAG_DCUTENTE]         VARCHAR (1)  CONSTRAINT [DF_TB_ANTRL_TIPRUOLOPG_CT_ANTRL_FLAG_DCUTENTE] DEFAULT ('N') NOT NULL,
    [ANTRL_FLAG_ESPOSIZ]          VARCHAR (1)  CONSTRAINT [DF_TB_ANTRL_TIPRUOLOPG_CT_ANTRL_FLAG_ESPOSIZ] DEFAULT ('S') NOT NULL,
    [ANTRL_COD_UTENTE]            VARCHAR (16) NOT NULL,
    [ANTRL_DATA_AGGIORN]          DATE         NOT NULL,
    [ANTRL_COD_APPL]              VARCHAR (2)  NOT NULL,
    [ANTRL_FLAG_SEDEUTENTE]       VARCHAR (1)  CONSTRAINT [DF_TB_ANTRL_TIPRUOLOPG_CT_ANTRL_FLAG_SEDEUTENTE] DEFAULT ('N') NOT NULL,
    [ANTRL_AUC_CODICE_PK]         BIGINT       IDENTITY (1, 1) NOT NULL,
    [ANTRL_AUC_DATA_INSERIMENTO]  DATETIME     CONSTRAINT [DF_TB_ANTRL_TIPRUOLOPG_CT_ANTRL_AUC_DATA_INSERIMENTO] DEFAULT (getdate()) NULL,
    [ANTRL_AUC_STATO_LAVORAZIONE] INT          CONSTRAINT [DF_TB_ANTRL_TIPRUOLOPG_CT_ANTRL_AUC_STATO_LAVORAZIONE] DEFAULT ((0)) NULL,
    [ANTRL_AUC_PRESENTE]          INT          CONSTRAINT [DF_TB_ANTRL_TIPRUOLOPG_CT_ANTRL_AUC_PRESENTE] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_ANTRL_TIPRUOLOPG] PRIMARY KEY CLUSTERED ([ANTRL_COD_TIPRUOLOPG_PK] ASC),
    CONSTRAINT [CK1_ANTRL_FLAG_DCUTENTE_DOM] CHECK ([ANTRL_FLAG_DCUTENTE]='N' OR [ANTRL_FLAG_DCUTENTE]='S'),
    CONSTRAINT [CK2_ANTRL_FLAG_SEDEUTENTE_DOM] CHECK ([ANTRL_FLAG_SEDEUTENTE]='N' OR [ANTRL_FLAG_SEDEUTENTE]='S')
);

