CREATE TABLE [dbo].[tb_ausca_sog_contr_az] (
    [ausca_codice_pk]                      INT           IDENTITY (1, 1) NOT NULL,
    [ausca_contro_codice]                  VARCHAR (2)   NULL,
    [ausca_denominazione]                  VARCHAR (405) NULL,
    [ausca_cognome]                        VARCHAR (255) NULL,
    [ausca_nome]                           VARCHAR (150) NULL,
    [ausca_codice_fiscale]                 VARCHAR (16)  NOT NULL,
    [ausca_aungi_codice_pk]                INT           NULL,
    [ausca_codice_qualita_ind]             VARCHAR (1)   NULL,
    [ausca_cciaa]                          VARCHAR (2)   NULL,
    [ausca_codice_toponimo]                VARCHAR (3)   NULL,
    [ausca_toponimo]                       VARCHAR (50)  NULL,
    [ausca_indirizzo]                      VARCHAR (255) NULL,
    [ausca_civico]                         VARCHAR (50)  NULL,
    [ausca_sede_legale_italia]             CHAR (1)      NULL,
    [ausca_frazione]                       VARCHAR (100) NULL,
    [ausca_localita]                       VARCHAR (50)  NULL,
    [ausca_codice_comune_istat]            VARCHAR (6)   NULL,
    [ausca_codice_comune]                  VARCHAR (4)   NULL,
    [ausca_descr_comune]                   VARCHAR (30)  NULL,
    [ausca_sigla_provincia]                VARCHAR (2)   NULL,
    [ausca_regione]                        VARCHAR (25)  NULL,
    [ausca_codice_stato_estero]            VARCHAR (4)   NULL,
    [ausca_cap]                            VARCHAR (10)  NULL,
    [ausca_telefono1]                      VARCHAR (20)  NULL,
    [ausca_telefono2]                      VARCHAR (20)  NULL,
    [ausca_telefono3]                      VARCHAR (20)  NULL,
    [ausca_fax]                            VARCHAR (20)  NULL,
    [ausca_telex]                          VARCHAR (20)  NULL,
    [ausca_email]                          VARCHAR (162) NULL,
    [ausca_PEC]                            VARCHAR (162) NULL,
    [ausca_legalmail]                      VARCHAR (162) NULL,
    [ausca_auate_codice_pk]                INT           NULL,
    [ausca_soggetto_certificato]           CHAR (1)      CONSTRAINT [DF_tb_ausca_sog_contr_az_ausca_soggetto_certificato] DEFAULT ('N') NULL,
    [ausca_data_variazione_stato]          DATETIME      NULL,
    [ausca_auten_codice_pk]                INT           NULL,
    [ausca_codice_entita_rif]              INT           NULL,
    [ausca_note]                           VARCHAR (50)  NULL,
    [ausca_n_rea]                          VARCHAR (20)  NULL,
    [ausca_n_rea_visura]                   VARCHAR (20)  NULL,
    [ausca_data_inizio_attivita]           DATETIME      NULL,
    [ausca_data_fine_attivita]             DATETIME      NULL,
    [ausca_DesATECO]                       VARCHAR (200) NULL,
    [ausca_ATECO]                          VARCHAR (20)  NULL,
    [ausca_auate_1991_codice_pk]           INT           NULL,
    [ausca_auate_2002_codice_pk]           INT           NULL,
    [ausca_auate_2007_codice_pk]           INT           NULL,
    [ausca_denom_lingua_alt]               VARCHAR (405) NULL,
    [ausca_attivita_lingua_alt]            VARCHAR (100) NULL,
    [ausca_data_modifica]                  DATETIME      NULL,
    [ausca_descr_utente]                   VARCHAR (50)  NULL,
    [ausca_codice_pk_db2]                  INT           NULL,
    [ausca_piva]                           VARCHAR (11)  NULL,
    [ausca_cert_auten_cod_pk]              INT           NULL,
    [ausca_cert_cod_entita_rif]            INT           NULL,
    [ausca_cert_data_modifica]             DATETIME      NULL,
    [ausca_data_del]                       DATETIME      NULL,
    [ausca_rec_del]                        VARCHAR (1)   NULL,
    [ausca_codice_gestione]                INT           NULL,
    [ausca_data_iscrizione]                DATETIME      NULL,
    [ausca_descr_stato_infocamere]         VARCHAR (100) NULL,
    [ausca_codice_stato_infocamere]        VARCHAR (5)   NULL,
    [ausca_Stato]                          VARCHAR (50)  NULL,
    [ausca_codice_gruppo_enpals]           VARCHAR (10)  NULL,
    [ausca_data_certificazione_gs]         DATETIME      NULL,
    [ausca_provenienza_cert_gs]            VARCHAR (5)   NULL,
    [ausca_cod_assoc_AC]                   VARCHAR (5)   NULL,
    [ausca_nome_assoc_AC]                  VARCHAR (100) NULL,
    [ausca_data_inizio_AC]                 DATETIME      NULL,
    [ausca_data_fine_AC]                   DATETIME      NULL,
    [ausca_coop_data_presentazione]        DATE          NULL,
    [ausca_coop_num_iscrizione]            VARCHAR (10)  NULL,
    [ausca_coop_data_iscrizione]           DATE          NULL,
    [ausca_coop_cod_sezione]               VARCHAR (10)  NULL,
    [ausca_coop_sezione]                   VARCHAR (200) NULL,
    [ausca_coop_cod_sottosezione]          VARCHAR (10)  NULL,
    [ausca_coop_sottosezione]              VARCHAR (200) NULL,
    [ausca_coop_cod_categoria]             VARCHAR (10)  NULL,
    [ausca_coop_categoria]                 VARCHAR (200) NULL,
    [ausca_coop_cod_categoria_attiv_eserc] VARCHAR (10)  NULL,
    [ausca_coop_categoria_attiv_eserc]     VARCHAR (200) NULL,
    [ausca_art_categoria]                  VARCHAR (2)   NULL,
    [ausca_art_descr_categoria]            VARCHAR (50)  NULL,
    [ausca_art_num_iscrizione_ruolo]       VARCHAR (20)  NULL,
    [ausca_art_provincia_iscrizione_ruolo] VARCHAR (20)  NULL,
    [ausca_art_data_accertamento]          DATE          NULL,
    [ausca_art_data_domanda]               DATE          NULL,
    [ausca_art_data_domanda_accertamento]  DATE          NULL,
    [ausca_art_data_iscrizione]            DATE          NULL,
    [ausca_art_data_delibera]              DATE          NULL,
    [ausca_art_data_iscrizione_inizio]     DATE          NULL,
    [ausca_art_data_inizio]                DATE          NULL,
    [ausca_art_info_suppl]                 VARCHAR (200) NULL,
    [ausca_art_causale_cess]               VARCHAR (2)   NULL,
    [ausca_art_descr_causale_cess]         VARCHAR (100) NULL,
    [ausca_art_data_domanda_accert_cess]   DATE          NULL,
    [ausca_art_data_delibera_cess]         DATE          NULL,
    [ausca_art_data_cessazione]            DATE          NULL,
    [ausca_art_data_descrizione_attivita]  VARCHAR (200) NULL,
    [Ausca_art_descrizione_iscr_ri]        VARCHAR (200) NULL,
    [Ausca_art_data_iscrizione_ri]         DATETIME      NULL,
    [Ausca_art_attesa_decisione_ri]        VARCHAR (1)   NULL,
    [ausca_pec_sin]                        VARCHAR (162) NULL,
    [ausca_bdso_id_va_inpdap]              BIGINT        NULL,
    [ausca_armatore]                       CHAR (1)      CONSTRAINT [DF_tb_ausca_sog_contr_az_ausca_armatore] DEFAULT ('N') NULL,
    [ausca_descrizione_01]                 VARCHAR (100) NULL,
    [ausca_descrizione_02]                 VARCHAR (100) NULL,
    [ausca_descrizione_03]                 VARCHAR (100) NULL,
    [ausca_n_iscrizione_ri]                VARCHAR (21)  NULL,
    [ausca_c_fonte]                        VARCHAR (2)   NULL,
    [ausca_f_aggiornamento]                VARCHAR (1)   NULL,
    [ausca_dt_annotazione]                 DATE          NULL,
    [ausca_dt_iscrizione_rea]              DATE          NULL,
    [ausca_dt_iscrizione_ri]               DATE          NULL,
    [ausca_codice_iscrizione_01]           VARCHAR (3)   NULL,
    [ausca_dt_iscrizione_sezione_01]       DATE          NULL,
    [ausca_f_colt_diretto_01]              VARCHAR (1)   NULL,
    [ausca_codice_iscrizione_02]           VARCHAR (3)   NULL,
    [ausca_dt_iscrizione_sezione_02]       DATE          NULL,
    [ausca_f_colt_diretto_02]              VARCHAR (1)   NULL,
    [ausca_codice_iscrizione_03]           VARCHAR (3)   NULL,
    [ausca_dt_iscrizione_sezione_03]       DATE          NULL,
    [ausca_f_colt_diretto_03]              VARCHAR (1)   NULL,
    [ausca_c_stato]                        VARCHAR (1)   NULL,
    [ausca_dt_inizio_attivita_impresa]     DATE          NULL,
    [ausca_dt_cessazione_canc]             DATE          NULL,
    [ausca_dt_domanda_canc]                DATE          NULL,
    [ausca_dt_canc_canc]                   DATE          NULL,
    [ausca_codice_tipo_trasferimento]      VARCHAR (1)   NULL,
    [ausca_dt_cessazione_trasferimento]    DATE          NULL,
    [ausca_codice_causale_trasferimento]   VARCHAR (2)   NULL,
    [ausca_dt_cessazione_att_canc]         DATE          NULL,
    [ausca_causale_cancellazione]          VARCHAR (100) NULL,
    [ausca_c_causale_canc]                 VARCHAR (2)   NULL,
    [ausca_RA_impresa_autonoma]            VARCHAR (1)   CONSTRAINT [DF__tb_ausca___ausca__7DE6B1EE] DEFAULT ('N') NULL,
    [ausca_RA_impresa_associata]           VARCHAR (1)   CONSTRAINT [DF__tb_ausca___ausca__7EDAD627] DEFAULT ('N') NULL,
    [ausca_RA_impresa_collegata]           VARCHAR (1)   CONSTRAINT [DF__tb_ausca___ausca__7FCEFA60] DEFAULT ('N') NULL,
    [ausca_RA_data_fine_esercizio]         DATE          CONSTRAINT [DF__tb_ausca___ausca__00C31E99] DEFAULT (NULL) NULL,
    [ausca_RA_dimensione_aziendale]        VARCHAR (2)   CONSTRAINT [DF__tb_ausca___ausca__01B742D2] DEFAULT (NULL) NULL,
    [ausca_RA_codice_operatore]            VARCHAR (20)  NULL,
    [ausca_RA_codice_fiscale_delegato]     VARCHAR (16)  NULL,
    [Ausca_RA_data_modifica]               DATETIME      NULL,
    [ausca_comune_esteso_ita]              VARCHAR (60)  NULL,
    [ausca_comune_esteso_ted]              VARCHAR (60)  NULL,
    [ausca_cod_com_ISTAT]                  VARCHAR (6)   NULL,
    [ausca_cod_com_Belfiore]               VARCHAR (4)   NULL,
    [ausca_c_n_iscrizione_ri_old]          VARCHAR (21)  NULL,
    [ausca_stato_impresa]                  VARCHAR (50)  NULL,
    [ausca_attivita_esercitata]            VARCHAR (500) NULL,
    [ausca_attivita_secondaria_esercitata] VARCHAR (500) NULL,
    [ausca_fonte_validazione_anagrafica]   VARCHAR (2)   NULL,
    [ausca_data_validazione_anagrafica]    DATETIME      NULL,
    [ausca_motivo_scarto]                  VARCHAR (2)   NULL,
    [ausca_data_scarto]                    DATETIME      NULL,
    [ausca_data_esito_pdd]                 DATETIME      NULL,
    [ausca_esito_pdd]                      VARCHAR (10)  NULL,
    [ausca_cod_regione_ISTAT]              VARCHAR (2)   NULL,
    [ausca_regione_Agenda_Sedi]            VARCHAR (2)   NULL,
    [ausca_regione_inps]                   VARCHAR (2)   NULL,
    [ausca_PEC_IVA]                        VARCHAR (162) NULL,
    [ausca_pec_IPA]                        VARCHAR (162) NULL,
    CONSTRAINT [PK_tb_ausca] PRIMARY KEY CLUSTERED ([ausca_codice_pk] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_ausca_auate] FOREIGN KEY ([ausca_auate_codice_pk]) REFERENCES [dbo].[tb_auate_cod_ateco_ct] ([auate_codice_pk]),
    CONSTRAINT [FK_ausca_aungi] FOREIGN KEY ([ausca_aungi_codice_pk]) REFERENCES [dbo].[tb_aungi_nat_giur_ct] ([aungi_codice_pk]),
    CONSTRAINT [FK_ausca_auten] FOREIGN KEY ([ausca_auten_codice_pk]) REFERENCES [dbo].[tb_auten_tipo_entita_ct] ([auten_codice_pk]),
    CONSTRAINT [UQ_ausca_ausca] UNIQUE NONCLUSTERED ([ausca_codice_pk] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [UQ_ausca_CF] UNIQUE NONCLUSTERED ([ausca_codice_fiscale] ASC) WITH (FILLFACTOR = 90)
);

