CREATE TABLE [dbo].[tb_ausrs_storico_rel_sog] (
    [ausrs_codice_pk]                 BIGINT        IDENTITY (1, 1) NOT NULL,
    [ausrs_aurss_codice_pk]           BIGINT        NULL,
    [ausrs_ausca_codice_pk]           INT           NULL,
    [ausrs_ausco_codice_pk]           INT           NULL,
    [ausrs_aussu_codice_pk]           INT           NULL,
    [ausrs_autis_codice_pk]           INT           NULL,
    [ausrs_data_inizio_validita]      DATETIME      NULL,
    [ausrs_data_di_fine_validita]     DATETIME      NULL,
    [ausrs_data_iscr_libro_soci]      DATETIME      NULL,
    [ausrs_data_atto_di_nomina]       DATETIME      NULL,
    [ausrs_data_nomina]               DATETIME      NULL,
    [ausrs_data_fine_carica]          DATETIME      NULL,
    [ausrs_note]                      VARCHAR (200) NULL,
    [ausrs_rappresentante_legale]     VARCHAR (1)   NULL,
    [ausrs_data_modifica]             DATETIME      NULL,
    [ausrs_descr_utente]              VARCHAR (50)  NULL,
    [ausrs_codice_pk_db2]             BIGINT        NULL,
    [ausrs_relazione_certificata]     CHAR (1)      NULL,
    [ausrs_cert_auten_cod_pk]         INT           NULL,
    [ausrs_cert_cod_entita_rif]       INT           NULL,
    [ausrs_cert_data_modifica]        DATETIME      NULL,
    [ausrs_indice_qualita_relazione]  INT           NULL,
    [ausrs_auten_codice_pk]           INT           NULL,
    [ausrs_codice_entita_rif]         INT           NULL,
    [ausrs_codice_carica]             VARCHAR (4)   NULL,
    [ausrs_provenienza]               VARCHAR (30)  NULL,
    [ausrs_data_iscrizione]           DATETIME      NULL,
    [ausrs_flag_chiusura]             SMALLINT      NULL,
    [ausrs_cap_agire]                 VARCHAR (2)   NULL,
    [ausrs_flag_se_elettore]          VARCHAR (1)   NULL,
    [ausrs_potere_firma]              VARCHAR (1)   NULL,
    [ausrs_quote_partec]              VARCHAR (15)  NULL,
    [ausrs_perce_partec]              VARCHAR (4)   NULL,
    [ausrs_quote_partec_e]            VARCHAR (17)  NULL,
    [ausrs_quota_c_valuta]            VARCHAR (3)   NULL,
    [ausrs_cod_durata_carica]         VARCHAR (2)   NULL,
    [ausrs_anni_ese_carica]           VARCHAR (2)   NULL,
    [ausrs_data_pres_carica]          VARCHAR (8)   NULL,
    [ausrs_prog_pers]                 VARCHAR (4)   NULL,
    [ausrs_progressivo_carica]        VARCHAR (4)   NULL,
    [ausrs_causa_storicizzazione]     CHAR (1)      NULL,
    [ausrs_utente_storicizzazione]    VARCHAR (50)  NULL,
    [ausrs_data_storicizzazione]      DATETIME      NULL,
    [ausrs_motivo_storicizzazione]    VARCHAR (200) NULL,
    [ausrs_data_inizio_validita_new]  DATETIME      NULL,
    [ausrs_data_di_fine_validita_new] DATETIME      NULL,
    CONSTRAINT [PK_tb_ausrs] PRIMARY KEY CLUSTERED ([ausrs_codice_pk] ASC),
    CONSTRAINT [UQ_ausrs_ausrs] UNIQUE NONCLUSTERED ([ausrs_codice_pk] ASC)
);

