CREATE TABLE [dbo].[TB_ANTCO_TCONTATT_CT] (
    [ANTCO_COD_TCONTATT_PK]    VARCHAR (3)   NOT NULL,
    [ANTCO_DESCR_TIPOCONTATTO] VARCHAR (100) NOT NULL,
    [ANTCO_DATA_INIZ]          DATE          NOT NULL,
    [ANTCO_DATA_FINE]          DATE          CONSTRAINT [DF_TB_ANTCO_TCONTATT_CT_ANTCO_DATA_FINE] DEFAULT (CONVERT([date],'9999-12-31')) NOT NULL,
    [ANTCO_FLAG_ESPOSIZ]       VARCHAR (1)   CONSTRAINT [DF_TB_ANTCO_TCONTATT_CT_ANTCO_FLAG_ESPOSIZ] DEFAULT ('S') NOT NULL,
    [ANTCO_NUM_ORDINAM]        BIGINT        CONSTRAINT [DF_TB_ANTCO_TCONTATT_CT_ANTCO_NUM_ORDINAM] DEFAULT ('0') NOT NULL,
    [ANTCO_COD_UTENTE]         VARCHAR (16)  NOT NULL,
    [ANTCO_DATA_AGGIORN]       DATE          CONSTRAINT [DF_TB_ANTCO_TCONTATT_CT_ANTCO_DATA_AGGIORN] DEFAULT (getdate()) NOT NULL,
    [ANTCO_COD_APPL]           VARCHAR (2)   NOT NULL,
    CONSTRAINT [PK_ANTCO_TCONTATT] PRIMARY KEY CLUSTERED ([ANTCO_COD_TCONTATT_PK] ASC),
    CONSTRAINT [CK1_ANTCO_FLAG_ESPOSIZ] CHECK ([ANTCO_FLAG_ESPOSIZ]='S' OR [ANTCO_FLAG_ESPOSIZ]='N'),
    CONSTRAINT [CK2_ANTCO_DATE_INIZ_FINE] CHECK ([ANTCO_DATA_FINE]>=[ANTCO_DATA_INIZ])
);

