CREATE TABLE [dbo].[tb_aupin_posizioni_enpals] (
    [AUPIN_CODICE_PK]            INT           IDENTITY (1, 1) NOT NULL,
    [aupin_codice_fiscale]       VARCHAR (16)  NULL,
    [aupin_denominazione]        VARCHAR (405) NULL,
    [aupin_toponimo]             VARCHAR (50)  NULL,
    [aupin_indirizzo]            VARCHAR (255) NULL,
    [aupin_civico]               VARCHAR (50)  NULL,
    [aupin_cap]                  VARCHAR (5)   NULL,
    [aupin_comune]               VARCHAR (30)  NULL,
    [aupin_belf_com]             VARCHAR (5)   NULL,
    [aupin_sigla_prov]           VARCHAR (2)   NULL,
    [aupin_frazione]             VARCHAR (100) NULL,
    [aupin_localita]             VARCHAR (50)  NULL,
    [aupin_posizione]            VARCHAR (50)  NULL,
    [aupin_progressivo]          VARCHAR (50)  NULL,
    [aupin_cod_categoria]        VARCHAR (10)  NULL,
    [aupin_data_inizio_attivita] DATETIME      NULL,
    [aupin_stato]                VARCHAR (20)  NULL,
    [aupin_data_var_stato]       DATETIME      NULL,
    [aupin_ateco]                VARCHAR (7)   NULL,
    [aupin_codice_sede_inps]     VARCHAR (10)  NULL,
    [aupin_tipo_rapporto]        VARCHAR (30)  NULL,
    [AUPIN_DATA_MODIFICA]        DATETIME      CONSTRAINT [DF_tb_aupin_posizioni_enpals_AUPIN_DATA_MODIFICA] DEFAULT (getdate()) NULL,
    [AUPIN_STATO_LAVORAZIONE]    INT           CONSTRAINT [DF_tb_aupin_posizioni_enpals_AUPIN_STATO_LAVORAZIONE] DEFAULT ((0)) NULL,
    [AUPIN_CODICE_LOTTO]         INT           CONSTRAINT [DF_tb_aupin_posizioni_enpals_AUPIN_CODICE_LOTTO] DEFAULT ((0)) NULL,
    [AUPIN_FLAG_AUSCA]           VARCHAR (1)   CONSTRAINT [DF_tb_aupin_posizioni_enpals_AUPIN_FLAG_AUSCA] DEFAULT ('N') NULL,
    [AUPIN_FLAG_AUPOC]           VARCHAR (1)   CONSTRAINT [DF_tb_aupin_posizioni_enpals_AUPIN_FLAG_AUPOC] DEFAULT ('N') NULL,
    [AUPIN_CODICE_AUSCA]         INT           CONSTRAINT [DF_tb_aupin_posizioni_enpals_AUPIN_CODICE_AUSCA] DEFAULT ((0)) NULL,
    [AUPIN_CODICE_AUPOC]         INT           CONSTRAINT [DF_tb_aupin_posizioni_enpals_AUPIN_CODICE_AUPOC] DEFAULT ((0)) NULL,
    [AUPIN_AUSIN_CODICE_PK]      INT           NULL,
    [AUPIN_AUCAT_CODICE_PK]      INT           NULL,
    [AUPIN_TIPO_POSIZIONE]       INT           CONSTRAINT [DF_tb_aupin_posizioni_enpals_AUPIN_TIPO_POSIZIONE] DEFAULT ((0)) NULL,
    [AUPIN_TS]                   VARCHAR (1)   NULL,
    [AUPIN_IND_QUALITA_INDIR]    INT           CONSTRAINT [DF_tb_aupin_posizioni_enpals_AUPIN_IND_QUALITA_INDIR] DEFAULT ((0)) NULL
);

