CREATE TABLE [dbo].[tb_ausrd_storico_rl_DMAG] (
    [ausrd_codice_pk]              BIGINT        IDENTITY (1, 1) NOT NULL,
    [ausrd_aurss_codice_pk]        BIGINT        NULL,
    [ausrd_ausca_codice_pk]        INT           NULL,
    [ausrd_ausco_codice_pk]        INT           NULL,
    [ausrd_aussu_codice_pk]        INT           NULL,
    [ausrd_autis_codice_pk]        INT           NULL,
    [ausrd_data_inizio_validita]   DATETIME      NULL,
    [ausrd_data_di_fine_validita]  DATETIME      NULL,
    [ausrd_note]                   VARCHAR (200) NULL,
    [ausrd_rappresentante_legale]  VARCHAR (1)   NULL,
    [ausrd_data_modifica]          DATETIME      NULL,
    [ausrd_descr_utente]           VARCHAR (50)  NULL,
    [ausrd_relazione_certificata]  CHAR (1)      NULL,
    [ausrd_cert_auten_cod_pk]      INT           NULL,
    [ausrd_cert_cod_entita_rif]    INT           NULL,
    [ausrd_cert_data_modifica]     DATETIME      NULL,
    [ausrd_auten_codice_pk]        INT           NULL,
    [ausrd_codice_entita_rif]      INT           NULL,
    [ausrd_codice_carica]          VARCHAR (4)   NULL,
    [ausrd_provenienza]            VARCHAR (30)  NULL,
    [ausrd_causa_storicizzazione]  CHAR (1)      NULL,
    [ausrd_utente_storicizzazione] VARCHAR (50)  NULL,
    [ausrd_data_storicizzazione]   DATETIME      NULL,
    [ausrd_motivo_storicizzazione] VARCHAR (200) NULL,
    CONSTRAINT [PK_tb_ausrd] PRIMARY KEY CLUSTERED ([ausrd_codice_pk] ASC),
    CONSTRAINT [UQ_ausrd_ausrd] UNIQUE NONCLUSTERED ([ausrd_codice_pk] ASC)
);

