CREATE TABLE [dbo].[tb_ausco_sog_contr_col_storico] (
    [ausco_codice_pk]                INT           NULL,
    [ausco_codice_fiscale]           VARCHAR (16)  NULL,
    [ausco_denominazione]            VARCHAR (405) NULL,
    [ausco_cognome]                  VARCHAR (255) NULL,
    [ausco_nome]                     VARCHAR (150) NULL,
    [ausco_sesso]                    VARCHAR (1)   NULL,
    [ausco_cittadinanza]             VARCHAR (4)   NULL,
    [ausco_comune_nascita]           VARCHAR (50)  NULL,
    [ausco_data_nascita]             DATETIME      NULL,
    [ausco_prov_nascita]             VARCHAR (2)   NULL,
    [ausco_stato_estero_nascita]     VARCHAR (4)   NULL,
    [ausco_tipo_persona]             VARCHAR (1)   NULL,
    [ausco_codice_qualita_ind]       VARCHAR (1)   NULL,
    [ausco_codice_toponimo]          VARCHAR (3)   NULL,
    [ausco_toponimo]                 VARCHAR (100) NULL,
    [ausco_frazione]                 VARCHAR (100) NULL,
    [ausco_localita]                 VARCHAR (50)  NULL,
    [ausco_indirizzo]                VARCHAR (100) NULL,
    [ausco_civico]                   VARCHAR (50)  NULL,
    [ausco_cap]                      VARCHAR (5)   NULL,
    [ausco_codice_comune_istat]      VARCHAR (6)   NULL,
    [ausco_codice_comune]            VARCHAR (4)   NULL,
    [ausco_provincia]                VARCHAR (2)   NULL,
    [ausco_sigla_nazione]            VARCHAR (10)  NULL,
    [ausco_codice_stato_estero]      VARCHAR (4)   NULL,
    [ausco_telefono]                 VARCHAR (20)  NULL,
    [ausco_telefono2]                VARCHAR (20)  NULL,
    [ausco_fax]                      VARCHAR (20)  NULL,
    [ausco_email]                    VARCHAR (162) NULL,
    [ausco_pec]                      VARCHAR (162) NULL,
    [ausco_legalmail]                VARCHAR (162) NULL,
    [ausco_note]                     VARCHAR (200) NULL,
    [ausco_data_modifica]            DATETIME      NULL,
    [ausco_descr_utente]             VARCHAR (50)  NULL,
    [ausco_codice_pk_db2]            INT           NULL,
    [ausco_cert_auten_cod_pk]        INT           NULL,
    [ausco_cert_cod_entita_rif]      INT           NULL,
    [ausco_cert_data_modifica]       DATETIME      NULL,
    [ausco_codice_comune_nasc]       VARCHAR (4)   NULL,
    [ausco_descr_cittadinanza]       VARCHAR (50)  NULL,
    [ausco_descr_stato_nascita]      VARCHAR (100) NULL,
    [ausco_certificato_arca]         CHAR (1)      NULL,
    [ausco_data_agg_arca]            DATETIME      NULL,
    [ausco_data_morte]               DATETIME      NULL,
    [ausco_ind_qualita_indir]        INT           NULL,
    [ausco_aurea_codice_pk]          INT           NULL,
    [ausco_data_inizio_AC]           DATETIME      NULL,
    [ausco_data_fine_AC]             DATETIME      NULL,
    [ausco_rec_del]                  VARCHAR (1)   NULL,
    [ausco_data_del]                 DATETIME      NULL,
    [ausco_residenza_frazione]       VARCHAR (25)  NULL,
    [ausco_residenza_altre_indic]    VARCHAR (30)  NULL,
    [ausco_codice_comune_nascita]    VARCHAR (5)   NULL,
    [ausco_residenza_codice_comune]  VARCHAR (5)   NULL,
    [ausco_residenza_codice_stato]   VARCHAR (3)   NULL,
    [ausco_cf_arca]                  VARCHAR (16)  NULL,
    [ausco_chiave_arca]              INT           NULL,
    [ausco_cod_comune_belf]          VARCHAR (4)   NULL,
    [ausco_codice_stato_estero_nasc] VARCHAR (4)   NULL,
    [ausco_certificato_AT]           CHAR (1)      NULL,
    [ausco_data_agg_AT]              DATETIME      NULL,
    [ausco_richiesta_verifica_arca]  CHAR (1)      NULL,
    [ausco_data_richiesta_arca]      DATETIME      NULL,
    [ausco_utente_richiesta_arca]    VARCHAR (50)  NULL,
    [ausco_stato_lavorazione_arca]   VARCHAR (10)  NULL,
    [ausco_data_lavorazione_arca]    DATETIME      NULL,
    [Ausco_CfCcc1_Ev0_ARCA]          VARCHAR (3)   NULL,
    [Ausco_Progr_Ev0_ARCA]           INT           NULL,
    [ausco_esito_lavorazione_arca]   VARCHAR (10)  NULL
);

