CREATE TABLE [dbo].[TB_ANRPG_RUOLIPG_CL] (
    [ANRPG_BDSO_ID_VA_PK]           BIGINT       NOT NULL,
    [ANRPG_ANTRL_COD_TIPRUOLOPG_PK] VARCHAR (3)  NOT NULL,
    [ANRPG_DATA_INIZ_PK]            DATE         NOT NULL,
    [ANRPG_DATA_FINE]               DATE         CONSTRAINT [DF_TB_ANRPG_RUOLIPG_CL_ANRPG_DATA_FINE] DEFAULT (CONVERT([date],'9999-12-31')) NOT NULL,
    [ANRPG_COD_UTENTE]              VARCHAR (16) NOT NULL,
    [ANRPG_DATA_AGGIORN]            DATE         CONSTRAINT [DF_TB_ANRPG_RUOLIPG_CL_ANRPG_DATA_AGGIORN] DEFAULT (getdate()) NOT NULL,
    [ANRPG_COD_APPL]                VARCHAR (2)  NOT NULL,
    [ANRPG_DATA_SISTEMA]            DATETIME     NOT NULL,
    [ANRPG_ANMCR_COD_MOTCHIRUPG]    VARCHAR (1)  CONSTRAINT [DF_TB_ANRPG_RUOLIPG_CL_ANRPG_ANMCR_COD_MOTCHIRUPG] DEFAULT ('N') NOT NULL,
    [ANRPG_AUC_CODICE_PK]           BIGINT       IDENTITY (1, 1) NOT NULL,
    [ANRPG_AUC_DATA_INSERIMENTO]    DATETIME     CONSTRAINT [DF_TB_ANRPG_RUOLIPG_CL_ANRPG_AUC_DATA_INSERIMENTO] DEFAULT (getdate()) NULL,
    [ANRPG_AUC_STATO_LAVORAZIONE]   INT          CONSTRAINT [DF_TB_ANRPG_RUOLIPG_CL_ANRPG_AUC_STATO_LAVORAZIONE] DEFAULT ((0)) NULL,
    [ANRPG_AUC_CF_PK]               VARCHAR (16) NULL,
    [ANRPG_AUC_AUSCA_PK]            INT          CONSTRAINT [DF_TB_ANRPG_RUOLIPG_CL_ANRPG_AUC_AUSCA_PK] DEFAULT ((0)) NULL,
    [ANRPG_AUC_PRESENTE]            INT          CONSTRAINT [DF_TB_ANRPG_RUOLIPG_CL_ANRPG_AUC_PRESENTE] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_ANRPG_RUOLIPG] PRIMARY KEY CLUSTERED ([ANRPG_BDSO_ID_VA_PK] ASC, [ANRPG_ANTRL_COD_TIPRUOLOPG_PK] ASC, [ANRPG_DATA_INIZ_PK] ASC),
    CONSTRAINT [CK1_ANMCR_COD_MOTCHIRUPG_DOM] CHECK ([ANRPG_ANMCR_COD_MOTCHIRUPG]='N' OR [ANRPG_ANMCR_COD_MOTCHIRUPG]='S'),
    CONSTRAINT [FK1_ANRPG_BDSO] FOREIGN KEY ([ANRPG_BDSO_ID_VA_PK]) REFERENCES [dbo].[BDSO_SOCIETA_CL] ([BDSO_ID_VA]),
    CONSTRAINT [FK2_ANRPG_ANTRL] FOREIGN KEY ([ANRPG_ANTRL_COD_TIPRUOLOPG_PK]) REFERENCES [dbo].[TB_ANTRL_TIPRUOLOPG_CT] ([ANTRL_COD_TIPRUOLOPG_PK])
);

