CREATE TABLE [dbo].[TB_AUT08_OSIRIDE_TR08] (
    [AUT08_R8_TIPO]                CHAR (2)    NULL,
    [AUT08_R8_PROV_CCIAA]          CHAR (2)    NULL,
    [AUT08_R8_NUM_IREA]            CHAR (9)    NULL,
    [AUT08_R8_COD_LIQUI]           CHAR (2)    NULL,
    [AUT08_R8_DATA_LIQ_APER]       CHAR (8)    NULL,
    [AUT08_R8_DATA_LIQ_FINE]       CHAR (8)    NULL,
    [AUT08_R8_DATA_LIQ_REVO]       CHAR (8)    NULL,
    [AUT08_R8_DATA_LIQ_CHIU]       CHAR (8)    NULL,
    [AUT08_R8_COD_ATTO]            CHAR (2)    NULL,
    [AUT08_R8IND_ESEC_ATTO]        CHAR (1)    NULL,
    [AUT08_R8_DESCR_NOTAIO]        CHAR (40)   NULL,
    [AUT08_R8_DESCR_TRIBUNALE]     CHAR (40)   NULL,
    [AUT08_R8_DESCR_ALTERNATIVA]   CHAR (40)   NULL,
    [AUT08_R8_NUM_REGIST_ATTO]     CHAR (15)   NULL,
    [AUT08_R8_DATA_REGIST_ATTO]    CHAR (8)    NULL,
    [AUT08_R8_LOC_REGIST_ATTO]     CHAR (30)   NULL,
    [AUT08_R8_PR_REGIST_ATTO]      CHAR (2)    NULL,
    [AUT08_R8_DATA_ESECU_CON_PREV] CHAR (8)    NULL,
    [AUT08_R8_FILLER]              CHAR (1268) NULL,
    [AUT08_R8_FILLER100]           CHAR (100)  NULL,
    [aut08_r8_codice_fiscale]      CHAR (16)   NULL
);

