CREATE TABLE [dbo].[TB_AUIAC_INTERFACCIA_ARCA_COLLEGATO] (
    [AUIAC_CODICE_PK]                BIGINT       IDENTITY (1, 1) NOT NULL,
    [AUIAC_CHIAVE_AUC]               INT          NULL,
    [AUIAC_CODICE_FISCALE_COLLEGATO] VARCHAR (16) NULL,
    [AUIAC_DATA_INSERIMENTO]         DATETIME     CONSTRAINT [DF_TB_AUIAC_INTERFACCIA_ARCA_COLLEGATO_AUIAC_DATA_INSERIMENTO] DEFAULT (getdate()) NULL,
    [AUIAC_Attuale_Collegato]        INT          NULL,
    CONSTRAINT [PK_tb_auiac] PRIMARY KEY CLUSTERED ([AUIAC_CODICE_PK] ASC),
    CONSTRAINT [UQ_auiac_auiac] UNIQUE NONCLUSTERED ([AUIAC_CODICE_PK] ASC)
);

