CREATE TABLE [dbo].[TB_AULDF_PERSONA_FISICA_LD] (
    [AULDF_CODICE_PK]                 INT         IDENTITY (1, 1) NOT NULL,
    [auldf_codice_fiscale]            NCHAR (16)  NULL,
    [auldf_cognome]                   NCHAR (255) NULL,
    [auldf_nome]                      NCHAR (150) NULL,
    [auldf_data_nascita]              DATETIME    NULL,
    [auldf_sesso]                     NCHAR (2)   NULL,
    [auldf_comune_nascita]            NCHAR (100) NULL,
    [auldf_prov_nascita]              NCHAR (50)  NULL,
    [auldf_cap]                       NCHAR (5)   NULL,
    [auldf_comune]                    NCHAR (100) NULL,
    [auldf_sigla_provincia]           NCHAR (50)  NULL,
    [auldf_indirizzo_residenza_input] NCHAR (255) NULL,
    [auldf_pec]                       NCHAR (160) NULL,
    [auldf_email]                     NCHAR (160) NULL,
    [auldf_telefono]                  NCHAR (20)  NULL,
    [auldf_toponimo]                  NCHAR (50)  NULL,
    [auldf_codice_toponimo]           NCHAR (3)   NULL,
    [auldf_indirizzo]                 NCHAR (255) NULL,
    [auldf_civico]                    NCHAR (50)  NULL,
    [auldf_indice_qualita_indirizzo]  INT         CONSTRAINT [DF_TB_AULDF_PERSONA_FISICA_LD_indice_qualita_indirizzo] DEFAULT ((0)) NULL,
    [auldf_data_inserimento]          DATETIME    NULL,
    [auldf_sequenza_inserimento]      INT         NULL,
    [AULDF_VALIDATO_AUSCA]            INT         CONSTRAINT [DF_TB_AULDF_PERSONA_FISICA_LD_AULDF_VALIDATO_AUSCA] DEFAULT ((0)) NULL,
    [AULDF_VALIDATO_AUSCO]            INT         CONSTRAINT [DF_TB_AULDF_PERSONA_FISICA_LD_AULDF_VALIDATO_AUSCO] DEFAULT ((0)) NULL,
    [AULDF_VALIDATO_AURSS]            INT         CONSTRAINT [DF_TB_AULDF_PERSONA_FISICA_LD_AULDF_VALIDATO_AURSS] DEFAULT ((0)) NULL,
    [AULDF_FLAG_AUSCA]                NCHAR (1)   CONSTRAINT [DF_TB_AULDF_PERSONA_FISICA_LD_AULDF_FLAG_AUSCA] DEFAULT ('N') NULL,
    [AULDF_FLAG_AUSCO]                NCHAR (1)   CONSTRAINT [DF_TB_AULDF_PERSONA_FISICA_LD_AULDF_FLAG_AUSCO] DEFAULT ('N') NULL,
    [AULDF_FLAG_AURSS]                NCHAR (1)   CONSTRAINT [DF_TB_AULDF_PERSONA_FISICA_LD_AULDF_FLAG_AURSS] DEFAULT ('N') NULL,
    [AULDF_DATA_MODIFICA]             DATETIME    CONSTRAINT [DF_TB_AULDF_PERSONA_FISICA_LD_AULDF_DATA_MODIFICA] DEFAULT (getdate()) NULL,
    [AULDF_STATO_LAVORAZIONE]         INT         CONSTRAINT [DF_TB_AULDF_PERSONA_FISICA_LD_AULDF_STATO_LAVORAZIONE] DEFAULT ((0)) NULL,
    [AULDF_CODICE_LOTTO]              INT         CONSTRAINT [DF_TB_AULDF_PERSONA_FISICA_LD_AULDF_CODICE_LOTTO] DEFAULT ((0)) NULL,
    [AULDF_CODICE_AUSCA]              INT         CONSTRAINT [DF_TB_AULDF_PERSONA_FISICA_LD_AULDF_CODICE_AUSCA] DEFAULT ((0)) NULL,
    [AULDF_CODICE_AUSCO]              INT         CONSTRAINT [DF_TB_AULDF_PERSONA_FISICA_LD_AULDF_CODICE_AUSCO] DEFAULT ((0)) NULL,
    [AULDF_CODICE_AURSS]              INT         CONSTRAINT [DF_TB_AULDF_PERSONA_FISICA_LD_AULDF_CODICE_AURSS] DEFAULT ((0)) NULL
);

