CREATE TABLE [dbo].[tb_aussc_storico_sog_contr] (
    [aussc_codice_pk]              INT           IDENTITY (1, 1) NOT NULL,
    [aussc_ausca_codice_pk]        INT           NULL,
    [aussc_denominazione]          VARCHAR (405) NULL,
    [aussc_cognome]                VARCHAR (255) NULL,
    [aussc_nome]                   VARCHAR (150) NULL,
    [aussc_codice_fiscale]         VARCHAR (16)  NOT NULL,
    [aussc_aungi_codice_pk]        INT           NULL,
    [aussc_codice_qualita_ind]     VARCHAR (1)   NULL,
    [aussc_cciaa]                  VARCHAR (2)   NULL,
    [aussc_codice_toponimo]        VARCHAR (3)   NULL,
    [aussc_toponimo]               VARCHAR (50)  NULL,
    [aussc_indirizzo]              VARCHAR (255) NULL,
    [aussc_civico]                 VARCHAR (50)  NULL,
    [aussc_sede_legale_italia]     CHAR (1)      NULL,
    [aussc_frazione]               VARCHAR (100) NULL,
    [aussc_localita]               VARCHAR (50)  NULL,
    [aussc_codice_comune_istat]    VARCHAR (6)   NULL,
    [aussc_codice_comune]          VARCHAR (4)   NULL,
    [aussc_descr_comune]           VARCHAR (30)  NULL,
    [aussc_sigla_provincia]        VARCHAR (2)   NULL,
    [aussc_codice_stato_estero]    VARCHAR (4)   NULL,
    [aussc_cap]                    VARCHAR (10)  NULL,
    [aussc_telefono1]              VARCHAR (20)  NULL,
    [aussc_telefono2]              VARCHAR (20)  NULL,
    [aussc_telefono3]              VARCHAR (20)  NULL,
    [aussc_fax]                    VARCHAR (20)  NULL,
    [aussc_telex]                  VARCHAR (20)  NULL,
    [aussc_email]                  VARCHAR (162) NULL,
    [aussc_PEC]                    VARCHAR (162) NULL,
    [aussc_legalmail]              VARCHAR (162) NULL,
    [aussc_auate_codice_pk]        INT           NULL,
    [aussc_soggetto_certificato]   CHAR (1)      NULL,
    [aussc_auten_codice_pk]        INT           NULL,
    [aussc_codice_entita_rif]      INT           NULL,
    [aussc_note]                   VARCHAR (50)  NULL,
    [aussc_n_rea]                  VARCHAR (20)  NULL,
    [aussc_DesATECO]               VARCHAR (200) NULL,
    [aussc_ATECO]                  VARCHAR (20)  NULL,
    [aussc_data_modifica]          DATETIME      NULL,
    [aussc_descr_utente]           VARCHAR (50)  NULL,
    [aussc_codice_pk_db2]          INT           NULL,
    [aussc_piva]                   VARCHAR (11)  NULL,
    [aussc_cert_auten_cod_pk]      INT           NULL,
    [aussc_cert_cod_entita_rif]    INT           NULL,
    [aussc_cert_data_modifica]     DATETIME      NULL,
    [aussc_codice_gestione]        INT           NULL,
    [aussc_data_iscrizione]        DATETIME      NULL,
    [aussc_codice_gruppo_enpals]   VARCHAR (10)  NULL,
    [aussc_provenienza_cert_gs]    VARCHAR (5)   NULL,
    [aussc_data_certificazione_gs] DATETIME      NULL,
    [aussc_Stato]                  VARCHAR (50)  NULL,
    [aussc_aurea_codice_pk]        INT           NULL,
    [auscc_data_inizio_attivita]   DATETIME      NULL,
    [auscc_data_fine_attivita]     DATETIME      NULL,
    CONSTRAINT [PK_tb_aussc] PRIMARY KEY CLUSTERED ([aussc_codice_pk] ASC),
    CONSTRAINT [UQ_aussc_aussc] UNIQUE NONCLUSTERED ([aussc_codice_pk] ASC)
);

