CREATE TABLE [dbo].[tb_aurin_relazioni_indirizzi] (
    [aurin_codice_pk]           BIGINT        IDENTITY (1, 1) NOT NULL,
    [aurin_lingua]              VARCHAR (10)  NULL,
    [aurin_ausca_codice_pk]     BIGINT        NULL,
    [aurin_ausco_codice_pk]     BIGINT        NULL,
    [aurin_auten_codice_pk]     INT           NULL,
    [aurin_codice_entita_rif]   INT           NULL,
    [aurin_sede_indirizzo]      VARCHAR (1)   NULL,
    [aurin_codice_toponimo]     VARCHAR (3)   NULL,
    [aurin_toponimo]            VARCHAR (50)  NULL,
    [aurin_indirizzo]           VARCHAR (255) NULL,
    [aurin_civico]              VARCHAR (50)  NULL,
    [aurin_localita]            VARCHAR (50)  NULL,
    [aurin_frazione]            VARCHAR (100) NULL,
    [aurin_codice_comune]       VARCHAR (5)   NULL,
    [aurin_codice_comune_istat] VARCHAR (6)   NULL,
    [aurin_descr_comune]        VARCHAR (50)  NULL,
    [aurin_sigla_provincia]     VARCHAR (2)   NULL,
    [aurin_cap]                 VARCHAR (10)  NULL,
    [aurin_codice_stato_estero] VARCHAR (5)   NULL,
    [aurin_descr_stato_estero]  VARCHAR (50)  NULL,
    [aurin_telefono1]           VARCHAR (20)  NULL,
    [aurin_telefono2]           VARCHAR (20)  NULL,
    [aurin_telefono3]           VARCHAR (20)  NULL,
    [aurin_fax]                 VARCHAR (20)  NULL,
    [aurin_email]               VARCHAR (162) NULL,
    [aurin_pec]                 VARCHAR (162) NULL,
    [aurin_gestore_indirizzo]   VARCHAR (10)  NULL,
    [aurin_stato_indirizzo]     VARCHAR (10)  NULL,
    [aurin_codice_qualita_ind]  VARCHAR (1)   NULL,
    [aurin_flag_operativo]      INT           NULL,
    [aurin_data_modifica]       DATETIME      NULL,
    [aurin_descr_utente]        VARCHAR (50)  NULL,
    [aurin_codice_pk_db2]       BIGINT        NULL,
    [aurin_rec_del]             VARCHAR (1)   NULL,
    [aurin_data_del]            DATETIME      NULL,
    [aurin_aurea_codice_pk]     INT           NULL,
    CONSTRAINT [PK_tb_aurin] PRIMARY KEY CLUSTERED ([aurin_codice_pk] ASC),
    CONSTRAINT [UQ_aurin_aurin] UNIQUE NONCLUSTERED ([aurin_codice_pk] ASC)
);

