CREATE TABLE [dbo].[tb_aupoe_PosizioniErrate_Aupoc] (
    [aupoc_contro_codice]                VARCHAR (2)    NULL,
    [aupoc_ausca_codice_pk]              INT            NULL,
    [aupoc_auapp_codice_pk]              INT            NULL,
    [aupoc_auspc_codice_pk]              INT            NULL,
    [aupoc_autia_codice_pk]              INT            NULL,
    [aupoc_posizione]                    VARCHAR (50)   NULL,
    [aupoc_sede_provinciale]             INT            NULL,
    [aupoc_matricola_azienda]            INT            NULL,
    [aupoc_controcod_matr_az]            INT            NULL,
    [aupoc_sede_zonale]                  VARCHAR (2)    NULL,
    [aupoc_data_inizio_attivita]         DATETIME2 (3)  NULL,
    [aupoc_denom_posiz_contr]            VARCHAR (405)  NULL,
    [aupoc_note]                         VARCHAR (2000) NULL,
    [aupoc_data_domanda_iscr]            DATETIME2 (3)  NULL,
    [aupoc_provenienza_iscr]             VARCHAR (1)    NULL,
    [aupoc_cod_sede_INPS]                VARCHAR (6)    NULL,
    [aupoc_cod_agenzia]                  VARCHAR (6)    NULL,
    [aupoc_utente_acquisizione]          VARCHAR (8)    NULL,
    [aupoc_utente_validazione]           VARCHAR (8)    NULL,
    [aupoc_attivita_dichiarata]          VARCHAR (80)   NULL,
    [aupoc_flag_operativo]               INT            NULL,
    [aupoc_data_modifica]                DATETIME2 (3)  NULL,
    [aupoc_descr_utente]                 VARCHAR (50)   NULL,
    [aupoc_ateco]                        VARCHAR (20)   NULL,
    [aupoc_auate_1991_codice_pk]         INT            NULL,
    [aupoc_auate_2002_codice_pk]         INT            NULL,
    [aupoc_auate_2007_codice_pk]         INT            NULL,
    [aupoc_desATECO]                     VARCHAR (200)  NULL,
    [aupoc_ausin_codice_pk]              INT            NULL,
    [aupoc_aurea_codice_pk]              INT            NULL,
    [aupoc_tipo_posizione]               INT            NULL,
    [aupoc_data_ultimo_stato]            DATETIME2 (3)  NULL,
    [ausca_codice_fiscale]               VARCHAR (16)   NOT NULL,
    [aupoc_codice_pk]                    INT            NULL,
    [aupoc_navale]                       CHAR (1)       NULL,
    [AUPOC_INQ_ESITO_CONTROL]            INT            NULL,
    [AUPOC_INQ_COD_ERRORE_CONTROL]       INT            NULL,
    [AUPOC_INQ_DESCR_ERRORE]             VARCHAR (100)  NULL,
    [AUPOC_INQ_DATA_PRIMO_CONTROL]       DATETIME       NULL,
    [AUPOC_INQ_DATA_ULTIMO_CONTROL]      DATETIME       NULL,
    [AUPOC_INQ_ESITO_VERIFICA_OPER]      INT            NULL,
    [AUPOC_INQ_DATA_ESITO_VERIFICA_OPER] DATETIME       NULL,
    [AUPOC_INQ_COD_OPER]                 VARCHAR (20)   NULL,
    [AUPOC_INQ_NOTE]                     VARCHAR (200)  NULL
);

