CREATE TABLE [dbo].[TB_AULDR_RAPPORTI_LD] (
    [AULDR_CODICE_PK]                 INT           IDENTITY (1, 1) NOT NULL,
    [auldr_progressivo_rapporto]      VARCHAR (20)  NULL,
    [auldr_chiave_gestionale_Datore]  VARCHAR (20)  NULL,
    [auldr_codice_fiscale]            NCHAR (16)    NULL,
    [auldr_data_presentazione]        DATETIME      NULL,
    [auldr_data_assunzione]           DATETIME      NULL,
    [auldr_data_cessazione]           DATETIME      NULL,
    [auldr_stato_pratica]             VARCHAR (50)  NULL,
    [auldr_descr_stato_pratica]       VARCHAR (200) NULL,
    [auldr_sede_inps]                 VARCHAR (50)  NULL,
    [auldr_cap]                       NCHAR (5)     NULL,
    [auldr_comune]                    VARCHAR (100) NULL,
    [auldr_sigla_provincia]           VARCHAR (50)  NULL,
    [auldr_indirizzo_input]           VARCHAR (255) NULL,
    [auldr_codice_fiscale_lavoratore] NCHAR (16)    NULL,
    [auldr_toponimo]                  NCHAR (50)    NULL,
    [auldr_codice_toponimo]           NCHAR (3)     NULL,
    [auldr_indirizzo]                 NCHAR (255)   NULL,
    [auldr_civico]                    NCHAR (50)    NULL,
    [auldr_indice_qualita_indirizzo]  INT           CONSTRAINT [DF_TB_AULDR_RAPPORTI_LD_auldr_indice_qualita_indirizzo] DEFAULT ((0)) NULL,
    [auldr_ausin]                     INT           CONSTRAINT [DF_TB_AULDR_RAPPORTI_LD_auldr_ausin] DEFAULT ((0)) NULL,
    [auldr_stato_posizione]           INT           CONSTRAINT [DF_TB_AULDR_RAPPORTI_LD_auldr_stato_posizione] DEFAULT ((0)) NULL,
    [auldr_data_inserimento]          DATETIME      NULL,
    [auldr_sequenza_inserimento]      INT           NULL,
    [auldr_denominazione]             NCHAR (200)   NULL,
    [AULDR_VALIDATO_AUSCA]            INT           CONSTRAINT [DF_TB_AULDR_RAPPORTI_LD_AULDR_VALIDATO_AUSCA] DEFAULT ((0)) NULL,
    [AULDR_VALIDATO_AUPOC]            INT           CONSTRAINT [DF_TB_AULDR_RAPPORTI_LD_AULDR_VALIDATO_AUPOC] DEFAULT ((0)) NULL,
    [AULDR_FLAG_AUSCA]                NCHAR (1)     CONSTRAINT [DF_TB_AULDR_RAPPORTI_LD_AULDR_FLAG_AUSCA] DEFAULT ('N') NULL,
    [AULDR_FLAG_AUPOC]                NCHAR (1)     CONSTRAINT [DF_TB_AULDR_RAPPORTI_LD_AULDR_FLAG_AUPOC] DEFAULT ('N') NULL,
    [AULDR_DATA_MODIFICA]             DATETIME      CONSTRAINT [DF_TB_AULDR_RAPPORTI_LD_AULDR_DATA_MODIFICA] DEFAULT (getdate()) NULL,
    [AULDR_STATO_LAVORAZIONE]         INT           CONSTRAINT [DF_TB_AULDR_RAPPORTI_LD_AULDR_STATO_LAVORAZIONE] DEFAULT ((0)) NULL,
    [AULDR_CODICE_LOTTO]              INT           CONSTRAINT [DF_TB_AULDR_RAPPORTI_LD_AULDR_CODICE_LOTTO] DEFAULT ((0)) NULL,
    [AULDR_CODICE_AUSCA]              INT           CONSTRAINT [DF_TB_AULDR_RAPPORTI_LD_AULDR_CODICE_AUSCA] DEFAULT ((0)) NULL,
    [AULDR_CODICE_AUPOC]              INT           CONSTRAINT [DF_TB_AULDR_RAPPORTI_LD_AULDR_CODICE_AUPOC] DEFAULT ((0)) NULL,
    [auldr_data_decorrenza_stato]     DATETIME      NULL,
    [AULDR_FLAG_AUVAS]                INT           CONSTRAINT [DF_TB_AULDR_RAPPORTI_LD_AULDR_FLAG_AUVAS] DEFAULT ((0)) NULL
);

