CREATE TABLE [dbo].[tb_auind_indirizzi] (
    [auind_codice_pk]           BIGINT        IDENTITY (1, 1) NOT NULL,
    [auind_lingua]              VARCHAR (10)  NULL,
    [auind_tabella]             VARCHAR (5)   NULL,
    [auind_tabella_codice_pk]   BIGINT        NULL,
    [auind_sede_indirizzo]      VARCHAR (1)   NULL,
    [auind_codice_toponimo]     VARCHAR (3)   NULL,
    [auind_toponimo]            VARCHAR (50)  NULL,
    [auind_indirizzo]           VARCHAR (255) NULL,
    [auind_civico]              VARCHAR (50)  NULL,
    [auind_localita]            VARCHAR (50)  NULL,
    [auind_frazione]            VARCHAR (100) NULL,
    [auind_codice_comune]       VARCHAR (5)   NULL,
    [auind_codice_comune_istat] VARCHAR (6)   NULL,
    [auind_descr_comune]        VARCHAR (50)  NULL,
    [auind_sigla_provincia]     VARCHAR (2)   NULL,
    [auind_cap]                 VARCHAR (10)  NULL,
    [auind_codice_stato_estero] VARCHAR (5)   NULL,
    [auind_descr_stato_estero]  VARCHAR (50)  NULL,
    [auind_telefono1]           VARCHAR (20)  NULL,
    [auind_telefono2]           VARCHAR (20)  NULL,
    [auind_telefono3]           VARCHAR (20)  NULL,
    [auind_fax]                 VARCHAR (20)  NULL,
    [auind_email]               VARCHAR (162) NULL,
    [auind_pec]                 VARCHAR (162) NULL,
    [auind_chiave_interna]      VARCHAR (50)  NULL,
    [auind_chiave_esterna]      VARCHAR (50)  NULL,
    [auind_gestore_indirizzo]   VARCHAR (10)  NULL,
    [auind_stato_indirizzo]     VARCHAR (10)  NULL,
    [auind_codice_qualita_ind]  VARCHAR (1)   NULL,
    [auind_flag_operativo]      INT           NULL,
    [auind_data_modifica]       DATETIME      NULL,
    [auind_descr_utente]        VARCHAR (50)  NULL,
    [auind_codice_pk_db2]       BIGINT        NULL,
    [auind_rec_del]             VARCHAR (1)   NULL,
    [auind_data_del]            DATETIME      NULL,
    [auind_aurea_codice_pk]     INT           NULL,
    CONSTRAINT [PK_tb_auind] PRIMARY KEY CLUSTERED ([auind_codice_pk] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [UQ_auind_auind] UNIQUE NONCLUSTERED ([auind_codice_pk] ASC) WITH (FILLFACTOR = 90)
);

