CREATE TABLE [dbo].[TB_AUQDA_QTA_DATI_AGGIORNABILI] (
    [AUQDA_CODICE_PK]         BIGINT      IDENTITY (1, 1) NOT NULL,
    [AUQDA_TIPO]              INT         NULL,
    [AUQDA_PROVENIENZA]       VARCHAR (5) NULL,
    [AUQDA_DATA_RIFERIMENTO]  DATETIME    NULL,
    [AUQDA_LOTTO]             INT         NULL,
    [AUQDA_STATO_RECORD]      CHAR (1)    NULL,
    [AUQDA_QUANTITA]          INT         NULL,
    [AUQDA_DATA_CREAZIONE]    DATETIME    CONSTRAINT [DF_TB_AUQDA_QTA_DATI_AGGIORNABILI_AUQDA_DATA_CREAZIONE] DEFAULT (getdate()) NULL,
    [AUQDA_FONTE_VALIDAZIONE] VARCHAR (2) NULL,
    [AUQDA_MOTIVO_SCARTO]     VARCHAR (2) NULL,
    CONSTRAINT [PK_tb_auQDA] PRIMARY KEY CLUSTERED ([AUQDA_CODICE_PK] ASC),
    CONSTRAINT [UQ_auQDA_auQDA] UNIQUE NONCLUSTERED ([AUQDA_CODICE_PK] ASC)
);

