CREATE TABLE [dbo].[TB_ANPGO_PGOPER_CL] (
    [ANPGO_ANOPG_SEQ_OPERAZPG_PK] BIGINT       NOT NULL,
    [ANPGO_BDSO_ID_VA_PK]         BIGINT       NOT NULL,
    [ANPGO_FLAG_TIPOPG]           VARCHAR (1)  NOT NULL,
    [ANPGO_COD_UTENTE]            VARCHAR (16) NOT NULL,
    [ANPGO_DATA_AGGIORN]          DATE         NOT NULL,
    [ANPGO_COD_APPL]              VARCHAR (2)  NOT NULL,
    [ANPGO_DATA_SISTEMA]          DATETIME     NULL,
    [ANPGO_AUC_CODICE_PK]         BIGINT       IDENTITY (1, 1) NOT NULL,
    [ANPGO_AUC_DATA_INSERIMENTO]  DATETIME     CONSTRAINT [DF_TB_ANPGO_PGOPER_CL_ANPGO_AUC_DATA_INSERIMENTO] DEFAULT (getdate()) NULL,
    [ANPGO_AUC_STATO_LAVORAZIONE] INT          CONSTRAINT [DF_TB_ANPGO_PGOPER_CL_ANPGO_AUC_STATO_LAVORAZIONE] DEFAULT ((0)) NULL,
    [ANPGO_AUC_CF_PK]             VARCHAR (16) NULL,
    [ANPGO_AUC_AUSCA_PK]          INT          NULL,
    [ANPGO_AUC_PRESENTE]          INT          CONSTRAINT [DF_TB_ANPGO_PGOPER_CL_ANPGO_AUC_PRESENTE] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_ANPGO_PGOPER] PRIMARY KEY CLUSTERED ([ANPGO_ANOPG_SEQ_OPERAZPG_PK] ASC, [ANPGO_BDSO_ID_VA_PK] ASC),
    CONSTRAINT [CK1_ANPOG_FLAG_TIPOPG] CHECK ([ANPGO_FLAG_TIPOPG]='A' OR [ANPGO_FLAG_TIPOPG]='P'),
    CONSTRAINT [FK1_ANPGO_ANOPG] FOREIGN KEY ([ANPGO_ANOPG_SEQ_OPERAZPG_PK]) REFERENCES [dbo].[TB_ANOPG_OPERAZPG_CL] ([ANOPG_SEQ_OPERAZPG_PK]),
    CONSTRAINT [FK2_ANPGO_BDSO] FOREIGN KEY ([ANPGO_BDSO_ID_VA_PK]) REFERENCES [dbo].[BDSO_SOCIETA_CL] ([BDSO_ID_VA])
);

