CREATE TABLE [dbo].[tb_DM_Scarti_Import_ausca] (
    [St_ausca_denominazione]            VARCHAR (MAX) NULL,
    [St_ausca_codice_fiscale]           VARCHAR (16)  NULL,
    [St_ausca_indirizzo]                VARCHAR (MAX) NULL,
    [St_ausca_Nome_Via]                 VARCHAR (MAX) NULL,
    [St_ausca_Toponimo]                 VARCHAR (MAX) NULL,
    [St_ausca_civico]                   VARCHAR (MAX) NULL,
    [St_ausca_descr_comune]             VARCHAR (MAX) NULL,
    [St_ausca_sigla_provincia]          VARCHAR (MAX) NULL,
    [St_ausca_cap]                      VARCHAR (MAX) NULL,
    [St_ausca_telefono1]                VARCHAR (MAX) NULL,
    [St_ausca_telefono2]                VARCHAR (MAX) NULL,
    [St_ausca_telefono3]                VARCHAR (MAX) NULL,
    [St_ausca_fax]                      VARCHAR (MAX) NULL,
    [St_ausca_email]                    VARCHAR (MAX) NULL,
    [St_ausca_PEC]                      VARCHAR (MAX) NULL,
    [St_ausca_legalmail]                VARCHAR (MAX) NULL,
    [St_ausca_soggetto_certificato]     VARCHAR (MAX) NULL,
    [St_ausca_note]                     VARCHAR (MAX) NULL,
    [St_ausca_Data_Inizio_Attivita]     VARCHAR (MAX) NULL,
    [St_ausca_Data_Fine_Attivita]       VARCHAR (MAX) NULL,
    [St_ausca_Filename]                 VARCHAR (MAX) NULL,
    [St_ausca_codice_Ateco91]           VARCHAR (MAX) NULL,
    [St_ausca_codice_forma_giuridica]   VARCHAR (MAX) NULL,
    [St_ausca_MatricolaGestioneAziende] VARCHAR (10)  NULL,
    [St_ausca_sede_provinciale]         INT           NULL,
    [St_ausca_matricola_azienda]        INT           NULL,
    [St_ausca_controcod_matr_az]        INT           NULL,
    [St_ausca_stato_posizione]          VARCHAR (MAX) NULL,
    [St_ausca_denominazione_lingua_alt] VARCHAR (MAX) NULL,
    [St_ausca_attivita_lingua_alt]      VARCHAR (MAX) NULL,
    [St_ausca_data_modifica]            VARCHAR (MAX) NULL,
    [St_ausca_descr_utente]             VARCHAR (MAX) NULL,
    [ErrorNum]                          VARCHAR (MAX) NULL,
    [ErrorDescription]                  VARCHAR (MAX) NULL,
    [NoteScartoErrori]                  VARCHAR (MAX) NULL
);

