CREATE TABLE [dbo].[tb_DM_Scarti_Import_ausco] (
    [St_ausco_codice_fiscale]       VARCHAR (16)  NULL,
    [St_ausco_cognome]              VARCHAR (MAX) NULL,
    [St_ausco_nome]                 VARCHAR (MAX) NULL,
    [St_ausco_denominazione]        VARCHAR (MAX) NULL,
    [St_ausco_note]                 VARCHAR (MAX) NULL,
    [St_ausco_FisicaGiuridica]      VARCHAR (MAX) NULL,
    [St_ausco_sesso]                VARCHAR (MAX) NULL,
    [St_ausco_sede_legale_italia]   VARCHAR (MAX) NULL,
    [St_ausco_CodiceFormaGiuridica] VARCHAR (MAX) NULL,
    [St_ausco_data_nascita]         VARCHAR (MAX) NULL,
    [St_ausco_comune_nascita]       VARCHAR (MAX) NULL,
    [St_ausco_prov_nascita]         VARCHAR (MAX) NULL,
    [St_ausco_codice_toponimo]      VARCHAR (MAX) NULL,
    [St_ausco_indirizzo]            VARCHAR (MAX) NULL,
    [St_ausco_civico]               VARCHAR (MAX) NULL,
    [St_ausco_cap]                  VARCHAR (MAX) NULL,
    [St_ausco_descr_comune]         VARCHAR (MAX) NULL,
    [St_ausco_sigla_provincia]      VARCHAR (MAX) NULL,
    [St_ausco_telefono1]            VARCHAR (MAX) NULL,
    [St_ausco_telefono2]            VARCHAR (MAX) NULL,
    [St_ausco_fax]                  VARCHAR (MAX) NULL,
    [St_ausco_PEC]                  VARCHAR (MAX) NULL,
    [St_ausco_email]                VARCHAR (MAX) NULL,
    [St_ausco_legalmail]            VARCHAR (MAX) NULL,
    [St_ausco_data_modifica]        DATETIME      NULL,
    [St_ausco_descr_utente]         VARCHAR (MAX) NULL,
    [ErrorNum]                      VARCHAR (MAX) NULL,
    [ErrorDescription]              VARCHAR (MAX) NULL,
    [NoteScartoErrori]              VARCHAR (MAX) NULL
);

