CREATE TABLE [dbo].[tb_DM_Scarti_Import_audel] (
    [St_audel_codice_fiscale]       VARCHAR (16)  NULL,
    [St_audel_cognome]              VARCHAR (MAX) NULL,
    [St_audel_nome]                 VARCHAR (MAX) NULL,
    [St_audel_denominazione]        VARCHAR (MAX) NULL,
    [St_audel_note]                 VARCHAR (MAX) NULL,
    [St_audel_FisicaGiuridica]      VARCHAR (MAX) NULL,
    [St_audel_sesso]                VARCHAR (MAX) NULL,
    [St_audel_sede_legale_italia]   VARCHAR (MAX) NULL,
    [St_audel_CodiceFormaGiuridica] VARCHAR (MAX) NULL,
    [St_audel_data_nascita]         VARCHAR (MAX) NULL,
    [St_audel_comune_nascita]       VARCHAR (MAX) NULL,
    [St_audel_prov_nascita]         VARCHAR (MAX) NULL,
    [St_audel_codice_toponimo]      VARCHAR (MAX) NULL,
    [St_audel_indirizzo]            VARCHAR (MAX) NULL,
    [St_audel_civico]               VARCHAR (MAX) NULL,
    [St_audel_cap]                  VARCHAR (MAX) NULL,
    [St_audel_descr_comune]         VARCHAR (MAX) NULL,
    [St_audel_sigla_provincia]      VARCHAR (MAX) NULL,
    [St_audel_telefono1]            VARCHAR (MAX) NULL,
    [St_audel_telefono2]            VARCHAR (MAX) NULL,
    [St_audel_fax]                  VARCHAR (MAX) NULL,
    [St_audel_data_modifica]        DATETIME      NULL,
    [St_audel_descr_utente]         VARCHAR (MAX) NULL,
    [ErrorNum]                      VARCHAR (MAX) NULL,
    [ErrorDescription]              VARCHAR (MAX) NULL,
    [NoteScartoErrori]              VARCHAR (MAX) NULL
);

