CREATE TABLE [dbo].[tb_INFO_Scarti_AUSCA] (
    [St_ausca_codice_pk]                  INT            NULL,
    [St_ausca_denominazione]              VARCHAR (405)  NULL,
    [St_ausca_codice_fiscale]             VARCHAR (16)   NULL,
    [St_ausca_cciaa]                      VARCHAR (2)    NULL,
    [St_ausca_aungi_codice_pk]            INT            NULL,
    [St_ausca_indirizzo]                  VARCHAR (255)  NULL,
    [St_ausca_codice_toponimo]            VARCHAR (3)    NULL,
    [St_ausca_Nome_Via]                   VARCHAR (255)  NULL,
    [St_ausca_Toponimo]                   VARCHAR (50)   NULL,
    [St_ausca_civico]                     VARCHAR (50)   NULL,
    [St_ausca_localita]                   VARCHAR (50)   NULL,
    [St_ausca_sede_legale_italia]         VARCHAR (1)    NULL,
    [St_ausca_codice_comune]              VARCHAR (4)    NULL,
    [St_ausca_descr_comune]               VARCHAR (30)   NULL,
    [St_ausca_sigla_provincia]            VARCHAR (2)    NULL,
    [St_ausca_regione]                    VARCHAR (25)   NULL,
    [St_ausca_codice_stato_estero]        VARCHAR (4)    NULL,
    [St_ausca_cap]                        VARCHAR (10)   NULL,
    [St_ausca_CodiceFormaGiuridica]       VARCHAR (50)   NULL,
    [St_ausca_FormaGiuridica]             VARCHAR (100)  NULL,
    [St_ausca_Stato]                      VARCHAR (50)   NULL,
    [St_ausca_telefono1]                  VARCHAR (20)   NULL,
    [St_ausca_telefono2]                  VARCHAR (20)   NULL,
    [St_ausca_telefono3]                  VARCHAR (20)   NULL,
    [St_ausca_fax]                        VARCHAR (20)   NULL,
    [St_ausca_email]                      VARCHAR (162)  NULL,
    [St_ausca_PEC]                        VARCHAR (162)  NULL,
    [St_ausca_auate_codice_pk]            INT            NULL,
    [St_ausca_auate1991_codice_pk]        INT            NULL,
    [St_ausca_auate2002_codice_pk]        INT            NULL,
    [St_ausca_auate2007_codice_pk]        INT            NULL,
    [St_ausca_soggetto_certificato]       CHAR (1)       NULL,
    [St_ausca_data_variazione_stato]      DATE           NULL,
    [St_ausca_auten_codice_pk]            INT            NULL,
    [St_ausca_codice_entita_riferimento]  INT            NULL,
    [St_ausca_note]                       VARCHAR (50)   NULL,
    [St_ausca_ATECO_2002]                 VARCHAR (20)   NULL,
    [St_ausca_ATECO_2007]                 VARCHAR (20)   NULL,
    [St_ausca_DesATECO_2002]              VARCHAR (200)  NULL,
    [St_ausca_DesATECO_2007]              VARCHAR (200)  NULL,
    [St_ausca_Data_Inizio_Attivita]       DATE           NULL,
    [St_ausca_Data_Fine_Attivita]         DATE           NULL,
    [St_ausca_Filename]                   VARCHAR (1000) NULL,
    [St_ausca_data_domandafile]           VARCHAR (200)  NULL,
    [St_ausca_TipologiaFile]              VARCHAR (100)  NULL,
    [St_ausca_MatricolaGestioneAziende]   VARCHAR (10)   NULL,
    [St_ausca_NomeFileVisuraOriginale]    VARCHAR (1000) NULL,
    [St_ausca_NomeOriginale_Prov1]        VARCHAR (50)   NULL,
    [St_ausca_NomeOriginale_Anno]         VARCHAR (10)   NULL,
    [St_ausca_NomeOriginale_Progressivo1] VARCHAR (100)  NULL,
    [St_ausca_NomeOriginale_Visura]       VARCHAR (1000) NULL,
    [St_ausca_NomeOriginale_Prov2]        VARCHAR (50)   NULL,
    [St_ausca_NomeOriginale_NumREA]       VARCHAR (50)   NULL,
    [St_ausca_NumeroREA_Visura]           VARCHAR (20)   NULL,
    [St_ausca_FLAG]                       TINYINT        NULL,
    [St_ausca_PRESENTE]                   CHAR (1)       NULL,
    [St_ausca_data_modifica]              DATETIME       NULL,
    [St_ausca_descr_utente]               VARCHAR (50)   NULL,
    [ErrorNum]                            VARCHAR (MAX)  NULL,
    [ErrorDescription]                    VARCHAR (MAX)  NULL
);

