CREATE TABLE [dbo].[tb_Soggetti_Fisici] (
    [St_codice_fiscale]           VARCHAR (16)  NULL,
    [St_cognome]                  VARCHAR (255) NULL,
    [St_nome]                     VARCHAR (255) NULL,
    [St_denominazione]            VARCHAR (255) NULL,
    [St_note]                     VARCHAR (255) NULL,
    [St_FisicaGiuridica]          VARCHAR (1)   NULL,
    [St_sesso]                    VARCHAR (255) NULL,
    [St_sede_legale_italia]       VARCHAR (255) NULL,
    [St_CodiceFormaGiuridica]     VARCHAR (255) NULL,
    [St_data_nascita]             VARCHAR (255) NULL,
    [St_comune_nascita]           VARCHAR (255) NULL,
    [St_prov_nascita]             VARCHAR (2)   NULL,
    [St_codice_toponimo]          VARCHAR (255) NULL,
    [St_indirizzo]                VARCHAR (255) NULL,
    [St_civico]                   VARCHAR (255) NULL,
    [St_cap]                      VARCHAR (255) NULL,
    [St_descr_comune]             VARCHAR (255) NULL,
    [St_sigla_provincia]          VARCHAR (255) NULL,
    [St_telefono1]                VARCHAR (255) NULL,
    [St_telefono2]                VARCHAR (255) NULL,
    [St_fax]                      VARCHAR (255) NULL,
    [St_data_modifica]            DATETIME      NULL,
    [St_descr_utente]             VARCHAR (255) NULL,
    [St_ausco_Presente]           INT           NULL,
    [st_email]                    VARCHAR (250) NULL,
    [st_PEC]                      VARCHAR (250) NULL,
    [St_ind_qualita_indir]        INT           NULL,
    [ausco_codice_pk]             INT           NULL,
    [St_ausco_codice_comune_nasc] VARCHAR (4)   NULL,
    [St_ausco_sigla_nazione]      VARCHAR (10)  NULL,
    [St_ausco_data_morte]         DATETIME      NULL
);

