CREATE TABLE [dbo].[TI_ANRDM_RUOLIDMA_CL] (
    [ANRDM_BDSO_ID_VA_SER_PK] BIGINT       NULL,
    [ANRDM_BDSO_ID_VA_APP_PK] BIGINT       NULL,
    [ANRDM_BDSO_ID_VA_DIC_PK] BIGINT       NULL,
    [ANRDM_DATA_INIZ_PK]      DATE         NULL,
    [ANRDM_DATA_FINE]         DATE         NULL,
    [ANRDM_COD_UTENTE]        VARCHAR (16) NULL,
    [ANRDM_DATA_AGGIORN]      DATE         NULL,
    [ANRDM_COD_APPL]          VARCHAR (2)  NULL,
    [ANRDM_DESCR_INTERVENTO]  VARCHAR (50) NULL,
    [ANRDM_DATA_SISTEMA]      DATE         NULL,
    [ANRDM_AUC_AUSCA_SER_PK]  INT          NULL,
    [ANRDM_AUC_AUSCA_APP_PK]  INT          NULL,
    [ANRDM_AUC_AUSCA_DIC_PK]  INT          NULL,
    [ANRDM_CODICE_PK]         BIGINT       IDENTITY (1, 1) NOT NULL,
    [ANRDM_DATA_MODIFICA]     DATETIME     NULL,
    [ANRDM_DESCR_UTENTE]      VARCHAR (50) NULL
);

