CREATE TABLE [dbo].[TI_ANTOG_TOPERPG_CT] (
    [ANTOG_COD_TOPERPG_PK] VARCHAR (3)  NULL,
    [ANTOG_DESCR_TOPERPG]  VARCHAR (50) NULL,
    [ANTOG_DATA_INIZ]      DATE         NULL,
    [ANTOG_DATA_FINE]      DATE         NULL,
    [ANTOG_FLAG_ESPOSIZ]   VARCHAR (1)  NULL,
    [ANTOG_NUM_ORDINAM]    INT          NULL,
    [ANTOG_COD_UTENTE]     VARCHAR (16) NULL,
    [ANTOG_DATA_AGGIORN]   DATE         NULL,
    [ANTOG_COD_APPL]       VARCHAR (2)  NULL,
    [ANTOG_CODICE_PK]      BIGINT       IDENTITY (1, 1) NOT NULL,
    [ANTOG_DATA_MODIFICA]  DATETIME     NULL,
    [ANTOG_DESCR_UTENTE]   VARCHAR (50) NULL
);

