CREATE TABLE [dbo].[TI_ANTLP_TIPLEGAMEPG_CT] (
    [ANTLP_COD_TIPLEGAMEPG_PK] VARCHAR (2)   NULL,
    [ANTLP_DESCR_TIPLEGAMEPG]  VARCHAR (60)  NULL,
    [ANTLP_DATA_INIZ]          DATE          NULL,
    [ANTLP_DATA_FINE]          DATE          NULL,
    [ANTLP_FLAG_ESPOSIZ]       VARCHAR (1)   NULL,
    [ANTLP_NOTE_TIPLEGAMEPG]   VARCHAR (255) NULL,
    [ANTLP_COD_UTENTE]         VARCHAR (16)  NULL,
    [ANTLP_DATA_AGGIORN]       DATE          NULL,
    [ANTLP_COD_APPL]           VARCHAR (2)   NULL,
    [ANTLP_CODICE_PK]          BIGINT        IDENTITY (1, 1) NOT NULL,
    [ANTLP_DATA_MODIFICA]      DATETIME      NULL,
    [ANTLP_DESCR_UTENTE]       VARCHAR (50)  NULL
);

