CREATE TABLE [dbo].[TI_ANNGG_NATGIURPG_CL] (
    [ANNGG_BDSO_ID_VA_PK] BIGINT       NULL,
    [ANNGG_DATA_INIZ_PK]  DATE         NULL,
    [ANNGG_DATA_FINE]     DATE         NULL,
    [ANNGG_BDNG_ID_VA]    BIGINT       NULL,
    [ANNGG_COD_UTENTE]    VARCHAR (16) NULL,
    [ANNGG_DATA_AGGIORN]  DATE         NULL,
    [ANNGG_COD_APPL]      VARCHAR (2)  NULL,
    [ANNGG_DATA_SISTEMA]  DATE         NULL,
    [ANNGG_AUC_AUSCA_PK]  INT          NULL,
    [ANNGG_CODICE_PK]     BIGINT       IDENTITY (1, 1) NOT NULL,
    [ANNGG_DATA_MODIFICA] DATETIME     NULL,
    [ANNGG_DESCR_UTENTE]  VARCHAR (50) NULL
);

