CREATE TABLE [dbo].[TI_ANTRL_TIPRUOLOPG_CT] (
    [ANTRL_COD_TIPRUOLOPG_PK] VARCHAR (3)  NULL,
    [ANTRL_DESCR_TIPRUOLOPG]  VARCHAR (60) NULL,
    [ANTRL_DATA_INIZ]         DATE         NULL,
    [ANTRL_DATA_FINE]         DATE         NULL,
    [ANTRL_FLAG_DCUTENTE]     VARCHAR (1)  NULL,
    [ANTRL_FLAG_ESPOSIZ]      VARCHAR (1)  NULL,
    [ANTRL_COD_UTENTE]        VARCHAR (16) NULL,
    [ANTRL_DATA_AGGIORN]      DATE         NULL,
    [ANTRL_COD_APPL]          VARCHAR (2)  NULL,
    [ANTRL_FLAG_SEDEUTENTE]   VARCHAR (1)  NULL,
    [ANTRL_CODICE_PK]         BIGINT       IDENTITY (1, 1) NOT NULL,
    [ANTRL_DATA_MODIFICA]     DATETIME     NULL,
    [ANTRL_DESCR_UTENTE]      VARCHAR (50) NULL
);

