CREATE TABLE [dbo].[TI_BDNG_NATGIUR_CT] (
    [BDNG_ID_VA]           BIGINT       NULL,
    [BDNG_CODICE_VB]       VARCHAR (6)  NULL,
    [BDNG_DESCRIZ_VB]      VARCHAR (60) NULL,
    [BDNG_MODREC_VB]       DATE         NULL,
    [BDNG_NSI_VB]          VARCHAR (1)  NULL,
    [BDNG_BDRG_ERI_VR]     BIGINT       NULL,
    [BDNG_DATAINI_VB]      DATE         NULL,
    [BDNG_DATAFIN_VB]      DATE         NULL,
    [BDNG_FLGOBBL_VB]      VARCHAR (1)  NULL,
    [BDNG_FLAG_DATABLOCPA] VARCHAR (1)  NULL,
    [BDNG_CODICE_PK]       BIGINT       IDENTITY (1, 1) NOT NULL,
    [BDNG_DATA_MODIFICA]   DATETIME     NULL,
    [BDNG_DESCR_UTENTE]    VARCHAR (50) NULL
);

