CREATE TABLE [dbo].[TI_BDTS_TIPOSOC_CT] (
    [BDTS_ID_VA]         BIGINT       NULL,
    [BDTS_CODICE_VB]     VARCHAR (3)  NULL,
    [BDTS_DESCRIZ_VB]    VARCHAR (60) NULL,
    [BDTS_MODREC_VB]     DATE         NULL,
    [BDTS_DATAINI_VB]    DATE         NULL,
    [BDTS_DATAFIN_VB]    DATE         NULL,
    [BDTS_NSI_VB]        VARCHAR (1)  NULL,
    [BDTS_FLGDCE_VB]     VARCHAR (1)  NULL,
    [BDTS_CODICE_PK]     BIGINT       IDENTITY (1, 1) NOT NULL,
    [BDTS_DATA_MODIFICA] DATETIME     NULL,
    [BDTS_DESCR_UTENTE]  VARCHAR (50) NULL
);

