CREATE TABLE [dbo].[TI_BDSD_SEDESOC_CL] (
    [BDSD_ID_VA]         BIGINT       NULL,
    [BDSD_BDSE_APP_VR]   VARCHAR (15) NULL,
    [BDSD_BDSO_EDI_VR]   BIGINT       NULL,
    [BDSD_CODINPS_VB]    VARCHAR (15) NULL,
    [BDSD_DATAFINE_VB]   DATE         NULL,
    [BDSD_DATAINI_VB]    DATE         NULL,
    [BDSD_DESCRIZ_VB]    VARCHAR (60) NULL,
    [BDSD_MODREC_VB]     DATE         NULL,
    [BDSD_UTENTE_VB]     VARCHAR (40) NULL,
    [BDSD_BDST_ERI_VR]   BIGINT       NULL,
    [BDSD_DTVAR_VB]      DATE         NULL,
    [BDSD_AUC_AUSCA_PK]  INT          NULL,
    [BDSD_CODICE_PK]     BIGINT       IDENTITY (1, 1) NOT NULL,
    [BDSD_DATA_MODIFICA] DATETIME     NULL,
    [BDSD_DESCR_UTENTE]  VARCHAR (50) NULL
);

