CREATE TABLE [dbo].[TI_BDRG_RGNATGIU_CT] (
    [BDRG_ID_VA]         BIGINT        NULL,
    [BDRG_CODICE_VB]     VARCHAR (6)   NULL,
    [BDRG_DESCRIZ_VB]    VARCHAR (100) NULL,
    [BDRG_MODREC_VB]     DATE          NULL,
    [BDRG_NSI_VB]        VARCHAR (1)   NULL,
    [BDRG_DATAINI_VB]    DATE          NULL,
    [BDRG_DATAFIN_VB]    DATE          NULL,
    [BDRG_BDTS_ERI_VR]   BIGINT        NULL,
    [BDRG_CODICE_PK]     BIGINT        IDENTITY (1, 1) NOT NULL,
    [BDRG_DATA_MODIFICA] DATETIME      NULL,
    [BDRG_DESCR_UTENTE]  VARCHAR (50)  NULL
);

