CREATE TABLE [dbo].[TI_BDSO_SOCIETA_CL] (
    [BDSO_ID_VA]                     BIGINT        NULL,
    [BDSO_BDNG_EDI_VR]               BIGINT        NULL,
    [BDSO_BDTS_APP_VR]               BIGINT        NULL,
    [BDSO_CODFISC_VB]                VARCHAR (11)  NULL,
    [BDSO_CONTGESC_VB]               VARCHAR (1)   NULL,
    [BDSO_DATAFIN_VB]                DATE          NULL,
    [BDSO_DATAINI_VB]                DATE          NULL,
    [BDSO_DENOM_VB]                  VARCHAR (60)  NULL,
    [BDSO_FLGOPZ_VB]                 VARCHAR (1)   NULL,
    [BDSO_PIVA_VB]                   VARCHAR (11)  NULL,
    [BDSO_TIMELOCK_VB]               DATE          NULL,
    [BDSO_MODREC_VB]                 DATE          NULL,
    [BDSO_CERTIF_VB]                 DATE          NULL,
    [BDSO_PROGRESS_VB]               VARCHAR (5)   NULL,
    [BDSO_IDBDSO_VR]                 BIGINT        NULL,
    [BDSO_BDST_ERI_VR]               BIGINT        NULL,
    [BDSO_UTENTE_VB]                 VARCHAR (40)  NULL,
    [BDSO_DTVAR_VB]                  DATE          NULL,
    [BDSO_BDSO_REC_VR]               BIGINT        NULL,
    [BDSO_FLSOSIMP_VB]               VARCHAR (1)   NULL,
    [BDSO_FLAPPART_VB]               VARCHAR (1)   NULL,
    [BDSO_FLSEDSER_VB]               VARCHAR (1)   NULL,
    [BDSO_FLVERSAN_VB]               VARCHAR (1)   NULL,
    [BDSO_DTFCOMPE_VB]               DATE          NULL,
    [BDSO_ANATE_APP_VR]              VARCHAR (5)   NULL,
    [BDSO_ANFGI_APP_VR]              VARCHAR (3)   NULL,
    [BDSO_CERTISCR_VB]               DATE          NULL,
    [BDSO_MAINIDMA_VB]               VARCHAR (6)   NULL,
    [BDSO_CODINPS_VB]                VARCHAR (15)  NULL,
    [BDSO_DENOMB_VB]                 VARCHAR (44)  NULL,
    [BDSO_FLGECCOMP_VB]              VARCHAR (1)   NULL,
    [BDSO_BDSO_VIG_VR]               BIGINT        NULL,
    [BDSO_FLGERR_VB]                 VARCHAR (1)   NULL,
    [BDSO_MAFINDMA_VB]               VARCHAR (6)   NULL,
    [BDSO_ANTLI_COD_TIPLIQUID]       VARCHAR (2)   NULL,
    [BDSO_DATA_LIQUID]               DATE          NULL,
    [BDSO_DATA_BLOCCOPA]             DATE          NULL,
    [BDSO_DATA_INIZGESCEN]           DATE          NULL,
    [BDSO_DATA_FINEGESCEN]           DATE          NULL,
    [BDSO_TOPONIMO]                  VARCHAR (100) NULL,
    [BDSO_COMPLEMENTO]               VARCHAR (200) NULL,
    [BDSO_DESCRIZIONE]               VARCHAR (200) NULL,
    [BDSO_CIVICO]                    VARCHAR (100) NULL,
    [BDSO_FRAZIONE]                  VARCHAR (100) NULL,
    [BDSO_LOCALITA]                  VARCHAR (100) NULL,
    [BDSO_CAP]                       VARCHAR (50)  NULL,
    [BDSO_SIGLA_PROVINCIA]           VARCHAR (100) NULL,
    [BDSO_CODICE_STRUT_INPDAP]       VARCHAR (20)  NULL,
    [BDSO_CODICE_STRUT_INPS]         VARCHAR (20)  NULL,
    [BDSO_AUC_AUSCA_PK]              INT           NULL,
    [BDSO_POSIZIONE]                 VARCHAR (50)  NULL,
    [BDSO_AUC_PRESENTE_AUPOC]        INT           NULL,
    [BDSO_AUC_AUPOC_PK]              INT           NULL,
    [BDSO_CODICE_PK]                 BIGINT        IDENTITY (1, 1) NOT NULL,
    [BDSO_DATA_MODIFICA]             DATETIME      NULL,
    [BDSO_DESCR_UTENTE]              VARCHAR (50)  NULL,
    [BDSO_AUC_STATO_POSIZIONE]       INT           NULL,
    [BDSO_AUC_AUSIN_CODICE_PK]       INT           NULL,
    [BDSO_AUC_CF_CONFLUITO]          VARCHAR (16)  NULL,
    [BDSO_AUC_PROGRESSIVO_CONFLUITO] VARCHAR (5)   NULL,
    [BDSO_AUC_PEC]                   VARCHAR (162) NULL,
    [BDSO_AUC_FORMAG]                VARCHAR (50)  NULL,
    [BDSO_AUC_NATURAG]               VARCHAR (50)  NULL,
    [BDSO_AUC_AUNGI]                 INT           NULL
);

