CREATE TABLE [dbo].[TINTERR_STAGING] (
    [A3CODPRO] DECIMAL (2) NULL,
    [A3MATAZI] DECIMAL (6) NULL,
    [A3CTRCOD] DECIMAL (2) NULL,
    [A3INIINT] DECIMAL (8) NULL,
    [A3FININT] DECIMAL (8) NULL
);

