CREATE PROCEDURE [dbo].[SP_Osiride_TR08_2_Output] @CodFisc VARCHAR(16)
AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [dbo].[TB_AUT99_OSIRIDE_OUT]

	SELECT 
		ISNULL (AUT08_R8_TIPO,SPACE(2))
		+ISNULL(AUT08_R8_PROV_CCIAA,SPACE(2)) 
		+ISNULL(AUT08_R8_NUM_IREA,SPACE(9)) 
--      +ISNULL(AUT08_R8_CODICE_FISCALE,SPACE(16)) 
		+ISNULL(AUT08_R8_COD_LIQUI,SPACE(2)) 
		+ISNULL(AUT08_R8_DATA_LIQ_APER,SPACE(8)) 
		+ISNULL(AUT08_R8_DATA_LIQ_FINE,SPACE(8)) 
		+ISNULL(AUT08_R8_DATA_LIQ_REVO,SPACE(8)) 
		+ISNULL(AUT08_R8_DATA_LIQ_CHIU,SPACE(8))	
		+ISNULL(AUT08_R8_COD_ATTO,SPACE(2))		
 		+ISNULL(AUT08_R8IND_ESEC_ATTO,SPACE(1))
 		+ISNULL(AUT08_R8_DESCR_NOTAIO,SPACE(40))	
 		+ISNULL(AUT08_R8_DESCR_TRIBUNALE,SPACE(40))
 		+ISNULL(AUT08_R8_DESCR_ALTERNATIVA,SPACE(40)) 
 		+ISNULL(AUT08_R8_NUM_REGIST_ATTO,SPACE(15))
 		+ISNULL(AUT08_R8_DATA_REGIST_ATTO,SPACE(8))
 		+ISNULL(AUT08_R8_LOC_REGIST_ATTO,SPACE(30))
 		+ISNULL(AUT08_R8_PR_REGIST_ATTO,SPACE(2))
 		+ISNULL(AUT08_R8_DATA_ESECU_CON_PREV,SPACE(8))
		+ISNULL(AUT08_R8_FILLER,SPACE(1268))	
		+ISNULL(AUT08_R8_FILLER100,SPACE(100))			
	FROM DBO.TB_AUT08_OSIRIDE_TR08 
	WHERE [AUT08_R8_COD_LIQUI] is not null
	AND AUT08_R8_CODICE_FISCALE = @CodFisc;	
		
END
